### ISSUE TITLE
Update cell in tableview

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#10]
When you update one cell in tableview you have to move focus to another row, or you will lose new data.
To reproduce it: show tableview, update value in one cell, go to another cell in same row, switch to another "view" without leave updated row. This value is lost.
Suggestion: we will need to save value into db right after lost focus in updated cell.

**Comment by fvacek** [comment]
implemented in 42c5b7965532fa59943f2129132b0d8cdf9606fe
