### ISSUE TITLE
Konzistence databaze v case

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#102]
Chapu ze je potreba obcas zmenit schema DB.
Ale uz ponekolikate se mi stalo ze stara data nejdou pouzit protoze mezitim se zmenil/pribyl nejaky sloupec v tabulce a program si s tim nevi rady.
Posledni pripad je pridani sloupce do classdefs, a kdyz uz mam data na zavod nachystana tak musim tento sloupec do db pridat rucne.
Predpokladam ze pouzitelnost dat neni omezena skoncenim zavodu/vydanim nove verze ?

**Comment by fvacek** [comment]
Obcas proste musim pridat sloupec, bez toho se dal nedostanem. Pokud chces pouzit starsi zavod v nove verzi, staci ho naimportovat do nove verze. Nejsem debil :)

**Comment by arnost00** [comment]
To je mi jasne ... jen mi docela dalo zabrat nez jsem nasel ze je novej sloupec :( ... vicemene az studiem commitu. 
Mno, import me jako prevodni/updatovaci feature nenapadla ... to bude chtit pak zminit v doku/wiki.

**Comment by fvacek** [comment]
urcite to zmin, ja na to posledni dobou mam malo casu
