### ISSUE TITLE
Jak zařídit, aby byl závodník DISK?

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#103]
Možná toto je spíše dotaz, co dělám špatně.

Experimentuji s programem a mám čipy plné mezičasů, které jsou totálně jiné než sledy testovacího závodu. Přesto všechny vyčtené čipy jsou "OK", závodníci nemají nastavený příznak DISK a lze vytisknout výsledky, kde jsou seřazeni podle podivných časů.

Jak funguje kontrola ražení?

Jak může vzniknout např. následující mezičas bez toho, aby tam někde bylo slovíčko DISK?

=========================================
```
Mistrovstvi oblasti ve sprintu
2016-04-08 Benatky nad Jizerou, sportovni areal Letni stadion
-----------------------------------------
D10 Hora Vojtech                  PGP8301
SI: 1006283                     2.3km 25m
Check: 11:07:05          Finish:  0:18:11
Start:  0:20:00/20.00          SI:1006283
  1.   69      0.00      0.00      0.00
  2.   93      0.00      0.00      0.00
  3.   61      0.00      0.00      0.00
  4.   83      0.00      0.00      0.00
  5.   94      0.00      0.00      0.00
  6.   82      0.00      0.00      0.00
  7.   32      0.00      0.00      0.00
  8.   74    665.28      0.00      0.00
  9.   63      0.00      0.00      0.00
 10.  100    717.45      0.00      0.00
       FI    718.11      0.26      0.00
poradi:2/2                   312.15min/km

```
Díky,
Vojta

**Comment by VoiToi** [comment]
Doplňuji, že v čipu jsou kontroly v následujícím pořadí:
31,34,71,40,70,74,78,57,81,80,70,73,53,54,77,59,52,50,70,75,42,67,39,33,72,100
a oražené v rozmezí 11:11:24 - 12:17:45.

Tedy jediné oražené kontroly z trati D10 jsou 74 a 100, ostatní chybí a závodník by to měl a neměl by figurovat normálně ve výsledcích s časem 710:11.

Nebo je nutné závodníky diskat ručně zaškrtnutím checkboxu a kontrolovat ražení jako ve 20. století? ;-)

**Comment by VoiToi** [comment]
a ještě doplňuji, že to bylo testováno v poslední verzi 0.1.12 beta EN a předtím v 0.1.9, obojí se stejným výsledkem.

**Comment by arnost00** [comment]
Potvrzuji ... taky nevim jak to nastavit automaticky.

**Comment by fvacek** [comment]
To je nejaka regrese, trochu jsem to predelaval a asi ne moc dobre, diky za upozorneni, zejtra pri zavodech bych to opravovat nechtel

**Comment by fvacek** [comment]
zkousel jsem cip, ktery mel orazenou pouze sberku s timto vysledkem

![1](https://cloud.githubusercontent.com/assets/4949019/14222416/c9caf930-f870-11e5-87e4-5c8f579b9abc.png)

**Comment by arnost00** [comment]
Potvrzuji ze neco podobneho jsem videl taky ... ty cervene kontroly jsou co vsechno chybi. 
Jedine co jsem objevil je ze se v Classic.qml :
 - nikam nezapisuje hodnota z error_mis_punch 
 - nenaplni se hodnota checked_card.setMisPunch

Zkusil jsem pridat proste prirazeni, ale asi spatne :(

**Comment by arnost00** [comment]
Chyba nalezena a bude opravena v nekterem nejblizsim commitu

**Comment by fvacek** [comment]
fixed in 9e61e5b7fc35917f73fbae367835b795412aeac4
