### ISSUE TITLE
Znovuzpracování čipu, rekonstrukce výsledků v CardReaderu

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#104]
Ahoj,

zajímalo by mě, zda je možné ve stávající verzi nějakým způdobem říci, aby se "znovu zpracoval"
vyčtený čip. Případně, jaký je doporučovaný postup v případě, že:
- závodník třeba běžel jinou kategorii než měl,
- závodníkovi se chybně vyčetl čip a přitom vyčítací krabička pípne jako že OK (možná tedy sedí CRC - ano, toto zní nepravděpodobně, ale z mých zkušeností se to se SportIdentem a OBReadSI stávalo třeba jednomu z 1000 čipů).
- změním třeba čas startu, tj všem by se měl změnit výsledný čas (když se startérům něco hodně nepodaří - lze provést něco jako rekonstrukci výsledků)?

Samozřejmě mě napadlo vymazat záznamy z tabulky cards, ale pak nevím jistě, kde by se mělo mazat dál, jestli v runs, runlaps, punches ... a při závodě bych to takto dělat nechtěl, riziko smazání něčěho blbě je velké.

Díky, Vojta

**Comment by VoiToi** [comment]
K tomuto doplňuji: Pokud vyčtu čip a závodník je disk z důvodu chybně zadaných sledů,
pak upravím sledy, mohu znovu vytisknout čip, ale závodník zůstává DISK ve výsledkách (a v seznamu závodníků).
Toto je problém - mohu vytisknout lísteček s tím, že ražení je OK a přitom ve výsledcích bude závodník nadále DISK. Pokud lze znovuzpracovat závodníka tím, že mu znovu vytisknou mezičas, pak by to chtělo přitom znovu přenastavit příznak DISK.

**Comment by fvacek** [comment]
Jsou dve moznosti:

* v pluginu CardReader kliknout pravou mysi na kartu a dat Assign card to runner. Tim se cip priradi k zavodnikovi a prepocita se mu cas a status a zkontroluje razeni.
* v pluginu Runs, kliknou pravou na zavodnika a dat Load times form card in selected rows, tim se zavodnikovi prepocita cas a status a zkontroluje razeni. Lze oznacit vic radku.

**Comment by VoiToi** [comment]
Prosím o doplnění možnosti "Přepočítat" nebo něco podobného přímo do modulu Card Reader.
Je to intuitivně jediné místo, kde to člověk hledá, navíc v případě, že chci opravit třeba prvních 25 načtených čipů, nebo 5 posledních, je to taky nejjednodušší.

**Comment by fvacek** [comment]
done
