### ISSUE TITLE
Práce s vakanty

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#105]
Jak lze vytvořit vakanty?

Pokud v nějaké kategorii vytvořím x vakantů před, v průběhu i po a dám nalosovat,
tak se žádní vakanti nevytvoří.

Jaký ja na to trik? Nebo ještě vakanti vůbec nejsou?

Existuje už workflow pro prezentaci, kdy lze dohlašovat jen do vakantů?
Jak?

Pokud funkčnost vakantů a dohlašování na ně existuje, jsem ochoten to po naučení se zdokumentovat tady na wiki.

Díky, Vojta

**Comment by fvacek** [comment]
V soucasne implementaci se pri losovani vytvori n1 vakantu pred n3 vakantu po a jeden vakant po kazdych n2 zavodnicich.

Do budoucna to planuji zmenit na n1 vakantu pred n2 vakantu v startovnim poli a n3 vakantu po. Asi pujde i volba vypocitej n2 = pocet_map - n1 - n3 - pocet_prihlasenych

**Comment by paukert** [comment]
Pro dopočítání vakantů ve startovním poli (n2) lze použít funkci use all maps
