### ISSUE TITLE
Chyba exportu výsledků

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#106]
Při pokusu o export výsledků do IOF XML ve verzi 1.14 je zobrazena chyba:
QML ERROR: "file:///C:/Programs/OB/QuickEvent/qml/quickevent/Runs/Results.qml:241: TypeError: Property 'msecToHMS' of object [object Object] is not a function"

Žádný exportní soubor se pak nevytvoří.

**Comment by arnost00** [comment]
Uz je v procesu reseni ... chybi funkce v ogtime.js

**Comment by fvacek** [comment]
Nahradil jsem ji funkci TimeExt.toString_hhmmss

**Comment by arnost00** [comment]
nasel jsem jen : TimeExt.msecToString_hhmmss

**Comment by arnost00** [comment]
Oprava v #109 ... chova se jak puvodni fce v ogtime
