### ISSUE TITLE
Chyba tisku diplomů

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#107]
Toto asi bude prkotina a mě to nijak při pořádání zatím neomezuje, ale nefunguje tisk diplomů.
Při pokusu o tisk se zobrazí chyby a výsledný tisk je prázdný:
Erorr loading report component: "file:///C:/Programs/OB/QuickEvent/qml/quickevent/Runs/reports/results_stage_awards.qml:1 Invalid regular expression flag 'f'\n"
Error creating root object from component: QQmlComponent(0x5d5d3a0) QUrl("file:///C:/Programs/OB/QuickEvent/qml/quickevent/Runs/reports/results_stage_awards.qml")
Created object: QObject(0x0)
"file:///C:/Programs/OB/QuickEvent/qml/quickevent/Runs/reports/results_stage_awards.qml:1:1: Invalid regular expression flag 'f'"

**Comment by fvacek** [comment]
Prkotin to uplne neni, je to kostlivec ve skrini a uz je cas to nejak poresit :)
