### ISSUE TITLE
Vysledky - chyba u poradi pokud maji zavonici stejny cas

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#112]
Nalezena chyba pri exportu i tisku vysledku.
Pokud zavodnici maji stejny cas, dostanou jine poradi. Chyba se vyskytuje jak v tisku (pdf), tak v exportu IOF formatu.
ORIS pri importu vysledky prebira tak jak jsou, poradi si neupravuje.

Spravne by pri stejnem casu meli mit oba zavodnici stejne poradi a dalsi poradi by melo pokracovat s vynechanim.
Priklad jak by to melo vypadat:
`1. Zavodnik A  38:00`
`2. Zavodnik B  40:00`
`2. Zavodnik C  40:00`
`4. Zavodnik D  42:00`

**Comment by frantisekpasek** [comment]
Prosím opravit.

**Comment by Paukert** [comment]
Na tuto chybu jsme včera při pořádání sprintu také narazili.
Chyba se vyskytuje úplně všude - export, tisk výsledků, tisk diplomů.

**Comment by fvacek** [comment]
closing as duplicate
