### ISSUE TITLE
Startovni cisla / Start numbers support

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#113]
Chybi podpora prirazeni startovnich cisel zavodnikum.
Minimalne pro pouziti v zavodech zebricku A, MCR a  vubec MTBO bude potreba je doplnit.

**Comment by arnost00** [comment]
Popis co je pro potrebu prideleni startovni cisel udelat :
 - sloupec u zavodnika s pridelenym cislem
 - sloupec v kategoriich (prvni startovni cislo)
 - funkce nad kategoriemi - prideleni startovnich cisel (postupne v kategorii )
 - upravit tisky startovek, tak aby zobrazovali startovni cisla (po klubech / po kategoriich)
 - vymyslet jak jednoduse zajistit spravne startovni cislo kdyz (tyka se vicemene prezentace) :
  - je dohlasen zavodnik do vakanta
  - pri zmene/zamene casu zavodnika (automaticky / rucni aktualizace pomoci funkce v UI)

Pozn. Pokud vakanti budou bez zaznamu v databazi bude mozne pridelovat startovni cisla pouze postupne v kategorii. Nahodne ci jine nepravidelne by nejspis bylo pri dohlasovani problem dopocitat + by se musel uchovavat jaky je vybrany zpusob pridelovani.
Otazka je zda je vubec potreba nejake jina metoda prideleni startovnich cisel ?

**Comment by xkenia** [comment]
V prvni verzi pripravim import/export a startovku s cislama.

**Comment by fvacek** [comment]
Pokud maji st. cisla tvorit souvislou radu, jze je jednoznacne vypocitat ze startovnich casu i bez vakantu ve startovce. Pokud ne, muzou byt prirazeny jakymkoliv zpusobem.

**Comment by VoiToi** [comment]
Prosím o doplnění možnosti tisknout startovní čísla ve:
- startovce po oddílech (na MTBO se startovky po oddílech tisknou právě proto, aby se daly do obálek a závodníci si podle nich rozdělili startovní čísla, bez čísel je to k ničemu).
- startovce pro startéra

Startovku se startovními čísly pro oddíly jsem nakonec dělal v ultraeditu a excelu z toho, co jsem vykopíroval z okna runs ... naštěstí na to byl čas.

Díky, Vojta

**Comment by Osin01** [comment]
Pokud tisknu startovku se startovními čísly i s vakanty, tak u vakantů tam je místo startovního čísla "undefined" a rozhodí se to na dva řádky.

**Comment by xkenia** [comment]
Osvedcilo se mi i copy&paste z excelu primo Zavodnici -> SČ.

Jen je potreba vzit v uvahu, ze se cisla kopiruji podle id, a je jedno, ze mate zavodniky serazene podle neceho jineho.

**Comment by arnost00** [comment]
Tisk startovnich cisel by mel byt opraven (undefined uz to netiskne).
Startovka po oddilech uz muze obsahovat take startovni cisla.
Startovka pro startery muze startovni cisla.
Pull request #416

**Comment by paukert** [comment]
Ve verzi 2.3.3 nelze vytisknout startovní listinu se startovními čísly:
- po klubech
- pro startéry
- po klubech n etap

**Comment by fvacek** [comment]
implemented in 2.3.4

**Comment by otahirs** [comment]
Startovní číslo by se mělo dát editovat i v `edit competitors` dialogu.

offtopic: Imho `SN`, `Reg` a `Ranking` by v tabulce competitors nemělo být editovatelné, vždy otevřit dialog
