### ISSUE TITLE
"Not competing" logic / logika "Mimo soutěž"

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#117]
Aktuální stav je ten že pokud je ručně nastaveno MS tak je dobře ve výsledcích.

Spatne se uklada do IOF XML
http://orienteering.org/wp-content/uploads/2010/12/IOFdata.txt
kam se ted ulozi jako status OK a poradi 0.

Aktualne se to nechova dobre ani v ORISu. (MS -> DISK)

Zvazit zda nejak resit automaticke MS kdyz zavodnik neodpovida vekem do kategorie?
Zvazit zda nejde nastavit pri importu z ORISu?

**Comment by arnost00** [comment]
A jeste mi neni jasno jak se prenasi pres IOF XML informace kdyz zavodnik je MS a zaroven DISK.

**Comment by arnost00** [comment]
Oprava MS do IOF XML vysledku #118

**Comment by arnost00** [comment]
Opraven i import vysledku v ORISu (Bestik).

**Comment by fvacek** [comment]
pokud vim, tak Oris stale neumi importovat vysledky v IOFXML 3.0, jestli budu neco opravovat, tak uz asi jedine tam

**Comment by frostidllo** [comment]
update: verze QE 2.2.6
chyba v exportu výsledků do iof xml 3.0
závodník označen v Úseky/Etapy jako MS (checkbox)
v exportu je u něj: <status>Inactive</status>
správně by mělo být: <status>NotCompeting</status>
V ORISu pak totiž nefiguruje závodník jako MS, ale jako DISK a to dělá bordel v počítání rankingu. Po ruční opravě přímo v xml už v pořádku. ORIS id: 4739
