### ISSUE TITLE
Export startovek dle času

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#119]
Nevidím nikde export startovek dle času, jen dle kategorií nebo klubů. Tisk dle času je, to je důležitejší, ale i export se někdy hodí (zatím místo exportu tisknu do souboru).

**Comment by fvacek** [comment]
K cemu to potrebujes a jaky format by se ti hodil?

**Comment by OndrejSpanel** [comment]
Už k ničemu. Chtěl jsem to jen kvůli kontrole před závodem. Tisk umí export do PDF, to jsem nečekal, čekal jsem, že to bude přímo tisknout. Export do PDF mi úplně stačí.
