### ISSUE TITLE
Startovky po klubech - odstránkování

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#120]
Když dávám tisk startovek po kategoriích, nabízí se mi možnost odstránkování (Break after each class). Při tisku po klubech takovou možnost nevidím - každý klub na zvláštní papír je přitom dost potřebné.

**Comment by viktorm2015** [comment]
souhlasím, tomu se Fany asi nevyhneš. I dnes ještě někdo rozdává na prezentaci obálky ...

**Comment by fvacek** [comment]
done
