### ISSUE TITLE
Formáty startovek nepraktické pro zveřejnění v ORISu

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#121]
Startovky jde tisknout (třeba do PDF) nebo exportovat do HTML. Ani jeden tento formát není moc vhodný pro zveřejnění v ORISu (viz např. přílohy u http://oris.orientacnisporty.cz/Zavod?id=3316, jako je http://oris.orientacnisporty.cz/files/3316_9ecd8573184a2d359cf6a7a1d7ba3811.pdf)

Špatně se z toho kopíruje a uspořádání ve dvou sloupcích vedle sebe působí divně, stejně jako rozdělení na stránky.

Z toho, co QE v tuto chvíli umí, by funkčně vhodnější byl výstup z exportu do HTML, ale ORIS nedovoluje vkládat HTML přílohy.

Nějaký jednoduchý textový výpis by byl praktičtější, viz třeba výstup konkurence na http://precek.cz/ob/scp/16oz/?page=4

**Comment by fvacek** [comment]
IOF-XML v.3 export implemented
