### ISSUE TITLE
Automatic results printing

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#122]
This feature was somewhere already mentioned. Automatic printing of results of classes with over 5 changes or with any change after 20 minutes (or with silghlty higher intervals) would free the organizer of many redundant manual actions during the competition.

I have created a very temporary "workaround" - the select of last changed classes from certain row ID
in SI reading view. You can paste the result into "Class names" filter in the print dialog.
You have to set the row ID of last printing and update it every time.

```
SELECT trim(both '{}' FROM cast(array_agg(kategorie.NAME) AS text)) AS kategorie FROM (
    SELECT classes.name AS name, 1 AS radek FROM cards
        JOIN runs ON (runs.id = cards.runid)
        JOIN competitors cmp ON (cmp.id = runs.competitorid)
        JOIN classes ON (classes.id = cmp.classid)
    WHERE cards.id > 60 -- ZDE LZE NASTAVIT ID VYCTENEHO CIPU, OD KTEREHO TISKNOUT ZMENY
    GROUP BY classes.name
    ORDER BY count(*) DESC) kategorie
GROUP BY kategorie.radek
```

Result looks like this: `H21C,H35,D21C,D35`. It's sorted from class with most changes to least changes. If you want to see actual number of changes in each class, you can use this simpler select:

```
SELECT classes.name, count(*) FROM cards
    JOIN runs ON (runs.id = cards.runid)
    JOIN competitors cmp ON (cmp.id = runs.competitorid)
    JOIN classes ON (classes.id = cmp.classid)
WHERE cards.id > 60
GROUP BY classes.name
ORDER BY count(*) DESC
```

Result looks like this:

```
name    count
H21C    8
H35     3
D21C    2
D35     1
```

I hope this will soon be useless and the printing will be done automatically.

**Comment by fvacek** [comment]
Have you tried Print_New feature on the EventStatistics window?

**Comment by VoiToi** [comment]
Please simplify results printing.

Now I need to:
- select classes with new results (which is irritating / impossible when people are reading new cards because of window refresh)
- click very small printer icon
- select page layout
- click OK (or Enter)
- click Printer
- clik OK

It should be **one click action** to print new resunts with default values remembered:
- remember printer settings,
- remember page layout,
- remember number of new results.

**Comment by fvacek** [comment]
done in 1.1.6
