### ISSUE TITLE
Show "Not started" in the event statistics or count them as Finished.

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#123]
Event statistics is a great tool for generating results, but there is one thing which could be improved. Currently runners marked as "Not started" are counted as Not finished, which makes checking if the category can be closed hard, because you have to count Not started manually. Could Not started be shown in the event statistics, or perhaps counted as Finished?

**Comment by fvacek** [comment]
Maybe NotStarted is little bit misleading but we have no evidence if particular runner came across the starting line or not till starters do not tell us. Radio on check station in start corridor would save this situation.

**Comment by OndrejSpanel** [comment]
In our situation we used mark NS after we have received start lists after the start was closed, and starters marked those who did not start, I think this works fine for us, but it did not help us knowing how many racers are still on the course.

Reading Check stations after the start is closed would be also an option, but I do not think it is worth the effort.

**Comment by fvacek** [comment]
I added column "Off race" to runners table, you can select off-race all the competitors who didn't cross start. Event statistics ignores off-race runners so it should show more accurate sums now.
