### ISSUE TITLE
První vakant umístěn pozdě

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#125]
Když si nastavím VE (vakant each) = 5 , první vakant se vygeneruje až po 6 závodnících (při intervalu 3 tedy s časem 18), další už fungují správně. Odhaduji, že algoritmus testuje n % (VE+1), ale v nule vakanta nedá (n je pořadové číslo závodníka). Mělo by se testovat (n + 1) % (VE+1).

(Až se někdy popasuji s tím QMakem, snad dokážu dát i pull request - zatím to přeložit nedokážu).

**Comment by fvacek** [comment]
na zapas s qmake zkus pouzit QtCreator, dost to usnadnuje
