### ISSUE TITLE
Když místo výběru souboru zruším tisk, QE spadne.

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#126]
Když nastavím tisk do souboru (na Windows např. vyberu jako tiskárnu Microsoft XPS Document Writer), systém se mě zeptá, kam chci soubor uložit. Když vyberu soubor, je to v pořádku, ale pokud dám místo toho Cancel, celé QE spadne.

Totéž se stane, pokud dám na XPS tisk startovek nebo výsledku a zase dám Cancel.

**Comment by fvacek** [comment]
V QE verze 1.0.3 beta bude pouzita knihovna QT verze 5.6.0, ktera by tuto chybu uz mela mit opravenu

**Comment by OndrejSpanel** [comment]
Vyzkoušel jsem, už mi to nespadlo.
