### ISSUE TITLE
Kolize programu veverzi 1.0.2.

### ISSUE THREAD

**Issue by BincikM** [fvacek/quickbox#127]
Ve verzi 1.0.2. po nalosování startovky program zhavaruje. "This aplication has requested the Runtime to terminate it in an unusal way"

**Comment by fvacek** [comment]
0.0.8 and 1.0.2 nemaji kompatibilni data. Dej Event->Import a naimportuj 336.qbe do novejsi verze. tim se opravi datovy format

**Comment by fvacek** [comment]
issue assigned #132

**Comment by BincikM** [comment]
Ano, po importu se již chyba neobjevila, ale nutí mne to zadat jiné čísli ID závodu a v tom případě se dostávám do kolize z ORISEM. 
Další možnost je to potom znova vyexportovat, smazat původní závod a znova naexportovat pod stejný ID číslem jako je v Orisu
Takto se bude postupovat při každém upgradu?

**Comment by fvacek** [comment]
zavod si muzes pojmenovat naprosto libovolne, muzes qm soubor i prejmenovat, jeho nazev vubec nemusi obsahovat Oris ID
