### ISSUE TITLE
Špatné přiřazení VAKANTU

### ISSUE THREAD

**Issue by BincikM** [fvacek/quickbox#128]
Zadal jsem si do jednotlivých kategorií Vakanty do políčka VakantB (předpokládám, že je jsou to vakanti umístěni v průběhu celého startovního pole na rozdíl od VakantP a VakantPo. Po losování startovky mi ale naskočilo daleko více Vakantů. Např kategorie D21 jsem zadal 2 vakanty a ve startovce jich mám šest.

**Comment by fvacek** [comment]
Soucasna implementace dava vakant po kazdem VakantB-tem zavodnikovi. Asi se to casem zmeni, protoze je to matouci.

**Comment by BincikM** [comment]
To jsem nepochopil, takže položka VakantB znamená, na kolik závodníků přijde jeden VAKANT.

**Comment by fvacek** [comment]
presne tak, asi to predelam na pocet vakantu ve startovnim poli, ale nevim kdy :)

**Comment by arnost00** [comment]
Fakt ? Ja celou dobu ziju v domeni ze je to pocet vakantu. Za me tedy docela matouci chovani.

**Comment by fvacek** [comment]
see issue: Matouci funkcionalita sloupce VakantB #134
