### ISSUE TITLE
VAKANTI

### ISSUE THREAD

**Issue by BincikM** [fvacek/quickbox#130]
Při dohláškách v sekci Závodníci, chci přiřadit startovní čas, ale bohužel Startovních časů musím pracně dohledat VAKANTY,(nejsou zobrazeny barevně, jak popisuje Ondra Spanel)„_V režimu Závodníci vkládat pomocí Vlož řádek při vkládání do losovaných kategorií přidělit i čas kliknutím na "Startovní časy". Vakanty se poznají podle toho, že za nimi je další řádek zelený“_ – **Toto zobrazení v této části aplikace barevné není.**
Navíc, pokud už nemám volno ve Vakantech zobrazí se nic neříkající hláška. 
Rychlou informaci o tom, kolik mám ještě volných vakantů jsem nikde nenašel.

**Comment by fvacek** [comment]
zkousel jsi seradit tabulku vzestupne podle sloupce startovni cas?

**Comment by BincikM** [comment]
Ne nezkoušel, až teď a zobrazili se mi zelená pole přesně podle popisu. Připadá mi to jako dva kliky myší navíc. Dělám těch závodů cca 10-20 do roka a vím, že dohlášky jsou vždy krizové místo, kde by mělo být co nejmíň operací.

**Comment by fvacek** [comment]
je to tak, zareportuj to prosim, jako chybu

**Comment by fvacek** [comment]
informaci o zbyvajicich mapach najdes v okne Event statistics, nevim jak je to prelozeno

**Comment by BincikM** [comment]
Ano, toto jsem našel, zobrazí se potom okno vpravo dole, Zatím to není přeloženo a je to ve volbě Zobrazení - Event Statistics
