### ISSUE TITLE
Zobrazení Registrace

### ISSUE THREAD

**Issue by BincikM** [fvacek/quickbox#133]
Při práci s programem, mám zaškrtnuto "Zobrazit Registraci".
Při opětovném spuštění aplikace, se mi zobrazí okno s Registraci, ale nejsou v něm žádná data, až po stisknutí tlačítka Refresh (Obnov) se Registrace načte.

**Comment by Paukert** [comment]
Myslím si, že tato chyba je již opravena.

**Comment by fvacek** [comment]
ano je uz opravena
