### ISSUE TITLE
Matouci funkcionalita sloupce VakantB

### ISSUE THREAD

**Issue by BincikM** [fvacek/quickbox#134]
Předpokládál jsem, že položky VakantP - představují počet Vakantů před startovním polem, VakantPo - počet Vakantů po startovním poli a VakantB - počet Vakantů v průběhu startovního pole. není tomu tak.
Z praxe pořádání závodů si převážně volím kolik chci Vakantů, nechám je rozlosovat náhodně a teprve potom si s jednotlivými kategoriemi pohraji, kam jednotlivé vakanty umístím. U některých dám vakanty dozadu, protože kategorie je dlouhá a předpokládám, že Vakanty nenaplním.
Klidně bych ponechal VakantP, VakantB a VakantPo, ale dal bych jim funkcionalitu skutečný počet Vakantů před, vakantů v startovní poli a vankantů po startovním poli.
Potom bych zavedl kontrolu na počet závodníků + VanatP + VakantB + VakantPo se musí rovnat Počet map

**Comment by OndrejSpanel** [comment]
>Z praxe pořádání závodů si převážně volím kolik chci Vakantů
> počet závodníků + VanatP + VakantB + VakantPo se musí rovnat Počet map
Rozhodně. Zrovna jsem podle počtu map rozpočítával vakanty pro závod se 43 kategoriemi (http://oris.orientacnisporty.cz/Zavod?id=3816) a docela jsem si to užil.

**Comment by fvacek** [comment]
je to tak, zvysil jsem prioritu

**Comment by OndrejSpanel** [comment]
Ideální by bylo, kdyby to nové VakantBěhem fungovalo tak, že to dá vakanty tak rovnoměrně, jak to jen jde, a pak ještě přidá na konec tolik, kolik je potřeba. Jen pomocí současného VakantB totiž nejde dosáhnout každého cílového počtu. Příklad: kategorie se 14 závodníky, chci přidat 5 vakantů. VakantB = 3 přidá 4, VakantB = 2 ale už 7.

**Comment by fvacek** [comment]
done
