### ISSUE TITLE
Negative start time for runner

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#135]
You cannot set negative start time (minus time) to racer. Sametimes you need to someone run earlier.

**Comment by fvacek** [comment]
I'm not quite if it worth to do it. Negative numbers requires wider columns in reports etc.

**Comment by jmacura** [comment]
I support such functionality. It is not common, but sometimes used and desired feature.
Q: Can be proposed start time suppressed by the use of "start" box? It would a sufficient workaround.

**Comment by fvacek** [comment]
Do you mean, to use start station for negative starts?

**Comment by jmacura** [comment]
exactly

**Comment by paukert** [comment]
Duplicate of #241
