### ISSUE TITLE
Import lokálního závodu z Orisu

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#139]
Do QE nelze z Orisu naimportovat "lokální závod".

**Comment by fvacek** [comment]
Co je lokalni zavod?

**Comment by arnost00** [comment]
Zavod, ktery neni oficialni CSOS, ale je zalozen v ORISu.
Jejich zobrazeni se povoluje v ORISu pomoci "Zobrazit včetně lokálních závodů"
v ORIS API : getEventList  ma nepovinny parametr :  pokud je nastaveno all=1 pak zobrazí i ostatní závod mimo oficiální kalendář
staci ?

**Comment by frantisekpasek** [comment]
Rádi bychom tuto funcionalitu použili při pořádání v první půlce května. Bylo by možné to do té doby vyřešit? Díky moc!

**Comment by fvacek** [comment]
Oris Id zavodu pujde, krome vybrani z listu, i vlozit primo.

**Comment by frostidllo** [comment]
A tato funkce již funguje? Nebo "pujde" znamena v pristim updatu?
Při postupu: soubor -> závod -> vytvořit závod můžu v následující tabulce editovat všechna pole až na "import ID" což je dle mě ta klíčová funkce (ID našeho závodu jak zmiňoval Fanda je 3603)
Adam Hájek

**Comment by fvacek** [comment]
Zatim, bohuzel, existuje pouze v mych predstavach. Je to ale lehky, tak bych to mohl dnes stihnout.

**Comment by fvacek** [comment]
done

**Comment by fvacek** [comment]
vyzkousejte verzi 1.0.4

**Comment by frostidllo** [comment]
diky za upravu, uz se zavod da alespon napul nacist.
dostanu se pres import az do dialogu "Upravit závod", vse vyplnim a pak dam OK
bez pripojeni k SQL databazi mi to vypíše chybu "Nelze vytvořit závod, databáze není otevřena: out of memory Error opening database"
myslel jsem, ze by to melo fungovat i kdyz budu mit soubory ve slozce, tedy offline.
v opacnem pripade nastuduju jak se pripojit na SQL databazi...

**Comment by fvacek** [comment]
Ne, musi to jit na lokale, to jsem tam zavlek jknou chybu. Ktery zavod jsi importoval?

**Comment by frostidllo** [comment]
importoval jsem zavod s ID 3603 - 11.5. PPŽ v Praze

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/14900562/683ad2e0-0d91-11e6-8f81-e9e7e578d633.png)

ahoj neni to velka chyba, ale je. Neslo ti to, protoze jsi nevybral typ uloziste, viz screen-shot. Nabidka importu by nemela byt aktivni. Vyber _Single file_, zadni zavod a pujde to naimportovat, zkousel jsem to.

**Comment by frostidllo** [comment]
už se mi to tam podařilo nahrát. asi jsem neměl vytvořenou tu složku na kterou jsem dokazoval.
už mi to tam hodilo přihlášené závodníky a tak. díky :)

**Comment by fvacek** [comment]
udelal jsem na to issue #151
