### ISSUE TITLE
Win32 build of QML plugins broken

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#14]
DESTDIR of QML plugins DLL libraries had changed. It is fixed for Linux build but Windows build is still broken.

see
quickbox/quickevent/plugins/qml/Core/Core.pro
quickbox/quickevent/plugins/qml/Core/Logging.pro
quickbox/quickevent/plugins/qml/CardReadout/CardReadout.pro

**Comment by arnost00** [comment]
QML copy in windows build updated & fixed.

**Comment by arnost00** [comment]
Problem with ORIS QML plugin which isn't in solution tree so it isn't copied in build dir.

**Comment by fvacek** [comment]
Pure QML plugins are not part of qmake build tre so far. I suggest to copy them manually in development phase. Installation (InnoSetup) software can copy them explicitly during installation.

Second option is to add pure QML plugins installation to build receipe of other c++ plugin (Event, Core ???)

**Comment by fvacek** [comment]
fixed in 29f723b8419138b9c8f13fea6471f78135016d9e
