### ISSUE TITLE
Duplicitní číslo čipu

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#140]
Při pokusu o uložení stejného čísla čipu, který již má někdo přiřazen, to vrací nepěknou neuživatelskou hlášku:

![duplicitni-cip](https://cloud.githubusercontent.com/assets/18633350/14763129/0bc9a534-098d-11e6-8c00-4015fd0ec35a.png)

**Comment by fvacek** [comment]
2 zavodnici nemohou mit soucasne stejny cip ani v programu ani v zivote. Hlaska je v poradku.

**Comment by mezkov** [comment]
Myslím, že tahle stížnost byla mířena na text té hlášky. Kontrala duplicity čipů je OK, ale z té hlášky by mělo být poznat, že to selhalo právě kvůli duplicitě.

**Comment by fvacek** [comment]
Aha :)
