### ISSUE TITLE
Smaž vybrané řádky

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#142]
1. "Závodníci"
2. označím více řádků
3. přes tlačítko (pravé tlačítko myši) "Smaž vybrané řádky" se pokusím řádky smazat
4. nic se nestane

**Comment by fvacek** [comment]
Oznacene zavodniky lze od verze 1.0.7 smazat stiskem tlacitka pro smazani radku nebo klavesovou zkratkou Ctrl+Del
