### ISSUE TITLE
Import competitors from CSV file

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#143]
Neexistuje možnost naimportovat závodníky mimo Oris.

**Comment by fvacek** [comment]
Z jakeho formatu?

**Comment by frantisekpasek** [comment]
Jde mi o to jak dostanu importem do QE závodníky aniž bych použil Oris. Je tu nějaká možnost? 
Formát může být třeba povinný formát ČSOS pro přihlášky, CSV, XLS, ...

**Comment by VoiToi** [comment]
Příklad jak to prozatím jde (ale pozor na bug - issue #177):

Pozor - v tomto případě jsou v datech i startovní časy.
Kdyby někdo chtěl, mohu mu dodat export z OB2000, který generuje tato data.

insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
 values (2260, case when trim(' ') = '' then null else 00000 end,
 (select id from classes where name = trim('D35B')), trim('Veronika '),
 trim('Ondráčková '), 'EKP7850', 'C', case when 2045231 = 0 then null else 2045231 end, 2260);
 insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
 values (2260, 2260, case when 2045231 = 0 then null else 2045231 end, 1, 41 * 60000,
 case when trim('ne ') = 'ne' then false else true end);
 insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
 values (2677, case when trim(' ') = '' then null else 00000 end,
 (select id from classes where name = trim('H21C')), trim('Jakub '),
 trim('Hruška '), 'ZBM9515', 'R', case when 1591995 = 0 then null else 1591995 end, 2677);
 insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
 values (2677, 2677, case when 1591995 = 0 then null else 1591995 end, 1, 40 * 60000,
 case when trim('ne ') = 'ne' then false else true end);
 -- ...

**Comment by fvacek** [comment]
Ahoj, napsal jsem import z CSOS at mame alespon neco. Asi by se hodil i import z CSV, abychom mohli uzavrit tuto issue. Kdys se podivate na funkci TxtImporter::importCompetitorsCSOS(), bude to fakt hracka pro nekoho, kdo by chtel pomoct. Ja ted poradam HSH, takze nemuzu.

**Comment by fvacek** [comment]
done
