### ISSUE TITLE
Import a přiřazení půjčených čipů

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#146]
Umožnit hromadně naimportovat a přiřadit čísla čipů závodníkům, kteří v přihlášce zažádají o jejich zapůjčení. Zároveň u závodníků zaškrtnout příznak PČ.

**Comment by fvacek** [comment]
Tady je trochu problem s prirazenim, zavodnici, kteri si pujcuji cip vetsinou nemaji ani registraci. Import podle jmena a kategorie nebude stoprocentni.

**Comment by nitschk** [comment]
Tady by pro začátek stačilo mít možnost někam nahrát seznam čipů, které půjčuji. Aby se automaticky označil půjčený čip, pokud je z tohohle seznamu. Přiřadit čip konkrétnímu závodníkovi asi stejně budu muset ručně.

**Comment by frantisekpasek** [comment]
Nejsem si jistý, že jsme se pochopili. 
Jde mi hlavně o maximální zjednodušení přípravy před závodem. Tedy chci po tom co jsem si založil závod a naimportoval data z Orisu hromadně nahrát z nějakého souboru čísla půjčovacích čipů závodníkům, kteří o čip požádali a zároveň je označit příznakem PČ.

**Comment by frantisekpasek** [comment]
Při importu z Orisu by se příznak PČ mohl vzít z pole "Půjčit SI", resp. na základě textu "SI=ANO" v poznámce jednotného formátu ČSOS pro přihlášky.

**Comment by fvacek** [comment]
jiz lze vlozit seznam cisel cipu na pujceni, to by melo problem resit celkem dobre
