### ISSUE TITLE
Circular dependancy in plugins

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#15]
Circular dependancy in plugins between app/plugins/qml/CardReader nad app/plugins/qml/Receipes

**Comment by fvacek** [comment]
Yes, it is true, maybe there is a better solution. Dependency of CardReader is weak for now and obtained pointer is tested for null. That means that when Receipes plugin is not installed then receipe preview will not work but the application remains stable and working as expected.  RegardsFanda                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: AmarounSent: Sunday, April 5, 2015 22:18To: fvacek/quickboxReply To: fvacek/quickboxSubject: [quickbox] Circular dependancy in plugins (#15)Circular dependancy in plugins between app/plugins/qml/CardReader nad app/plugins/qml/Receipes

—Reply to this email directly or view it on GitHub.

**Comment by arnost00** [comment]
But we are talking about build dependancy (Linux & Windows). 
With circular dependancy its imposible to build Quickbox.

**Comment by fvacek** [comment]
Strange, I've no problems building quickbox on Linux, I'll try to rebuild fresh clone to reproduce this error. Fa                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: arnost00Sent: Monday, April 6, 2015 19:55To: fvacek/quickboxReply To: fvacek/quickboxCc: Fanda VacekSubject: Re: [quickbox] Circular dependancy in plugins (#15)But we are talking about build dependancy (Linux & Windows). 
With circular dependancy its imposible to build Quickbox.

—Reply to this email directly or view it on GitHub.

**Comment by fvacek** [comment]
fixed in 3cb3396c70e3f03f3c7be3bcf2da3fe71bd629d7
