### ISSUE TITLE
make dist is hitting missing files

### ISSUE THREAD

**Issue by lpechacek** [fvacek/quickbox#153]
Following files are missing in the source tree despite being mentioned in the corresponding project files:
	quickevent/app/plugins/qml/ExampleCppQml/ExampleCppQml.cs_CZ.ts
	quickevent/app/plugins/qml/ExamplePureQml/ExamplePureQml.cs_CZ.ts
	quickevent/app/plugins/qml/Speaker/Speaker.cs_CZ.ts

**Comment by fvacek** [comment]
fixed in 240f758f0390d9b261e7cc69f94d1bf965bf6fec
