### ISSUE TITLE
Verze 1.0.5 - chyby SQL

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#157]
Ahoj,

verzi 1.0.5 v kombinaci s DB PostgreSQL nedokážu program zprovoznit kvůli různým chybám:
- při startu hlásí, že data závodu jsou moc stará (1.0.4), je třeba 1.0.5.
- vytvoření závodu nejde z důvodu chyby:

```
Warning     "ERROR:  INSERT has more expressions than target columns
LINE 1: ... qpsqlpstmt_9 AS INSERT INTO ppz.stages (id) VALUES ($1, $2)
                                                                    ^
(42601) QPSQL: Unable to prepare statement" 2016-05-30T20:07:05 query.cpp   30  bool qf::core::sql::Query::prepare(const QString&, bool)
Warning     "ERROR:  syntax error at or near \"(\"
LINE 1: EXECUTE  (1, TIMESTAMP WITH TIME ZONE '2016-05-30T08:00:00.0...

```
- import závodu nejde z důvodu "Error getting current schema"

Program jsem nezprovoznil ani s čistou instalací nad prázdnou databází.

Možná funguje s SQLLite, to jsem nezkoušel.

Verze 1.0.4 je OK, s tou jsem uspořádal závod o 660 lidech a bez problému.

Vojta

**Comment by fvacek** [comment]
Ja se na to zejtra mrknu :)

**Comment by fvacek** [comment]
zkus prosim te 1.0.6
