### ISSUE TITLE
Půjčené čipy ve startovní listině po klubech

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#158]
Přidat do startovní listiny po klubech příznak čipům, které jsou půjčené.

**Comment by frantisekpasek** [comment]
Tohle asi není hotové, že?

**Comment by fvacek** [comment]
dosud ne

**Comment by frantisekpasek** [comment]
A uděláš to, prosím? 
Moc by se to hodilo při přípravě obálek na prezentaci (čipy přidělujeme předem a rovnou dáváme do obálek společně se startovkou oddílu).

**Comment by fvacek** [comment]
udelam, kdybych to o vikendu nestih nebo na to zapomnel, tak se prosim pripomen

**Comment by fvacek** [comment]
done in 1.1.16

**Comment by frantisekpasek** [comment]
Mohl bys, prosím, přidat příznak i do sestavy spuštěné přes Úseky/Etapy > Print > Start list > Kluby n etapa?

![obrazek](https://user-images.githubusercontent.com/18633350/36645007-c80ae5c2-1a62-11e8-8840-1cf415116190.png)

**Comment by fvacek** [comment]
potrebujes to nutne?

**Comment by frantisekpasek** [comment]
Ne. Jen mě napadlo, že by to tu mělo/mohlo být taky.

**Comment by fvacek** [comment]
to urcite, ja jenom nevedel jak hodne to specha
