### ISSUE TITLE
Export startovní listiny do IOF-XML 3.0

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#159]
Úseky/Etapy > Export > Start list > XML > IOF-XML 3.0 > Uložit > žádný soubor se nevytvoří/neuloží.

**Comment by fvacek** [comment]
v jake verzi QE?

**Comment by frantisekpasek** [comment]
1.0.4

**Comment by fvacek** [comment]
pro reportovani chyb je nutne pouzivat posledni verzi (1.0.6), chyby mohou byt uz davno opraveny

**Comment by frantisekpasek** [comment]
Ani ve verzi 1.0.6 se soubor nevytvoří/neuloží.

**Comment by fvacek** [comment]
fixed in 1.0.7
