### ISSUE TITLE
Zobrazit čip

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#160]
Na vygenerovaném lístečku chybí jméno závodníka, kategorie, čip, apod. a zároveň se nezobrazí informace o poslední kontrole.

**Comment by fvacek** [comment]
nerozumim, ale obavam se, ze se to nevztahuje k verzi 1.0.6

**Comment by frantisekpasek** [comment]
Vztahuje se to k verzi 1.0.4.
Na lístečku vygenerovaném přes "Zobrazit čip" chybí jméno závodníka, kategorie, apod. a zároveň se nezobrazí informace o poslední kontrole. 
Na tomhle lístečku je navíc na posledním řádku rozhozený vzhled (pětka je o řádek níže).
![a](https://cloud.githubusercontent.com/assets/18633350/15838290/81683f1c-2c3d-11e6-8954-73902b2441eb.jpg)

**Comment by fvacek** [comment]
Jmeno zavodnika je na "Zobrazit kartu", "Zobrazit cip" zobrazi razeni na cipu bez jeho kontroly

**Comment by frantisekpasek** [comment]
I ve verzi 1.0.6 chybí na lístečku přes "Zobrazit čip" ražení poslední kontroly.

**Comment by fvacek** [comment]
Last control is missing on "Show Card" report #173  created
