### ISSUE TITLE
Sestava výsledků s mezičasy pro zavody, ktere nejsou v Orisu

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#161]
Připravit sestavu výsledků s mezičasy.

**Comment by Osin01** [comment]
Při nelze zkontrolovat průběh na jednotlivých kontrolách, stačil by export do html / txt.

**Comment by fvacek** [comment]
a proc by se mely pocitat spatne?

**Comment by fvacek** [comment]
Uznavam, ze vystup s mezicasy by se mohl hodit pro zavody, ktere nejsou v Orisu

**Comment by fvacek** [comment]
mohl, ale kde na to mam vzit cas, trosku jsem doufal, kdyz jsem zacinal, ze takovymi jednoduchymi vecmi, jako je treba tato, mi nekdo pomuze. :(

**Comment by jmacura** [comment]
@fvacek (off-topic) Rozumím, že vyvíjet to v jednom člověku musí být strašně náročné, ale trochu se bojím, že tu platí rovnice: {počet lidí, kteří běhají OB} - {počet lidí, které nezajímá SW na pořádání závodů} - {počet lidí, co neumí C++ a QML} - {počet lidí, co nemají čas} = 1

**Comment by fvacek** [comment]
@jmacura v tom pripade je to 0, protoze @fvacek patri do `mnoziny lidi, co nemaji cas` :) Jinak pozadavek na QML uz moc neplati. Puvodne jsem si myslel, ze QML pritahne vyvojare, protoze JS je jednodussi nez C++, mne osobne to praci docela dost pridalo. Protoze se tak ale nestalo, postupne QML s projektu vytlacuji, pocitam, ze ho necham nakonec jen pro popis setav.

**Comment by fvacek** [comment]
implemented in QE 2.3.2
