### ISSUE TITLE
Výchozí filtr v Závodníci a Úseky/Etapy

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#162]
Přijde mi vhodnější nastavit výchozí filtr na všechny/všechno než na nějakou kategorii (pokud bych chtěl někoho hledat a nebyl bych zrovna ve správné kategorii, ušetřím si jeden klik).

**Comment by fvacek** [comment]
Na zavodech s 1000 zavodniky to zbytecne zatezuje SQL server, takze to asi nechame, jak to je.

**Comment by frantisekpasek** [comment]
Já to vidím z pohledu uživatele, kde pokud budu chtít udělat rychle nějakou změnu (typicky na prezentaci) budu muset zbytečně klikat.

**Comment by fvacek** [comment]
taky treba zbytecne dlouho cekat, nez se nacte 1000 zaznamu z SQL serveru. Navic se bavime o 2 kliknutich po startu programu.
