### ISSUE TITLE
Najít v registracích

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#163]
Čekal bych, že pokud začnu do pole psát, tak se začnou podle toho filtrovat závodníci z registrace. Nic se ale neděje. 
(v agendě Registrace závodníky naimportované mám, používám verzi 1.0.4 s ukládáním do souboru).

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/15740929/77ae99dc-28b7-11e6-9301-5fa0f586a82a.png)

ja mam pocit, ze testujes nejakou pravekou verzi

**Comment by frantisekpasek** [comment]
Jak píšu výše, používám verzi 1.0.4.

**Comment by fvacek** [comment]
a muzes prosim pouzivat 1.0.6, chyba uz muuze byt davno opravena

**Comment by frantisekpasek** [comment]
V 1.0.6 je to v pořádku.
