### ISSUE TITLE
Chybné vyhodnocení oražených kontrol

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#164]
Pokud závodník vynechá kontrolu, orazí cíl, vrátí se na trať, kde orazí chybějící kontrolu, program to vyhodnotí, že má správně všechny kontroly. Dle pravidel by ale měl být diskvalifikován (závodník se nesmí po oražení cíle vracet na trať).

**Comment by frantisekpasek** [comment]
![cil](https://user-images.githubusercontent.com/18633350/34743815-6d12ed64-f58b-11e7-942a-40d82329c53a.jpg)

**Comment by fvacek** [comment]
neexistuje zpusob, jak tohle z cipu poznat, poradatel musi zajistit, aby zavodnik toto nemohl udelat

**Comment by Osin01** [comment]
V případě, že to ale závodník zjistí až po vyčtení čipu, program by mu neměl umožnit vyčíst čip podruhé, nebo čip vyčíst ano, ale neměl by automaticky aktualizovat přiřazení vyčtenému čipu závodníkovi.
Možná už to takto v současnosti funguje, to teď nevím...

**Comment by frantisekpasek** [comment]
> neexistuje zpusob, jak tohle z cipu poznat, poradatel musi zajistit, aby zavodnik toto nemohl udelat
@fvacek Porovnáním času cíle a času kontroly se to poznat nedá?
