### ISSUE TITLE
Chybné mezičasy v exportu do IOF-XML

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#167]
V exportu do IOF-XML chybí některé mezičasy.
Nemám to teď jak otestovat, nicméně to zřejmě nastává ve chvíli, když závodník běží jinou kategorii než byl přihlášen, vyčte si => disk. Pak mu změním kategorii na tu, kterou opravdu běžel => OK, již není disk.
Následný export neobsahuje mezičasy z té kategorie, kterou opravdu běžel, nýbrž z té do které byl původně přihlášen. 
V Orisu to pak vypadá takto
![chm](https://cloud.githubusercontent.com/assets/18633350/15727954/e26acdda-2859-11e6-888f-c703ebaeb8d8.png)

**Comment by fvacek** [comment]
pokud zmenis kategorii po pribehnuti zavodnika, musis mu znovu nahrat cas z karty, jinak se mu ani nezkontroluje razeni

**Comment by frantisekpasek** [comment]
A jak se nahrává čas z karty?

**Comment by Paukert** [comment]
V záložce Úseky/Etapy (Runs) klikneš pravým tlačítkem někam v řádku daného závodníka a vybereš "Nahrát časy z čipu ve vybraných řádcích" (Load times from card in selected rows).

**Comment by frantisekpasek** [comment]
Již je to OK, díky. Kartu bych přejmenoval na čip.
Škoda, že se to neděje automaticky.
