### ISSUE TITLE
Chybějící číslo čipu v Print receipt

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#168]
Pokud přes Přiřadit čip závodníkovi někoho přiřadím na vyčtený neznámý čip a následně vytisknu obsah čipu přes Print receipt, tak lísteček místo čísla čipu (pole SI:) obsahuje nulu.
![cc](https://cloud.githubusercontent.com/assets/18633350/15728199/5bceb316-285b-11e6-8586-7744ce60a849.png)

**Comment by fvacek** [comment]
to je proto, protoze je to jina informace. Zavodnik se prihlasil s SI:0 a pak mu byl prirazen obsah SI: 301075. Je to asi trochu matouci, ale nevim, jestli to je ted akutni opravovat, protoze to asi jinak nicemu nevadi.

**Comment by xkenia** [comment]
Rekl bych, ze stejny problem jako v #169 . Pokud to bylo tak, ze puvodne zavodnik zadny cip nemel zadan, mel tam tedy 0, tak to je duplicita urcite.

Zkusil jsem pripravit pro toto opravu v cardreaderplugin.cpp, ale aktualne nejsem schopen rozumne otestovat.
+     bool ret = q.exec("UPDATE cards SET runId=" QF_IARG(run_id) ", runIdAssignTS=" + now + " WHERE id=" QF_IARG(card_id), !qf::core::Exception::Throw);
 +     //update also runs with proper SI card
 +     ret = q.exec("UPDATE runs SET siID=(select siId from cards where id=" QF_IARG(card_id) ") WHERE id=" QF_IARG(run_id), !qf::core::Exception::Throw);

**Comment by fvacek** [comment]
to by teoreticky slo, ale muselo by se jeste pred tim jeste zavolat
```sql
UPDATE runs SET siId = NULL WHERE siId=(SELECT siId FROM cards WHERE id={{card_id}})
```
protoze na siId je unikatni klic

**Comment by fvacek** [comment]
Mozna, ze nejlepsi reseni je to horni SI na listecku vubec netisknout :)

**Comment by xkenia** [comment]
Promazat ten druhy cip me taky napadlo, ale prijde mi nebezpecne se teto informace zbavit.
Navic bych to videl tak, ze pokud budes prirazovat nekomu cip z fronty, tak z techto duvodu:
1. cip neni vubec v runs => tim neni butne zadny cip nulovat, pouze se priradi a unikatnost nebude porusena
2. pokud tento cip jiz bezi (je v runs), tak se s nejvetsi pravdepodobnosti jedna o prohozeni cipu => zahlasit, zda uzivatel chce cipy prohodit

**Comment by fvacek** [comment]
to je vsechno pravda, ale vzhledem k tomu, ze tohle vsechno bychom museli podstoupit jenom proto, ze 1 zavodnik ze 100 ma na vycetce matouci informaci jsem fakt pro reseni, kdy vyhodime horni SI z reportu vycetky. 80% kodu resi 20% pripadu a ja bych tech 80% hrozne nerad udrzoval :)

**Comment by frantisekpasek** [comment]
Tak to vyhoď, ušetříš si minimálně dotazy uživatelů jako jsem já.

**Comment by fvacek** [comment]
tak ja ho vyhodim :)

**Comment by fvacek** [comment]
vyhozeno
