### ISSUE TITLE
Chybné číslo čipu v Print receipt

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#169]
Pokud přes Přiřadit čip závodníkovi někoho přiřadím na vyčtený čip a následně vytisknu obsah čipu přes Print receipt, tak lísteček v poli SI (druhý řádek) obsahuje chybné číslo čipu (toho původního závodníka ke kterému byl čip původně přiřazen).

Původní
![puvodni](https://cloud.githubusercontent.com/assets/18633350/15728363/3b042ff2-285c-11e6-8378-17f7c321f523.png)

Nové
![nove](https://cloud.githubusercontent.com/assets/18633350/15728367/42656f04-285c-11e6-8008-921140cfbe26.png)

**Comment by fvacek** [comment]
SI ve zlutem pole, je cislo cipu se kterym byl zavodnik prihlasen. Pokud je mu pak prirazen cip jiny, toto cislo se neprepisuje. System aktualne rozlisuje cip, se kterym zavodnik hodlal bezet a SI se kterym skutecne bezel.

**Comment by fvacek** [comment]
duplicate of #168
