### ISSUE TITLE
Nejde vytvořit první kategorii

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#171]
Pokud neimportuji závod z ORISu, ale vše od začátku dělám v QuickEvent (což se mi zrovna stalo, protože připravuji měřený oddílový trénink), nedaří se mi vytvořit první kategorii.

V okně `Kategorie` je tlačítko `Vlož řádek` neaktivní (šedé a nejde na něj kliknout).

Přidávám qbe soubor, ve kterém problém vidím: [trial_2016_06.zip](https://github.com/fvacek/quickbox/files/299932/trial_2016_06.zip)

Když přidám ručně v SQL po jednom řádku do tabulek `classes` a `classdefs`, další kategorie už zakládat jde.

**Comment by fvacek** [comment]
fixed in 1.0.7

**Comment by janzhanal** [comment]
Ahoj, 
velmi podobny problem v 1.1.12 (Centos 7.4), tlacitkova lista neni vubec videt.
![quickevent1](https://user-images.githubusercontent.com/34436593/33820900-e9fe6174-de51-11e7-95e5-ddccf8517b10.png)

a data zde: [test.qbe.zip](https://github.com/fvacek/quickbox/files/1546959/test.qbe.zip)

**Comment by fvacek** [comment]
problem je v tom, ze aby bylo mozne vytvaret kategorie, je treba nejprve nadefinovat trate a priradit jim kody, potom tabulka zazracne ozije. Asi to je trochu ukryty, zaroven to ale dava smysl.

**Comment by fvacek** [comment]
fixed
