### ISSUE TITLE
Možnost importu dat závodníků z TXT souboru

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#172]
Rád bych naimportoval seznam závodníků, který jsem dostal v csv souboru. V tabulkách vidím v kontextovém menu možnost Import, ale zatím nikdy jsem ji neviděl jako aktivní, stále je šedá (zakázaná).

Formát dat je v mém případě např. `DOR7100;Ondřej;Španěl;2058506`, ale to nehraje roli, přeformátovat je můžu podle potřeby.

Existuje nějaká možnost buď obecného importu do tabulky, nebo importu seznamu závodníků? Když používám QBE soubor, je nějaká jiná možnost, jak do tabulek data dostat hromadně?

**Comment by OndrejSpanel** [comment]
Zatím jsem přišel aspoň na jeden způsob, přes SQL Query:

INSERT INTO main.competitors (registration, firstName, lastName, siId)
  VALUES
  ("DORxxx","Nnn","Mmm","AAAAA"),
  ("DORxxx","Xxxxí","Yyyyy","BBBBB")

**Comment by fvacek** [comment]
to nepomuze, musi se vytvorit jeste zaznamy v tabulce runs

**Comment by fvacek** [comment]
import v kontextove nabidce slouzi obecne pro import dat do tabulky, takze v tomto pripade take nepomuze. Import zavodniku z TXT souboru je nutne doprogramovat.

**Comment by xkenia** [comment]
stejny pozadavek jako #143

**Comment by fvacek** [comment]
closing as a duplicate

**Comment by VoiToi** [comment]
Příklad jak to jde (ale pozor na bug - issue #177):

Pozor - v tomto případě jsou v datech i startovní časy.

insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2260, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('D35B')), trim('Veronika                 '),
trim('Ondráčková               '), 'EKP7850', 'C',  case when  2045231 = 0 then null else  2045231 end, 2260);
insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
values (2260, 2260, case when  2045231 = 0 then null else  2045231 end, 1,  41 * 60000,
case when trim('ne    ') = 'ne' then false else true end);
insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2677, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('H21C')), trim('Jakub                    '),
trim('Hruška                   '), 'ZBM9515', 'R',  case when  1591995 = 0 then null else  1591995 end, 2677);
insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
values (2677, 2677, case when  1591995 = 0 then null else  1591995 end, 1,  40 * 60000,
case when trim('ne    ') = 'ne' then false else true end);
-- ...
