### ISSUE TITLE
Kolize primárního klíče po importu závodníků

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#177]
Pokud importuju závodníky pomocí SQL dotazu (viz níže) - jinak to nejde pokud zdroj přihlášek není ORIS ale třeba semifinále MČR, pak se může stát, že když chci někoho dohlásit, dojde ke kolizi primárního klíče (Chyba duplicate key constraint violation...). Při dohlášce by se mělo najít první volné ID (pomocí max(id)+1), neměla by se používat sekvence (a nebo se musí sekvence automaticky posunout).

Příklad importu závodníků:
```
insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2260, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('D35B')), trim('Veronika                 '),
trim('Ondráčková               '), 'EKP7850', 'C',  case when  2045231 = 0 then null else  2045231 end, 2260);
insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
values (2260, 2260, case when  2045231 = 0 then null else  2045231 end, 1,  41 * 60000,
case when trim('ne    ') = 'ne' then false else true end);
insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2677, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('H21C')), trim('Jakub                    '),
trim('Hruška                   '), 'ZBM9515', 'R',  case when  1591995 = 0 then null else  1591995 end, 2677);
insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
values (2677, 2677, case when  1591995 = 0 then null else  1591995 end, 1,  40 * 60000,
case when trim('ne    ') = 'ne' then false else true end);
insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2263, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('D35B')), trim('Magdalena                '),
trim('Kurfürstová              '), 'FSP7852', 'C',  case when   207837 = 0 then null else   207837 end, 2263);
insert into runs (id, competitorid, siid, stageid, starttimems, cardlent)
values (2263, 2263, case when   207837 = 0 then null else   207837 end, 1,  47 * 60000,
case when trim('ne    ') = 'ne' then false else true end);
insert into competitors (id, startnumber, classid, firstname, lastname, registration, licence, siid, importid)
values (2680, case when trim('     ') = '' then null else 00000 end,
(select id from classes where name = trim('H21C')), trim('Jan                      '),
trim('Drábek                   '), 'ZBM8511', 'C',  case when    49690 = 0 then null else    49690 end, 2680);

```

**Comment by VoiToi** [comment]
Ještě připojuji (velmi trapný) workaround.
Pokud se pokouším dohlášeného závodníka uložit pořád dokola, sekvence generovaných ID se pořád posouvá o 1 dál. Takže po X pokusech se to podaří (ale pokud byste měli souvislou řadu 1500 lidí, tak to je už fakt na palici). Jinak určitě existuje SQL příkaz, kterým sekvenci v PostgreSQL posunu dál kam chci, ale tu jsem ještě negoogloval.

**Comment by xkenia** [comment]
Podle ceho jsi tam daval to competitors.id? Podle meho je to potreba brat prave ze sekvence.

**Comment by VoiToi** [comment]
Ahoj, asi kdybych ID bral ze sekvence, tak by žádný problém nenastal. Ale ve chvíli, kdy jsem import připravoval, jsem si vyzkoušel, že data jsou v QE zobrazena korektně a to, že se tam používá sekvence jsem ještě ani netušil. A jestli mi řeknete, že je to tedy vše moje chyba a nic se opravovat nebude, tak díky a příště si dám pozor. Ale stejně si myslím, že sekvence jsou obecně zlo a program by měl umět dělat alespoň takové základní věci jako dohlásit závodníka trochu robustněji.
Jinak dovedete si představit můj první dojem, když jsem dohlašoval na prezentaci asi 10. člověka a začala se objevovat tahle chyba (než jsem pochopil pravou příčinu).

**Comment by xkenia** [comment]
Musel ses trefit nekam "dovnitr" intervalu. Moznost je pouzit tak velke id, ze budes vzdy za max(id) nebo nepouzivat id pri insertu. Pokud udelas 
`insert into competitors (startnumber, classid) values (1, 10); `
tak to projde a vlozi id = max(id)+1.

**Comment by xkenia** [comment]
Jinak to samozrejme spis chce napsat funkci pro import zavodniku. Ale na to je jiz zadan pozadavek #143 . Tudiz tento se stava duplicitnim.

**Comment by fvacek** [comment]
Jak pise Kena, jediny fix na tuhle issue je napsat funkci pro import zavodniku z TXT. Zaviram to, jako duplicitni issue.
