### ISSUE TITLE
Kontrola startovky

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#179]
Ahoj,

kontrola startovky by měla umět následující věci (všechny vycházejí z pravidel OB):
- ve stejné minutě nesmí být společný start na stejnou první kontrolu,
- nesmí jít dva závodníci ze stejného klubu za sebou,
- více kategorií se stejnou tratí musí jít za sebou (nesmí startovat prokládaně).

Takový hezký bonus by byl, kdyby se kontrolovalo i to, zda v případě více kategorií na stejné trati startují kategorie od nejsilnější (H21E, A, H20, H35 ...) k nejslabším (... D10, D75). To je v pravidlech také, akorát porovnání výkonnosti kategorií není vždy úplně jednoznačné.

Vojta

**Comment by xkenia** [comment]
- vice kategorii se stejnou trati musi mit mezi sebou rozestup alespon 2 inervalu

**Comment by fvacek** [comment]
S tim startem od nejsilnejsi k nejslabsi me to prekvapuje, treba na HSH mame kategorie H80 a H85, ktere maji cca 3km a bezci na nich maji casy pres 60, klidne i 90. Nedovedu si predstavit, ze bych je losoval na konec. Vlastne davam vzdycky super-veterany na zacatek.

**Comment by VoiToi** [comment]
Ahoj, na vícedenních jasně, tam jde o to, aby se nečekalo a i ti vetoši by nadávali, že tam jsou sami. Ale na ŽB, ŽA nebo MČR to bohužel není možné ani u vetošů. Samozřejmě ideálně na to myslí stavitel a nespojuje je vůbec se silnějšími kategoriemi.

**Comment by frantisekpasek** [comment]
- ač se to všeobecně asi dodržuje, tak si myslím, že pravidla nezakazují startovat více závodníkům ve stejné minutě na stejnou první kontrolu
- jakým trikem se nastavuje minimální rozestup mezi 2 kategoriemi na shodné trati?

**Comment by frantisekpasek** [comment]
@mezkov 
Pomocí VA(Vacants after) a VB(Vacants before) sloupečků v tabulce kategorií
// v minimálním rozestupu mezi 2 kategoriemi na shodné trati by neměl nikdo startovat, neměli by to tedy být vakanti

**Comment by fvacek** [comment]
v tom pripade to QE neumi :)

**Comment by paukert** [comment]
Duplicate of #262
