### ISSUE TITLE
Import z OCADu

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#18]
Nelze importovat trate z OCADu

Log z programu : 
<WARN>[classesplugin.cpp] inserting course "D10+H10"
<ERR>[classesplugin.cpp] "D10+H10" not found in defined classes
<ERR>[classesplugin.cpp] "D10+H10" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "D10N+H10N+HDR"
<ERR>[classesplugin.cpp] "D10N+H10N+HDR" not found in defined classes
<ERR>[classesplugin.cpp] "D10N+H10N+HDR" not found in defined classes
<ERR>[classesplugin.cpp] "D10N+H10N+HDR" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "D12"
<INFO>[classesplugin.cpp] inserting classdefs "D12"
<WARN>[classesplugin.cpp] inserting course "D14"
<INFO>[classesplugin.cpp] inserting classdefs "D14"
<WARN>[classesplugin.cpp] inserting course "D16+D55+H65"
<ERR>[classesplugin.cpp] "D16+D55+H65" not found in defined classes
<ERR>[classesplugin.cpp] "D16+D55+H65" not found in defined classes
<ERR>[classesplugin.cpp] "D16+D55+H65" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "D18+H16+D35"
<ERR>[classesplugin.cpp] "D18+H16+D35" not found in defined classes
<ERR>[classesplugin.cpp] "D18+H16+D35" not found in defined classes
<ERR>[classesplugin.cpp] "D18+H16+D35" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "D21"
<INFO>[classesplugin.cpp] inserting classdefs "D21"
<WARN>[classesplugin.cpp] inserting course "D45+H55"
<ERR>[classesplugin.cpp] "D45+H55" not found in defined classes
<ERR>[classesplugin.cpp] "D45+H55" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "H12"
<INFO>[classesplugin.cpp] inserting classdefs "H12"
<WARN>[classesplugin.cpp] inserting course "H14"
<INFO>[classesplugin.cpp] inserting classdefs "H14"
<WARN>[classesplugin.cpp] inserting course "H18+H45"
<ERR>[classesplugin.cpp] "H18+H45" not found in defined classes
<ERR>[classesplugin.cpp] "H18+H45" not found in defined classes
<WARN>[classesplugin.cpp] inserting course "H21"
<INFO>[classesplugin.cpp] inserting classdefs "H21"
<WARN>[classesplugin.cpp] inserting course "H35"
<INFO>[classesplugin.cpp] inserting classdefs "H35"
<WARN>[classesplugin.cpp] inserting course "P"
<INFO>[classesplugin.cpp] inserting classdefs "P"
<WARN>[exception.cpp] "NOT NULL constraint failed: codes.outOfOrder Unable to fetch row" "D:\ProjectsOwn\quickbox\libqf\libqfcore\src\sql\query.cpp:52 bool qf::core::sql::Query::exec(bool) " ----- stack trace ----- ""

**Comment by arnost00** [comment]
Tohle se tyka exportu souboru (tzv. v8)
HDR;D10N, H10N, HDR;0;3.200;75;S1;0.231;94;0.415;96;0.329;92;0.292;93;0.392;102;0.593;103;0.215;76;0.313;78;0.266;100;0.113;F1

Verze :
D10N, H10N, HDR	3,2	75	9	S1-94-96-92-93-102-103-76-78-100-F1
nefunguje vubec, log:
<WARN>[classesplugin.cpp] inserting course ""
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes
<ERR>[classesplugin.cpp] "" not found in defined classes

**Comment by fvacek** [comment]
importovane soubory
https://gist.github.com/fvacek/db75346173595039a7a8
