### ISSUE TITLE
Přepočet startovky

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#180]
Prosím o možnost přepočtu startovky.
Přepočet startovky by měl zachovat pořadí v kategorii dle zadaných startovních časů, ale přepočítat konkrétní časy podle prvního startu a intervalu.

Toto se hodí pro:
- načtení rozlosování (v žebříčku A, elita MTBO, WRE apod.), kde se k závodníkovi načte jen pořadí (třeba 1 ... 26), ale kategorie startuje třeba po 4 minutách od prvního startu 37. Takže chci, aby se přiřadily starty 37, 41, 45, ..., 129, 133, 137.
- složitější případy tvorby startovky, kdy pořadí startujících vypočtu mimo program
- pokud se těsně před závodem rozhodnu jednu kategorii posunout o X minut vpřed nebo vzad a už nechci hýbat pořadím (např. protože jsou vytištěná čísla apod.)

**Comment by fvacek** [comment]
existuje context menu "Shift start times in selected rows"
