### ISSUE TITLE
Při změně času startu 00 je třeba restartovat program, aby to pochopil

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#181]
Název bugu je asi samovysvětlující, dále píšu jen příběh pro dokreslení situace.

Prezentace probíhá bez problému, vyčítací krabička funguje, vyčte si 10 lidí, ale všichni mají časy 700 a více minut. Zjistím, že je blbě nastaven čas startu (logicky, to se mi nestalo poprvé ani naposled). Čas startu opravím, ale stále vše funguje blbě (i nově načtené a znovu zpracované čipy). To už mě na začátku finále MČR trochu znérvóznilo. Naštěstí vypnutí a zapnutí pomohlo ... myslím, že každý pořadatel bude rád, když tuto chvilku "napětí" nebude muset zažít.

V souvislosti s tímto prosím o zjednodušení funkce znovuzpracování načtených čipů, což jsem psal v #104.

**Comment by fvacek** [comment]
Jaka je to verze QE? Zkousel jsem to v posledni verzi a nepodarilo se mi to zreprodukovat. I ve zdrojacich to vypada OK.

https://github.com/fvacek/quickbox/blob/master/quickevent/app/plugins/qml/Event/src/Event/eventplugin.cpp#L300

**Comment by VoiToi** [comment]
Ahoj, bylo to ve verzi 1.0.4. V novější jsem to nezkoušel.

**Comment by fvacek** [comment]
Aha, tak to bude asi uz opravene.

**Comment by fvacek** [comment]
cannot reproduce in 1.0.6
