### ISSUE TITLE
Vkládání intervalů, startu kategorie

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#19]
![quickevent_2015-05-05_16-28-28](https://cloud.githubusercontent.com/assets/8378685/7474788/d907424c-f343-11e4-80f6-f7be10a9315a.png)
Zatím se mi nikdy nepodařilo dostat jakoukoliv hodnotu do sloupců Start, Interval - resp. nějakou tam dostanu ale po odejítí na Competitors a navratu zpet na Classes tam opět jsou jenom null.
Pritom se mi do logu i napise: <INFO>[transaction.cpp] COMMIT
Tak nevim. Mozna mi jenom není jasné správne workflow ...

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/7474979/30de7ae8-f345-11e4-9054-57f00b2e2508.png)

To je divny, me to funguje, zadny specialni workflow by nemelo byt potreba, kazda editace v tabulce se hned uklada na SQL server, nemam tuseni, proc ti to nefunguje. As nejdriv opravim SQLite verzi, abychom si mohli posilat data.

**Comment by arnost00** [comment]
Tyhle data jsou import z ORISu - kategorii a zavodniku a presto je porad Count (runners count) roven 0, a opet se mi nepodarilo najit jak QB donutit prepocist tohle pole.
Importy z ORISu se do db zapisou, jen oddily nevim kde prohlednout.
Jo a pouzivam Sqlite (to jsem nenapsal).

**Comment by fvacek** [comment]
kterej zavod to je?

**Comment by arnost00** [comment]
25.04.2015 - Mistrovství oblasti na krátké trati - ZBM
ORIS ID - 2959
A ty trate v issue #18 patri k tomuto zavodu

**Comment by arnost00** [comment]
Pri zapnuti DEB vypisu:
<DEB>[sqltablemodel.cpp] dirty field "classdefs.startTimeMin" type: QVariant::int orig val: "" new val: "4"
<DEB>[sqltablemodel.cpp] field is null: false
<DEB>[sqltablemodel.cpp] updating table edits: "classdefs"
<DEB>[sqltablemodel.cpp] looking for primary index of table: "classdefs"
<DEB>[sqltablemodel.cpp] checking value of field: "classdefs.id"
<DEB>[sqltablemodel.cpp] pri index field "classdefs.id" type: QVariant::int orig val: QVariant(QString, "") current val: QVariant(QString, "")
<DEB>[sqltablemodel.cpp] save edit query: "UPDATE classdefs SET "startTimeMin"=? WHERE "id" IS NULL"
<DEB>[query.cpp] >>>> ENTER FN bool qf::core::sql::Query::prepare(const QString&, bool) "UPDATE classdefs SET "startTimeMin"=? WHERE "id" IS NULL"
<DEB>[query.cpp] EXIT FN bool qf::core::sql::Query::prepare(const QString&, bool)
<DEB>[sqltablemodel.cpp] num rows affected: 0

**Comment by fvacek** [comment]
Tak to vypada, ze budu mit nejakou chybu v generovani UPDATE SQL pro SQLite, ja jedu jenom na psql, takze SQLite je uplne neotestovany

**Comment by fvacek** [comment]
Je to tim, ze jsi nenaimportoval trate, takze se to nemelo kam ulozit. Zatim jsem to fixnul tak, ze bez trati je tabulka disabled.

**Comment by fvacek** [comment]
Ted se pri importu vytvori i definice kategorii pro jednotlive etapy, takze ti to uz bude ukladat
