### ISSUE TITLE
Program losuje do startovky i lidi off-race

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#190]
Ve startovce tak vznikaly díry.
Týká se asi jen víceetapových závodů. U 5E jsme měli dost lidí, kteří chtěli jen některé dny.

**Comment by paukert** [comment]
Dodal bych, že program je tam nelosuje vždy, ale pouze pokud je vybrán způsob losování:
`Randomized equidistant clubs` nebo `Equidistant clubs`
v ostatních případech jim program nepřiřadí startovní čas.

**Comment by paukert** [comment]
Opraveno od verze 2.2.3
