### ISSUE TITLE
Půjčené čipy - návrh na předělání

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#191]
Dnes se musí zadávat u každého závodníka příznak. 
Moje idea je:
- vytvořit novou tabulku "půjčené čipy"
- do tabulky mít možnost vložit jednotlivá čísla čipů, nebo rozsahy čísel (56220-56280), případně import z csv.
- program bude vyhodnocovat podle této tabulky.

Také by bylo pěkné mít tiskovou sestavu půjčených čipů. Hodilo by se nám to jako podklad pro výpočet částky za půjčení čipů, kterou odvádíme PSOB.

**Comment by xkenia** [comment]
Tenhle napad spise smeruje k necemu jako centralni registrace pujcenych/zapomenutych/ztracenych cipu. Mit moznost importu ztracenych cipu z centralky (nutna zmen ORISu), import pujcenych (tohle se stejne deje na urovni jednotlivych cipu, takze nechat priznakem).

**Comment by fvacek** [comment]
tabulka pujcenych cipu je v QE 1.1.7
