### ISSUE TITLE
5E formát výsledků

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#192]
Výsledky za 5 etap se nevejdou na A4. Musel jsem předělávat formát, aby se nezobrazvovaly E1-E4, ale jen čas v E5 a celkový čas.

**Comment by paukert** [comment]
V #515 je připravená oprava. Změnil jsem šířku některých sloupců, aby se 5 etap ještě na A4 vešlo :)

![E5](https://user-images.githubusercontent.com/15065907/73600501-2d209900-4551-11ea-8b80-28bdcda02514.PNG)

**Comment by fvacek** [comment]
@paukert  diky moc :)
