### ISSUE TITLE
Tisk výsledků - málo lidí v kategorii

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#195]
Na přehledu event statistics je počet New results. Tisknul jsem vždy kategorie, ve kterých byl new results větší než 5 - šetření papírem. Pro kategorie DH70, ve kterých byly jen 4 lidi se tak výsledky netiskly, protože neprošly mým mentálním filtrem. To samé pak na konci závodu, kdy některé kategorie už nedobíhaly - měly 1-3 nové výsledky (poslední závodníci v té kategorii) ale ostatní kategorie ještě dobíhaly - používal jsem stále mentální filtr 5 a víc nových. Not finished úplně použít nelze - ne všichni se dostaví na start.

Celkem by se hodilo pole "čas od posledního tisknutí", připadně ještě s filtrem pro zobrazení pouze kategorií s novými výsledky (další volba k volbě auto-refresh)

**Comment by xkenia** [comment]
Overene resi: po x vysledcich nebo po y minutach.

**Comment by fvacek** [comment]
to mi prijde docela dobry

**Comment by fvacek** [comment]
done
