### ISSUE TITLE
Defaultní tiskárna i parametry pro tisk výsledků

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#197]
Dost by se hodila default tiskárna a parametry (break type) pro tisk výsledků.

**Comment by Osin01** [comment]
Nedaly se nastavit parametry tisku tak, aby se celý obsah startovek vešel při tisku (tiskárna měla příliš široké okraje). Netiskly se celá čísla čipů ve startovce pravém sloupci - musel jsem tisknout z pdf.

**Comment by fvacek** [comment]
Defaultni tiskarnu zatim lze nastavit v systemu. Okraje tiskarny jak by smet

**Comment by Osin01** [comment]
Vzhledem k tomu, že to teď začínají zkoušet malé oddíly, bylo by vhodné to udělat trochu standardně. Já dělám na počítačích docela dost, ale tohle na windows neumím / ještě nikdy jsem to nepotřeboval nastavovat.

**Comment by fvacek** [comment]
Ja na windows nedelam uz 10 let, ale pred 10 lety to na nich slo, tak to tam snad porad nekde je :)

**Comment by paukert** [comment]
Výchozí tiskárna se opravdu nastavuje v systému (ve W10 nastavení -> zařízení -> tiskárny a skenery -> vybrat konkrétní tiskárnu -> otevřít frontu -> tiskárna -> nastavit jako výchozí tiskárnu; samozřejmě jde vyhledat třeba hned tiskárny a skenery..)

Rozložení stránky lze už v QE také nastavit jen jednou a potom nastavit jako výchozí v dialogu, který se zobrazuje před tiskem.
