### ISSUE TITLE
Windows - pluginy se nenactou - Receipes & CardReader

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#20]
Stejny get ve Win i Linuxu, Linux zobrazi vlevo 5 ikon, Windows jen 3.
Konkretne Windows nenactou pluginy : Receipes & CardReader
Hlasky z konzole programu :
51<INFO>[pluginloader.cpp:129] "Receipes" solving dependency on "CardReader"
52<ERR>[pluginloader.cpp:118] "Feature id: 'CardReader' - Invalid manifest!"
53<ERR>[pluginloader.cpp:132] Cannot load feature: "Receipes" due to unsatisfied dependecies!
54<ERR>[pluginloader.cpp:133] 	!!! "Receipes" depends on: "CardReader, Core"
55<ERR>[pluginloader.cpp:156] ERROR load feature: "Receipes"

**Comment by arnost00** [comment]
Dalsi cast hlasek :
28<INFO>[pluginloader.cpp:138] "CardReader" dependency on "Core" satisfied
29<INFO>[pluginloader.cpp:143] Installing feature: "CardReader" from: "bin/qml/quickevent/CardReader/main.qml"
30<WARN>[qqmlcomponent.cpp:857] QQmlComponent: Component is not ready
31<ERR>[pluginloader.cpp:181] Error creating plugin: "bin/qml/quickevent/CardReader/main.qml"
32<ERR>[pluginloader.cpp:182] "bin/qml/quickevent/CardReader/main.qml:4 plugin cannot be loaded for module "CardReader": Cannot load library bin/qml/quickevent/CardReaderplugin.dll: Uvedený modul nebyl nalezen."
33<ERR>[pluginloader.cpp:190] Feature: "CardReader" install ERROR
34<ERR>[pluginloader.cpp:156] ERROR load feature: "CardReader" 

Pritom se na uvedenych cestach lezi vse potrebne. Nejaky napad co hledat ci proverit ?

**Comment by fvacek** [comment]
uz jsem si kvuli tomu koupil windows, tak se na to mrknu :)

**Comment by fvacek** [comment]
Problem je v tom, ze plugin loader nenajde dll na kterych CardReaderplugin.dll zavisi. Dobry reseni neznam, teda krome instalace Unixu :). Treba nekdo, s vetsi zkusenosti s Windows nejaky najde. Prozatimni reseni je pridat pred spustenim quickeventu do PATH cestu k QML pluginum. V mym pripade je to:

path=%path%;C:\proj\_build\quickbox-MinGW-Debug\bin\qml\quickevent
quickevent.exe

pokud nikdo na nic neprijde, udelame asi quickevent.bat, kterej nastavi environment a spusti quickevent.exe

**Comment by arnost00** [comment]
Hmmm, depend me nenapadl. Zkusim se na to jeste kouknout, uz jsme nekde resili postbuild stepy kvuli QT pluginum.
