### ISSUE TITLE
Startovka pro startéra s filtrem

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#200]
Pro tisk startovky pro startéra by se hodil stejný filtr kategorií, jako je při tisku výsledků. 

Na hendikep jsme měli 4 koridory a startovky pro startéra jsem musel dělat ručně exportem z DB.

Hezčí by samozřejmě bylo udělat přiřazení startů ke kategoriím a pak tisknout jen pro příslušný start.
Krásná by byla i statistika, kolik lidí projde přes ten daný start, případně i maximální počet lidí v minutě - aby jeden koridor nebyl přetížen nebo neměl nezvládnutelnou špičku.

**Comment by Osin01** [comment]
Bylo by dobré tisknout včetně vakantů. Startéři by měli vědět, kde mají okno, pokud někdo přijde později.
Vyřešili jsme to startovkou dle kategorií, ale není to ono.

**Comment by fvacek** [comment]
pokud nekdo prijde pozdeji, mel by se stavit predevsim na prezentaci, kde by mel dostat startovni cas. Starter muze takdo poslat treba 2 zavodniky ze stejneho oddilu za sebou. Nicmene pozadavek je to legitimni, ale ma malou prioritu

**Comment by Osin01** [comment]
Jistě, takové věci se dají dělat jen na malých závodech, ale běžně se tak děje (např. když někdo nestihne start kvůli hlídání dětí).

**Comment by fvacek** [comment]
Nerikam, ze vakanty do startovky pro startery nikdy nepridame, jenom jsou potreba udelat dulezitejsi veci. My jako workaround na malych zavodech pouzivame to, ze si takovy zavodnik orazi startovaci krabicku.

**Comment by Osin01** [comment]
Pokud to při vyčítání dá přednost startu ze startovací krabičky, místo času ze startovky, tak to je dobrý způsob, nemusí se dodatečně upravovat čas v programu.

**Comment by fvacek** [comment]
Ano, cas ze startovni krabicky ma v QE vzdy prednost.

**Comment by fvacek** [comment]
implemented in 2.3.0
