### ISSUE TITLE
Tisk oddílových startovek do obálek

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#203]
Chyběla mi volba page-break při tisku oddílové startovky na n etap. Startovky do obálky jsem tiskul exportem z DB a formátováním přes HTML 
Asi by šel použít stejný dialog jako pro tisk výsledků - filtr oddílů a break-type

**Comment by OndrejSpanel** [comment]
Není to totéž, co už je označeno jako hotové v #120?

**Comment by fvacek** [comment]
je :)
