### ISSUE TITLE
Tisk 5E - filtr pagebreak po kategoriích

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#204]
Na tisk výsledků po n etapách by se hodil filtr kategorií a také by se hodila volba break-type. Nemuseli bychom před vyvěšováním rozstříhávat výsledky podle kategorií.
Samozřejmě to znamená větší spotřebu papíru, ale raději budu mít méně práce s vyvěšováním.

**Comment by fvacek** [comment]
fixed in 2.3.2
