### ISSUE TITLE
Přetížení minut po startu hendikepu

### ISSUE THREAD

**Issue by opokorny** [fvacek/quickbox#208]
Naplánovali jsme starty jednotlivých vln v hendikepu v 0 a každých dalších 10 minut. Interval po hendikepu byl 2 minuty (omezená kapacita startérů)
Tím jsme ale totálně přetížili sudé minuty po ukončení hendikepu - první startoval třeba v 20, poslední v hendikepu 80, první mimo hendikep 82 a pak po 2 minutách. Takže měli stejné časy jako lidi mimo hendikep z kategorií, které šly od 0 i od 10. V lichých minutách samozřejmě startovali jen ti v hendikepu a jinak nikdo. 
Když o tom víš, tak ti to vůbec nevadí - naplánuješ start prvních do sudých i lichých minut. - např. 0, 15, 30, 45. Pro mě to však bylo nepříjemné překvapení.
Jediný způsob, jak to vyřešit je asi doplnit "offset" 0 nebo 1 minutu po ukončení hendikepu pro jednotlivé kategorie. Tím by se kategorie posunuly.

**Comment by xkenia** [comment]
Nerozbije "offset" po hendikepu celkove vysledky? Neda se to vyresit odlisnym startem kategorii hned pro prvniho zavodnika?

**Comment by fvacek** [comment]
ja bych byl taky pro to, aby se liche startovni casy zadavaly uz ve startu kategorie, je to stejna prace, jako vymysleni offsetu, pokud uz se ofset vi, muze se rovnout pricist ke startu kategorie.
