### ISSUE TITLE
Missleading error message

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#21]
Tried to start working in file database, selected menu "File/Connect to database"
in dialog "Data storage setup", sheet "Single file"
If non-existant directory is selected, error message box appears:

"Open Database Error: out of memory Error opening database" message box received

Having to select a directory inside "Single file" leads to confusion as well

**Comment by fvacek** [comment]
fixed in d21b465c8df2b7c01313912cd77f6ab7bb97f0b3
