### ISSUE TITLE
Více usnadnit zpracování požadavků na losování přes kategorie (pro lidi co chtějí třeba rozdílný start v rodině)

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#210]
Třeba po výběru v závodnících mít možnost zobrazit v dalším okně startovky kategorií, bez nutnosti odcházet z menu závodníci.

**Comment by Osin01** [comment]
Chtělo by to přidat možnost posouvat jednotlivé závodníky libovolně ve startovce tak, aby se zároveň přepočítávali časy ostatních. Jak je to nyní nastavené, je posouvání startovním polem moc složité a vede to k ignorování požadavků na start. Také by to chtělo nový sloupec s požadavkem na start, který by se načetl z Orisu.

**Comment by fvacek** [comment]
zkousel jsi drag'n'drop startovniho casu?

**Comment by Osin01** [comment]
Drag and drop funguje dobře, to je to co jsem myslel.
Já jsem to totiž losoval v OB2000, protože mi to přišlo v QE moc složité. Možná je to řešeno dobře, jen není nikde pořádně popsané jak na to, nebo jsem to nenašel.

**Comment by fvacek** [comment]
popis zatim asi neexistuje, prihlasilo se nekolik lidi, ze pomohou s dokumentaci, ale zatim nikde nic. Dokumentace je na wiki, klidne tam pripis svoje zkusenosti. Nekdo jiny bude usetren tvych problemu :)

**Comment by petrsv** [comment]
Drag and drop perfektní, ušetřil spoustu práce, ještě že jsem tu na to narazil.

**Comment by frantisekpasek** [comment]
Tahání myší je fajn, díky. Uvítal bych ale radši, kdyby se dala závodníkům nastavit dopředu nějaká priorita, kdy chtějí startovat (na začátku, na konci, v podobný čas, apod.). Program by to pak následně dle těchto priorit nalosoval a zkontroloval. Při ručním tahání hrozí, že člověk někde něco přehlédne. Těch požadavků bývá opravdu hodně.

**Comment by fvacek** [comment]
S tim nezbyva nez souhlasit, jenom to musi nekdo napsat nebo na to musi prijit rada. Ja budu ted asi psat stafety, takze to letos nevidim. Pokus by se nasel nejaky dobrovolnik, bylo by to bezva.

**Comment by paukert** [comment]
Duplicate of #149
