### ISSUE TITLE
Tisk prubeznych vysledku na termotiskarne

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#213]

**Comment by Osin01** [comment]
Možná by se hodila i startovka, hlavně pro startéry.

**Comment by fvacek** [comment]
moc tomu nerozumim, jak by to melo vypadat, jako jeden sloupec, pripadne nekolik metru dlouhy?

**Comment by Osin01** [comment]
Využití bych viděl jen pro malé závody - tréninky, na které by pak stačila jen termotiskárna. 
Formát asi tak jak je, jen jeden sloupec.

**Comment by fvacek** [comment]
oka, uz to chapu :)

**Comment by paukert** [comment]
Již hotovo #373 :-)

**Comment by arnost00** [comment]
Opraveny layouty stranek, tak aby braly ohled na zmenu sirky stranky.
