### ISSUE TITLE
Obráceně jméno / příjmení při importu z povinného ČSOS formátu

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#215]
Nejsem si tím 100 % jist, protože jsem popis povinného ČSOS formátu přihlášek nenašel, ale když jsme teď pořádali měřený oddílový trénink, tak závodníci, kteří prošli přes povinný ČSOS formát přihlášek, měli obráceně jméno / příjmení, takže pokud jsem nedostal data ve špatném formátu (nevím, jak přesně vznikala, dostal jsem je od trenérů), jedná se o chybu v QE.

Ve vstupním souboru vidím jména v následujícím formátu, s příjmením napřed (konkrétní jméno smyšlené):

<pre>
DOR0101 H             1234567 Novák Jan                 B 
</pre>

Po importu mám v tabulce jméno "Jan Novák", s příjmením na konci. Řazení podle abecedy je pak podle křestního jména, což je nečekané.

Jinak moc děkuji za ten textový import z ČSOS, hodně usnadňuje práci při tréninkách, které nechceme hnát přes ORIS.

**Comment by fvacek** [comment]
jestli je v povinnem formatu csos nejprve prijmeni a pak jmeno, mam to skutecne prehozene

**Comment by OndrejSpanel** [comment]
Snažil jsem se to ověřit a našel jsem příklad, kde to opravdu je Příjmení Jméno:

http://www.ok-bor.cz/jestedska/upload/20150123153508.pdf

> VZOR
> 1-7 (m8) 9-18 (m19) 20-29 (m30) 31-55 (m56) 57 (m58) 59-
> JET6104 H21C 0000313888 Novák Jaromír A 80Kc

**Comment by arnost00** [comment]
Stačí se v ORISU podivat do "Přihláška z jednotného formátu ČSOS" kde máte jeho ukázku : 
`XXX9999 Kategorie  Číslo_čipu Příjmení_a_jméno......... L Poznámka`
