### ISSUE TITLE
Čipy po vyčtení při rychlosti 4800 baudů obsahují místo čísel kontrol nuly 

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#216]
Stala se mi teď divná věc: vyhodnocuji měřený trénink, který běželo pár desítek lidí. Při vyhodnocování výsledků vidím, že Start a Finish měli všichni oražený dobře, ale kontroly 31-35 jen tři lidé.

U těch pár závodníků, co bylo ražení v pořádku,  vypadalo `punches` v tabulce `cards` vypadala např. takto:

`[[31, 66413, 0], [32, 66437, 0], [33, 66480, 0], [34, 66576, 0], [35, 66685, 0]]`

Všichni ostatní měli v punches samé nuly, např:

`[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]`

Počet nul odpovídal tomu, kolik kontrol závodníci orazili, někdo jednu vynechal, pak měl třeba jen:

`[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]`

Mám teď v ruce čip, které byl takhle vyčtený s nulami, zkusil jsem si ho vyčíst ve SportIdent Config+ a vidím, že má kontroly oražené dobře. V QE se mi ale spolehlivě a opakovaně zase se vyčtou nuly.

Nastavení vyčítání mám:
- Bity za sekundu: 4800
- Datové bity: 8
- Stop bity: 1
- Parita: žádná

CRC check jsem nezakazoval, Ukaž surová data také zapnuté nebylo. Teď jsem ho Ukaž surová data povolil a v logu aplikace pak vidím následující:

<pre>
"DriverRawData: length: 8 [ e8 06 00 04 02 1f 35 86 ]"
sending command: "length: 7 [ 02 ef 01 08 ea 09 03 ]"
"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
"Čip: 2045318"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
empty message
"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"
empty message
empty message
empty message
empty message
"DriverRawData: length: 8 [ e7 06 00 04 00 1f 35 86 ]"
</pre>

**Comment by OndrejSpanel** [comment]
Zdá se, že to nějak souvisí s přenosovou rychlostí. Když jsem přepnul krabičku v SI Config+ na 38400 baudů a stejně změnil nastavení v programu, už mi to i tenhle čip vyčítá dobře, v logu vidím následující:

<pre>
"DriverRawData: length: 8 [ e8 06 00 04 02 1f 35 86 ]"
sending command: "length: 7 [ 02 ef 01 08 ea 09 03 ]"
"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"
"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"
"Čip: 2045318"
loading field info for table: "stages"
"DriverRawData: length: 8 [ e7 06 00 04 00 1f 35 86 ]"
</pre>

**Comment by fvacek** [comment]
Ja jsem mel jednou podobny problem, nakonec se ukazalo, ze v konfiguraci vycitaci krabicky je `Card 6 with 192 punches` zaskrtnuto a krabicky v lese to zaskrtnuto nemely. Zkus jeste overit tohle.

**Comment by OndrejSpanel** [comment]
Zkusil jsem, `Card 6 with 192 punches` nastavené nemám. Nejvíc mi připadá podivná ta reprodukovatelnost: přepnu na 4800, čip vyčtu s nulami. Přepnu na 38400, vyčtu dobře ... a můžu opakovat, kolikrát chci. Raw data se přitom zobrazují stejně. Jak může low-level nastavení, týkající se přenosu dat, ovlivňovat až zpracování dat, která jsou v obou případech stejná?

**Comment by fvacek** [comment]
Tohle je fakt divny, pokud jsou data identicka, nevidim duvod, aby byla jinak reprezentovana. S prenosovou rychlosti to souviset muze, ale je treba zjistit, co se tim zmeni. Ja ted bohuzel namam krabicku, takze to nemuzu vyzkouset.

**Comment by fvacek** [comment]
Taky se mi zda, ze krabicka nebyla nastavena na autosend. Mohl bys prosim vyzkouset, jak se to bude chovat v autosend modu?

**Comment by fvacek** [comment]
V prvnim pripade (pri nizsi rychlosti) dochazi k zpracovani dat z cipu driv, nez prijde druhy zaznam `[ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 ...` proto jsou casy 0, protoze ten blok prijde az po zpracovani dat. Je to zvlastni a muze to byt ma chyba. Potreboval bych jeste aplikacni log, tam by holo byt napsano, proc se QE rozhodl zpracovavat data. Hlavne by me zajimalo, jestli tam nekde nebude neco o time-outu. Tim by se to dalo vysvetlit, znamenalo by to, ze pri male prenosove rychlosti, QE neceka dostatecne dlouho na druhy blok, protoze si mysli, ze uz neprijde.

**Comment by OndrejSpanel** [comment]
To, co jsem poslal nahoře, je kopie z okna "Application log". Nic dalšího mezi tím v okně není. Mám přiložit ještě něco jiného? Dobré je, že to můžu naprosto spolehlivě reprodukovat. Přikládám ještě jednou:

Přikládám ještě jednou, navíc proti předtím vidím jen "loading field info for table:":

<pre>
"DriverRawData: length: 8 [ e8 06 00 04 02 1f 35 86 ]"
sending command: "length: 7 [ 02 ef 01 08 ea 09 03 ]"
"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
"Čip: 2045318"
loading field info for table: "stages"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
empty message
"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"
empty message
empty message
empty message
empty message
"DriverRawData: length: 8 [ e7 06 00 04 00 1f 35 86 ]"

<pre/>

**Comment by OndrejSpanel** [comment]
> Taky se mi zda, ze krabicka nebyla nastavena na autosend
Zkusil jsem to s autosend a dělá to taky. V záznamu pak jen chybí ty krátké zprávy délky 7 a 8, jinak to vypadá podobně:

<pre>
"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
"Čip: 2045318"
Invalid block no: 1
Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8
Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12
Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16
Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20
Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24
empty message
"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"
empty message
empty message
empty message
empty message
</pre>

**Comment by fvacek** [comment]
aha, takze to je jen sloupec massage?

**Comment by fvacek** [comment]
https://github.com/fvacek/quickbox/releases/tag/QE-1.0.10
udelal jsem verzi, ktera by mela byt ukecanejsi pri vycitani cipu, mohl bys to prosim zkusit s ni?

**Comment by OndrejSpanel** [comment]
Zkusil jsem, kopíruji všechny sloupce, jestli ti to tak vyhovuje víc.
<pre>
Info		"DriverInfo: <INFO> Available ports: COM3 \\\\.\\COM3"	2016-10-07T21:51:42	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> Connecting to \\COM3 - baudrate: 4800, data bits: 8, parity: 0, stop bits: 1"	2016-10-07T21:51:42	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> \\COM3 connected OK"	2016-10-07T21:51:42	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 28991 0x713f computed CRC: 28991 0x713f"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 0"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Error		Invalid block no: 1	2016-10-07T21:51:52	simessagedata.cpp	131	QByteArray SIMessageData::blockData(int) const	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Info		"Čip: 2045318"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		loading field info for table: "stages"	2016-10-07T21:51:52	catalog.cpp	108	virtual void qf::core::sql::FieldInfoList::load(const QSqlDatabase&, QString)	
Error		Invalid block no: 1	2016-10-07T21:51:52	simessagedata.cpp	131	QByteArray SIMessageData::blockData(int) const	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 12 offset: 8	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 16 offset: 12	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 20 offset: 16	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 24 offset: 20	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		Incorrect punch data: "length: 0 [  ]" correct length is: 28 offset: 24	2016-10-07T21:51:52	simessage.cpp	93	SIMessageCardReadOut::Punch::Punch(const QByteArray&, int, SIMessageCardReadOut::PunchRecordType)	
Error		empty message	2016-10-07T21:51:52	simessagedata.cpp	38	static SIMessageData::Command SIMessageData::command(const QByteArray&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 29072 0x7190 computed CRC: 29072 0x7190"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 0"	2016-10-07T21:51:52	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Error		empty message	2016-10-07T21:51:52	simessagedata.cpp	38	static SIMessageData::Command SIMessageData::command(const QByteArray&)	
Error		empty message	2016-10-07T21:51:52	simessagedata.cpp	38	static SIMessageData::Command SIMessageData::command(const QByteArray&)	
Error		empty message	2016-10-07T21:51:52	simessagedata.cpp	38	static SIMessageData::Command SIMessageData::command(const QByteArray&)	
Error		empty message	2016-10-07T21:51:52	simessagedata.cpp	38	static SIMessageData::Command SIMessageData::command(const QByteArray&)	
</pre>

**Comment by fvacek** [comment]
moh bych jeste poprosit o log, kdyz to funguje na vyssi prenosovy rychlosti

**Comment by OndrejSpanel** [comment]
Když to funguje, vypadá to takhle:

<pre>
Info		"DriverInfo: <INFO> Available ports: COM3 \\\\.\\COM3"	2016-10-07T22:03:13	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> Connecting to \\COM3 - baudrate: 38400, data bits: 8, parity: 0, stop bits: 1"	2016-10-07T22:03:13	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> \\COM3 connected OK"	2016-10-07T22:03:13	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 28991 0x713f computed CRC: 28991 0x713f"	2016-10-07T22:03:21	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"	2016-10-07T22:03:21	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 1"	2016-10-07T22:03:21	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 29072 0x7190 computed CRC: 29072 0x7190"	2016-10-07T22:03:22	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"	2016-10-07T22:03:22	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 0"	2016-10-07T22:03:22	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"Čip: 2045318"	2016-10-07T22:03:22	cardreaderwidget.cpp	361	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		loading field info for table: "stages"	2016-10-07T22:03:22	catalog.cpp	108	virtual void qf::core::sql::FieldInfoList::load(const QSqlDatabase&, QString)	
</pre>

**Comment by fvacek** [comment]
Uz jsem na to prisel, ale nemam krabicku, tak jsem to zkusil opravit naslepo. 

https://github.com/fvacek/quickbox/releases/tag/QE-1.1.0-devel

**Comment by OndrejSpanel** [comment]
Je to pokrok, data z čipu vidím vyčtená, ale zas to teď do logu to píše o nějakém timeoutu, a to bez ohledu na rychlost:

Rychlost 4800, autosend:
<pre>
Info		"DriverInfo: <INFO> Available ports: COM3 \\\\.\\COM3"	2016-10-08T12:03:38	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> Connecting to \\COM3 - baudrate: 4800, data bits: 8, parity: 0, stop bits: 1"	2016-10-08T12:03:38	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> \\COM3 connected OK"	2016-10-08T12:03:38	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 28991 0x713f computed CRC: 28991 0x713f"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 1"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 29072 0x7190 computed CRC: 29072 0x7190"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 0"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"Čip: 2045318"	2016-10-08T12:03:42	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		loading field info for table: "stages"	2016-10-08T12:03:42	catalog.cpp	108	virtual void qf::core::sql::FieldInfoList::load(const QSqlDatabase&, QString)	
Error		"DriverInfo: <ERR> RX data timeout"	2016-10-08T12:03:43	cardreaderwidget.cpp	406	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	</pre>

Rychlost 38400, autosend:

<pre>
Info		"DriverInfo: <INFO> Available ports: COM3 \\\\.\\COM3"	2016-10-08T12:07:17	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> Connecting to \\COM3 - baudrate: 38400, data bits: 8, parity: 0, stop bits: 1"	2016-10-08T12:07:17	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> \\COM3 connected OK"	2016-10-08T12:07:17	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 28991 0x713f computed CRC: 28991 0x713f"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 00 9b cf 12 7f ea ea ea ea 07 01 59 21 87 10 59 24 87 4f 5b 12 00 23 05 b6 02 1f 35 86 0c ff ea 55 32 30 34 35 33 31 38 3b 48 2e 53 2e 48 2e 20 53 70 6f 72 74 20 73 2e 72 3b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 1"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> CRC check - data CRC is: 29072 0x7190 computed CRC: 29072 0x7190"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverRawData: length: 133 [ ef 83 00 04 01 00 00 00 00 00 00 00 00 27 1f 59 aa 27 20 59 c2 27 21 59 e6 27 22 5a 60 27 23 5a d3 ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ee ]"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"DriverInfo: <INFO> packetReceived, packetToFinishCount: 0"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Info		"Čip: 2045318"	2016-10-08T12:07:22	cardreaderwidget.cpp	404	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
Error		"DriverInfo: <ERR> RX data timeout"	2016-10-08T12:07:23	cardreaderwidget.cpp	406	void CardReaderWidget::appendLog(qf::core::Log::Level, const QString&)	
</pre>

**Comment by fvacek** [comment]
zkus to prosim ted

https://github.com/fvacek/quickbox/releases/tag/QE-1.1.0-devel2

**Comment by OndrejSpanel** [comment]
Otestoval jsem 4800 i 38400, oboje autosend i bez něj, vše funguje dobře. Díky.

**Comment by fvacek** [comment]
Super, jsem rad a taky dekuju. Byla to nakonec docela blba chyba, ktera by se nahodne mohla projevit i na vyssi rychlosti tak, ze by se nekdy spatne vycetl cip. Hledala by se hodne blbe, protoze by ji nezlo na vysoke rychlosti reprodukovat. Takze jeste jednou dik :)
