### ISSUE TITLE
Licence ve výsledcích

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#219]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Při exportu výsledků do XML se v něm nezobrazují licence (tento sloupec je pak v ORISu celý prázdný.

**Comment by fvacek** [comment]
Vubec jsem neobjevil, jak licenci predat ve formatu IOF-XML, jestli to nekdo vi, at mi prosim poradi.

**Comment by fvacek** [comment]
btw: mohl bych te poprosit, jestli bys tyto 2 zavody zazipoval a dal jak oprilohu na Oris?

**Comment by frostidllo** [comment]
Určitě, chceš jen .qbe soubory že?

**Comment by frostidllo** [comment]
Nepodporovaný typ souborů. Povoleny jsou: jpg,gif,png,doc,rtf,xls,pdf,txt
[qbe soubory.zip](https://github.com/fvacek/quickbox/files/546528/qbe.soubory.zip)

**Comment by fvacek** [comment]
to je skoda, asi bych mel na to udelat wiki stranku

**Comment by frostidllo** [comment]
V ORISu existuje funkce: doplnit licence do výsledků.
A funguje správně!
Je hned na úvodní stránce závodu (nutná práva na editaci závodu)

**Comment by fvacek** [comment]
Ale v IOF-XML v.2 jsem tuto moznost nenasel.

**Comment by frostidllo** [comment]
Teď nevím jestli jsme si rozuměli, já měl na mysli toto:
![2016-10-30-2141 2](https://cloud.githubusercontent.com/assets/18715961/19839840/b0103d32-9ee9-11e6-8eb1-9a0954282feb.png)
Když na to kliknu, tak to chvilku něco dělá a pak se objeví licence u všech závodníků ve výsledcích (zřejmě to doplňuje z databáze podle registračky, protože těm, kteří nejsou registrováni v ČSOS to nedá licenci žádnou
