### ISSUE TITLE
Prohození 2 lidí ve startovce

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#220]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Při tvoření startovky jsem se snažil vyhovovat požadavkům na brzký/pozdní start a tak, vždy jsem to udělal tak, že jsem někomu například s časem 160 dal start 80 a pak tomu v 80 dal start 160, tímto způsobem jsem to nakonec vyladil, ale ocenil bych funkci prohození 2 lidí "jedním tlačítkem". Tento proces jsem dělal třeba 200krát v rámci startovek pro 2 dny.

**Comment by fvacek** [comment]
startovni casy se nechaji prohodit pretazenim policka se startovnim casem pomoci mysi, drag'n'drop

**Comment by frostidllo** [comment]
Tak toto je geniální, ušetří spoustu času a eliminuje případné chyby způsobené špatně přepsaným časem.

**Comment by frostidllo** [comment]
Nevím jak jsem to tehdy dělal, nebo se tato funkce ztratila, ale ve verzi 1.1.4. když chci dát drag'n'drop na startovním času v Úseky/Etapy, tak mi to začne označovat víc polí, takže mi to nefunguje.
A nemám zaškrtlé draw lock.

**Comment by mezkov** [comment]
Pro drag and drop prohazování závodníků musíš seřadit závodníky podle startovního času. Tj kliknout na hlavičku sloupce Start. 

-------- Původní zpráva --------
Od:frostidllo <notifications@github.com>
Odesláno:Thu, 25 May 2017 22:54:25 +0200
Komu:fvacek/quickbox <quickbox@noreply.github.com>
Kopie:Subscribed <subscribed@noreply.github.com>
Předmět:Re: [fvacek/quickbox] Prohození 2 lidí ve startovce (#220)
