### ISSUE TITLE
Vyčítání a tisk na dvou PC

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#221]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Měl jsem propojené 2 počítače, každý s vlastní tiskárnou Epson TM-T20 a Epson TM-T20II a každý s vyčítací krabičkou.
Na obou počátačích jsem měl nainstalované drivery na danou tiskárnu a pomocí tisku zkušební stránky jsem mohl ověřit, že tiskou. Když jsem však spojil počítače dohromady, tak z nepochopitelného důvodu začly tiskárny tisknout "křížem", tedy čip vyčtený v PC1 na vyčítací krabičce 1 měl vytisklé mezičasy na tiskárně 2, která byla zapojena v PC 2, který měl vyčítací krabičku 2 a naopak.
(takhle mi to fungovalo v pátek doma a v neděli při vyčítání, v sobotu mi všechno lezlo z tiskárny 1 a tak 5% mezičasů z tiskárny 2).

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/19628050/6ed1bc0e-9955-11e6-9acc-d489cbc8b096.png)

je na to zaskrtavatko

**Comment by frostidllo** [comment]
Tak to mě uplně minulo. Vim o tom, že tam tohle zaškrtávátko je, ale nepřišel jsem na to k čemu to je.
Dík, tohle určitě pro příště využiju :)
