### ISSUE TITLE
Tvorba startovek offsetem

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#222]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Tvorbu startovek v programu jsem využil až v neděli (v sobotu jsem si to rozkreslil na papír). Byl jsem až překvapen jak rychle se mi to přímo v programu podařilo, ale velmi dlouho mi trvalo na to jak pracovat s offsetem.
Možná by bylo dobré, kdyby se dal taky nastavit offset mezi jednotlivými kategoriemi a ne jen na začátku (zjednodušeně, že by se daly posouvat ty obdélníčky libovolně a ne jen celej řádek společně).
Toto jsem řešil tak, že jsem jednu z kategorií dal do prázdného řádku a pak mu dal offset třeba 50, nebo jak bylo potřeba (kvůli kombinaci společné 1. kontroly a jiného startovního intervalu).

**Comment by fvacek** [comment]
ofset mezi katekoriemi se resi pomoci poctu vakantu PO. Jinak nechapu, proc by bylo treba delat mezi kategoriemi mezery, akorat by t ozbytecne natahovalo startovni pole. Mozna mi neco unika.

**Comment by frostidllo** [comment]
je to jednoduchý, příklad z našich závodů:
H18 a D18 interval 2 minuty, D45L a H45K interval 3 minuty
H18 má stejnou trať jako D45L a H45K jako D18, všechny tratě mají stejnou první kontrolu
Začínají H18 a D18, po nich veteráni. Když však jde o víc jak 2 závodníky víc v jedný z dorosteneckejch kategorií, tak ten proklad bez roztáhnutí mezery nejde udělat.
Ale budiž, to se dá vyřešit tím vložením na prázdnej řádek (není to zas tak častý případ, tzn. tak jednou, dvakrát v závodě)

**Comment by fvacek** [comment]
oka, zavru to, protoze stejne by se na to dostalo az buh vi kdy, jestli vubec nekdy
