### ISSUE TITLE
Vymazání "starých" závodů

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#223]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Když jsem se na závod připravoval, tak jsem si stáhnul zkušební závod nocni_2015 a taky jsem si založil jeden testovací závod, ale po založení sobotního a nedělního závodu jsem tyto už nepotřeboval a hledal jsem jak je vymazat (celá jejich data). Na to jsem však nepřišel. Ne, že by to vadilo, ale představa, že za 3 roky tam budu mít 10 takových závodů co se budou jmenovat "sobota" a "nedele" jak jsem si je chytře pojmenoval není příliž příznivá.
Tahle funkce v programu možná je, třeba jsem to fakt jen nenašel

**Comment by fvacek** [comment]
Pokud je zavod v QBE souboru, staci vymazat tento soubor. Pokuj je v postgresql databazi, lze vymazat inkrimovane schema pomoci prikazu `DROP SCHEMA event_name CASCADE`

Vymazani zavodu je tak nebezpecne a tak malo pouzivane, ze jej neplanuji z bezpecnostnich duvodu implementovat.
