### ISSUE TITLE
Pri exportu do Orisu, priradit shodnym casum shodne poradi

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#224]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

V sobotu v D14 měly 2 závodnice stejný čas (2.-3. místo), program je označil jako 2. a 3. a ORIS to tak nechal, takže jsem musel výsledky stáhnout, ručně přepsat .xml soubor a pak je nahrát znova.
Není to zas tak vážné, ale třeba při sprintech jsou shodné časy celkem časté.

**Comment by fvacek** [comment]
dublicate #112

**Comment by viktorm2015** [comment]
Fany, toto je potřeba opravit. Dej to jako Bug.

**Comment by fvacek** [comment]
fixed

**Comment by Paukert** [comment]
Pořadí je ještě špatně vyhodnocováno u tisku diplomů.
