### ISSUE TITLE
Automatické doplňování vakantů do startovek

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#225]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

Tohle se přiznám, že jsem ještě zcela napochopil jak funguje (který vstup v záložce Kategorie má přednost, jestli Start a Last, nebo Vak. P, Vak. B a Vak. Po.
Každopádně když mám 2 kategorie se stejnou tratí (například D10 a H10) a jdou mi rovnou za sebou a někdo z D10 si vyžádá start do H10 vakanta na konci, tak když té holčičce ve startovce přepíšu čas až na konec H10, tak se ve startovce, po kategoriích se zaškrtnutým políčkem zobrazit vakanty, vloží třeba 30 vakantů do všech časů mezi tuto závodnici a tu co běží před ní (o hodinu, protože mezi nimi je celá kategorie H10).

Těžko říct, jestli se s tím dá něco dělat, ale možná by stálo za to mít vakanty nastavený nějak jako fiktivní závodníky, kteří by se neprojevovali ve výsledcích, ale měli by vlastní startovní čas.
A když bych chtěl někoho dát do toho startovního času, tak bych to udělal přes takový to velký tlačítko E1 v "Uprav závodníka" a vybral bych tam konkrétního vakanta do kterýho bych ho dal (takže bych si nemusel ten čas pamatovat) a ten vakant by zmizel, nebyl by označen jako závodník se stejným startovním časem (červeně).

Ale to bych toho asi chtěl fakt moc

**Comment by fvacek** [comment]
Vakant pred a po jsou jasny. Vakanti mezi jsou ted naimplementonany tak, ze program vynecha po kazdem n-tem zavodnikovi mezeru ve startovnim poli. Je to uz dlouhodoby problem a budu s tim muset neco udelat.

Posilat holcicku z D10 po H10 je corner case a asi i proti pravidlum, takze to resit asi nebudu.

Mam v planu udelat rezim losovani, kdy se pocet vakantu mezi vypocita podle poctu map, tak aby neslo prihlasit vic zavodniku, nez map.

Myslenka s fiktivnimi zavodniky je stara a o SW na poradani zavodu v OB docela oblibena. jeji problem spociva v tom, nejake problemy vyresi a nejake jine zase vygeneruje. Uvazuji nad tim, ze udelam pri losovani moznost **vloz fiktivni zavodniky na mista vakantu**, ale moc se mi do toho nechce, cejtim tam problemy a je to docela dost prace na to, abych to jen vyzkousel :)

Soucasna situace neni idealni (zejmena u jednodennich zavodu), ale neznam ani idealni reseni. Pokud se nejake objevi, rad to upravim.

**Comment by frostidllo** [comment]
Souhlasim, ze idealni reseni neni jednoduche ani vymyslet, natož naprogramovat a uznavam, ze tenhle pozadavek je dost prehnanej.
Tisknul jsem to proste bez vakantu (šlo o startovky na start)

**Comment by fvacek** [comment]
Lze tisknout startovky s vakanty, exportuji se i do Orisu
