### ISSUE TITLE
Tisk počtu závodníků v lese  ve vysledcich

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#226]
V tomto programu se nám povedlo úspěšně odpořádat dva oblastní žebříčky a narazil jsem při tom na několik problémů, či námětů.
http://oris.orientacnisporty.cz/Zavod?id=3410 , http://oris.orientacnisporty.cz/Zavod?id=3416

O návrhu tisknout pouze aktualizované výsledky už jsem se tady dočetl, pod to bych se podepsal. Já bych navrhnul ještě na konec stránky dopsat větičku: v lese je ještě xx závodníků. To by snad neměl být takový problém, protože informaci o počtu závodníků v lese program poskytuje v event statistics.
Byla by to příjemnost pro závodníky a pro vyhlašování průběžných výsledků rozhlasem.
A taky by se mě furt nechodili desítky ptát, jestli někdo ještě přiběhne nebo už ne :D

**Comment by fvacek** [comment]
Pouze aktualizovane vysledky lze tisknout z **Event statistics** Veticku bychom asi pridat mohli :)

**Comment by frostidllo** [comment]
Já jsem výsledky vždy tiskl z event statistics, ale zřejmě jsem tam něco zapomněl zakliknout, podívám se na to

**Comment by frostidllo** [comment]
Už možná vim, tam musís vždycky po tisku kliknout na tu černou šipku doleva s křížkem, aby se vymazaly nové výsledky a příště to vytiskne jen tam kde new results>0 ?

**Comment by fvacek** [comment]
to ne, po vytisteni (preview nestaci) vysledku, by se to melo vynulovat samo, zkousel jsem to ve verzi 1.1 a chodi mi to tak

**Comment by frostidllo** [comment]
Já jsem používal verzi 1.0.11 (kterou jsem vyhodnotil jako stable verze)
Výsledky jsem tiskl tímto postupem:
1) klik na tiskárničku v okně event statistics
2) vypnout filtr kategoií, nastavit zalomení na: stránka
3) export do acrobatu
4) tisk z pdf

Chybu vidím v tom kroku 3, možná kdybych to tisknul rovnou z preview, tak to bude fungovat... zkušenost pro příště
