### ISSUE TITLE
Označení závodníka, že neběžel 

### ISSUE THREAD

**Issue by Nechanicky** [fvacek/quickbox#228]
Je možné do okna Úsek/Etapa doplnit příznak neběžel (obdoba příznaku Neběží ze Závodníci). 
Jedná se o to, že pokud ze startu dostanu seznam závodníků, kteří nestartovali v dané etapě, tak není jiná možnost než složitě přes okno Závodníci závodníka odebrat. 
Přitom byl řádně přihlášen, při prezentaci se neodhlásil, ale nenastoupil k závodu. 
Pomáhá to v kontrole počtu závodníků v lese.

**Comment by fvacek** [comment]
Tento sloupac se zobrazi po zaskrtnuti checkboxu show off-race
![1](https://cloud.githubusercontent.com/assets/4949019/19839720/55160c92-9ee7-11e6-83f4-a5f3118f2beb.png)
