### ISSUE TITLE
Losování - určení priority závodníka (na začátek, na konec)

### ISSUE THREAD

**Issue by Nechanicky** [fvacek/quickbox#229]
Umožnit doplnit podmínku pro losování u konkrétních závodníků jejich priority pro umístění na začátek nebo konec startovacího pole. 
Použít například hodnotu v intervalu 0-1, která by vyjadřovala umístění v rámci startovního času kategorie. 
Zkusím dát stejný požadavek na ORIS, aby si závodníci pro oblastní závody tuto volbu mohli dávat přímo v ORISu a dalo se to načítat.

**Comment by paukert** [comment]
Duplicate of #149
