### ISSUE TITLE
Kontrola při označení Off-race, zda opravdu nedoběhl

### ISSUE THREAD

**Issue by viktorm2015** [fvacek/quickbox#231]
V okně Úsek/Etapa je super příznak neběžel. Navrhuji ale kontrolovat, zda vypínaný závodník nemá cílový čas. Pokud označím Off-race doběhlého závodníka zmizí z výsledků, i když má výsledek závodu v pořádku! Takže pokud startér neodškrtne záv. na startu, a ve stresu závodu chci rychle označit kdo nevyběhl, nevšimnu si toho. Stačí upozornit, zda jej chci opravdu vypnout..

**Comment by fvacek** [comment]
done
