### ISSUE TITLE
Informace vrátit čip na lístečku

### ISSUE THREAD

**Issue by Osin01** [fvacek/quickbox#240]
Na lístečku by se hodila informace o vrácení čipu. Museli jsme mít počítač trochu dál od vyčítání a obsluha tiskárny neměla podle čeho poznat, zda se jedná o půjčený čip (nebylo slyšet).

**Comment by fvacek** [comment]
proc jste si nedali tiskarnu k vycitaci kontrole, zavodnik tak vycte a jde?

**Comment by mezkov** [comment]
No právě, závodník vyčte a jde a půjčený čip si odnese domů.

Aktuálně jediný způsob, jak poznat při vyčítání půjčený čip, je ten děsivý zvuk z aplikace. OB2000 tiskne na lísteček velkým písmem "Vrátit čip".

**Comment by Osin01** [comment]
Počítač jsme měli v budově a vyčítání venku. Do budovy by nemohli chodit závodníci s hřeby. Zároveň byla přímo pod oknem předzahrádka, kde se nemohlo šlapat, tak to muselo být kousek vedle, jen asi 4 m od počítače, ale přesto už pípání nebylo slyšet. Uznávám, že to nebylo nejlepší řešení, ale líp jsme to v danou chvíli nevymysleli. Museli jsme pak pořvávat od počítače vrátit čip na pořadatele, který vydával mezičasy, vybíral čipy, dával bombony a posílal problémové k počítači.
