### ISSUE TITLE
Start v minusovém čase

### ISSUE THREAD

**Issue by Osin01** [fvacek/quickbox#241]
Start v mínusovém čase se ve startovce zobrazil místo -2  -120, vyhodnocení času bylo v pořádku.
Při zadávání záporného startovního času je potřeba zadat celý text -2.00, po zadání -2 se nastaví 0.02.

**Comment by fvacek** [comment]
zaporne startovni casy nebudou podporovany z mnoha implementacnich duvodu, nema cenu kvuli nekomu, kdo bezi trenink, revidovat a testovat celou aplikci.

**Comment by Osin01** [comment]
Požadavek na záporný čas, se mi zdá naprosto legitimní a není důvod, aby někdo  nemohl běžet v minusovém čase, když jsou splněny ostatní předpoklady. Není to proti pravidlům a na našich malých závodech to používáme často.

**Comment by fvacek** [comment]
jak jsem psal pred tim, jedna se o mnozstvi prace, ktere bych radeji venoval nejake issue s vyssi prioritou. Legitimnost pozadavku nezpochybnuji, jenom nejsou lidi. Pokud by to chtel udelat nekdo jiny, budu jedine rad.

**Comment by Paukert** [comment]
Stejný požadavek je #135 a #141.

Pro větší přehlednost by to tady stačilo asi jednou :-)

**Comment by frantisekpasek** [comment]
#141 není to samé. Já považoval záporný startovní čas za chybu.
