### ISSUE TITLE
Jde nějak přestěhovat výsledek načtení čipu do jiné etapy?

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#243]
Stalo se mi to jen při tréninku, takže žádná tragédie, vyexportoval jsem to z SQL a zpracuji si to vedle, ale možná by se to mohlo někomu stát i při závodech?

Při vyčítání druhé etapy tréninku jsem neměl správně nastavenou aktuální etapu, takže se mi vše vyčítalo dál do první etapy. V oknech Vyčítání SI čipů i Mezičasy jsem výsledky viděl zdvojené, po prohlédnutí pomocí "Zobrazit čip" jsem byl schopen si prohlédnout i předchozí výsledky, ale nepřišel jsem na to, jak bych mohl těm novým změnit etapu.

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/24745400/f861799e-1af8-11e7-8d7d-e8411edc1c7d.png)

jde to na urovni SQL

**Comment by fvacek** [comment]
zmenit stageId na 2 a potom znovu nacist casy z karet, doporucuji to zkouset na nejake zaloze

![3](https://cloud.githubusercontent.com/assets/4949019/24745690/e6080230-1af9-11e7-97af-a1129e4111fc.png)

**Comment by OndrejSpanel** [comment]
Díky, to vypadá pochopitelně. Mám se nějak starat o `stageId` v tabulce `punches`, nebo stačí jen `cards`? (Co vlastně jsou punches?

**Comment by fvacek** [comment]
cards staci, punches se pregeneruji pri nacteni karet

**Comment by fvacek** [comment]
punches jsou rozebrany mezicasy z karty, ulozeny do tabulky, aby se daly pocitat ztraty na viteze v kategorii
