### ISSUE TITLE
export startovek do csv

### ISSUE THREAD

**Issue by viktorm2015** [fvacek/quickbox#244]
Připravit export startovek do csv pro interní potřebu větších oddílů, např. při zajištění dopravy. Nynější html export není jednoduše zpracovatelný pro Excel či jinou tabulku. Ideálně mít možnost určit sloupce k exportu, ale netrvám si na tom.

**Comment by fvacek** [comment]
Kazda tabulka muze byt exportovana do CSV

![1](https://cloud.githubusercontent.com/assets/4949019/25016677/45f6e99a-2081-11e7-85ac-15dac76b8ad1.png)

![2](https://cloud.githubusercontent.com/assets/4949019/25016689/4f8091dc-2081-11e7-8a19-16e088d333ca.png)

**Comment by fvacek** [comment]
Zaviram tuto issue, protoze existuje celkem pohodlne reseni
