### ISSUE TITLE
Při vyčtení čipu byl výsledek přiřazen k závodníkovi, který neběžel

### ISSUE THREAD

**Issue by Paukert** [fvacek/quickbox#245]
Pokud nastavím u nějakého závodníka, že neběží (off-race), tak můžu jeho číslo čipu zadat jinému závodníkovi. 

Při vyčtení čipu se však výsledek přiřadil k závodníkovi, který měl nastaveno, že neběží. K druhému závodníkovi, který s daným čipem běžel, se nepřiřadilo nic.

**Comment by fvacek** [comment]
muzes prosim prilozit qbe soubor a napsat, ktery zavodnik to byl?

**Comment by fvacek** [comment]
fixed in bc93bc56622d46aeb9a2b9cdd9cf0a0333d2e778

**Comment by Paukert** [comment]
Asi to už nepotřebuješ, ale tady je kdyžtak odkaz na stažení qbe souboru:
[http://kobusti.cz/static/usti2017/usti2017_final_20170422.qbe](url)

Jednalo se o závodníka:
Kaška Jan --> neběžel
Kunt Stanislav --> běžel s čipem 2053567

Pro opravu stačilo smazat číslo čipu u Kaška Jan a vyčíst daný čip znovu.

Bohužel teď nejsem schopný ověřit opravu, nemám k dispozici vyčítací krabičku.
