### ISSUE TITLE
Možnost penalizace za chybějící kontrolu místo DISK

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#248]
Někdy bychom rádi v nesoutěžních kategoriích (typicky HD10L, HDR) místo DISK za chybějící kontroly dávali penalizaci. Vím, že to není úplně triviální, ale hádám, že nejsme sami, kdo by to uvítal.

**Comment by OndrejSpanel** [comment]
Vidím, že už to je evidované jako #144

**Comment by fvacek** [comment]
implemented in 2.3.4
