### ISSUE TITLE
Startovní listina po oddílech exportovaná do HTML je prázdná

### ISSUE THREAD

**Issue by OndrejSpanel** [fvacek/quickbox#249]
Nechal jsem exportovat startovní listiny do HTML po kategoriích a po oddílech, Export po kategoriích proběhl v pořádku, ale po oddílech ne, bylo tam jen opakované záhlaví, žádný obsah.

V HTML to vypadalo takto:

```
<h2>
		<a name="club_undefined"></a>
	</h2>
	<h3></h3>
	<table>
		<tr>
			<th>Start</th>
			<th>Kategorie</th>
			<th>Jméno</th>
			<th>Registrace</th>
			<th>SI</th>
		</tr>
	</table>

```

Totéž se mi stalo při pokus o tisk po klubech. Když jsem jsem QE ukončil a znovu spustil, tisk po klubech fungoval správně, ale jakmile jsem se pokusil o export do HTML, opět byl prázdný a zase nefungoval ani tisk po klubech.

Problém vidím ve verzi 1.1.4. Loni, když jsme pořádali závody na cca beta 0.1.12, to fungovalo dobře.

**Comment by Paukert** [comment]
Export startovních listin do HTML po klubech se mi podařil, pokud jsem to udělal hned po zapnutí programu. Pokud jsem po zapnutí programu nejdříve provedl export startovek po kategoriích do HTML, tak potom nastane situace, která je popsaná výše.

**Comment by OndrejSpanel** [comment]
Díky za tip, to mi ušetřilo hledání nouzového řešení (už jsem se chystal dělat CSS pro HTML exportované z tiskového výstupu).

**Comment by fvacek** [comment]
fixed
