### ISSUE TITLE
Nelze zvolit sport pro import registrace z ORISu

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#256]
Pokud pořádám závody v MTBO a chci si stáhnout registraci, program stále tahá registraci z URL:
http://oris.orientacnisporty.cz/API/?format=json&method=getRegistration&sport=1&year=%1

Pro stažení registrace MTBO by stačilo jiné URL:
http://oris.orientacnisporty.cz/API/?format=json&method=getRegistration&sport=3&year=%1

Bohužel toto nelze v programu nakonfigurovat.

Na druhou stranu klika je, že URL je napsané natvrdo v binárním souboru QuickEvent\qml\quickevent\Orisplugin.dll a když jsem v hexadecimálním editoru upravil příslušný znak z 1 na 3, DLL je stále čitelné a program funguje a pracuje zase pokaždé s MTBO.

Takže, pokročilý uživatel může stáhnout i registraci MTBO, ale bylo by super to trošičku ulehčit,
buď to přidat někam do konfigurace závodu, nebo alespoň přesunout URL pro stahování
registrace z ORIS z binárního DLL někam do textového konfiguračního souboru ...

Vojta

**Comment by fvacek** [comment]
done
