### ISSUE TITLE
Při importu závodu z ORISu se neimportuje čas startu 00

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#257]
Při importu závodu z ORISu se neimportuje čas startu 00.

Příklad:
URL závodu, ze kterého se stahuje API:
https://oris.orientacnisporty.cz/API/?format=xml&method=getEvent&id=3935
Odpověď obsahuje informaci:
`<StartTime>09:00</StartTime>`

V QE se při importu vytvořil závod s etapou s časem startu 10:00 (asi výchozí hodnota).

Bohužel mě nenapadlo toto kontrolovat, a při exportu startovky do ORISu
se exportují absolutní startovní časy, které kvůli tomu byly o hodinu posunuté
a bohužel mě na to upozornili až závodníci. Kontroloval jsem startovku v HTML,
která ale má relativní časy.

Prosím o opravu, snad by to mohlo ušetřit podobnou chybu dalším pořadatelům.
Díky, Vojta

**Comment by fvacek** [comment]
fixed
