### ISSUE TITLE
Doladění terminologie a úprava kontextových menu ("mezičasy" vs "surová data čipu")

### ISSUE THREAD

**Issue by Czelda** [fvacek/quickbox#258]
QE je už ve stávající verzi (1.1.12-beta) skvělý a naprosto použitelný program, se kterým musela být spousta práce. Jak už to ale "opravdoví programátoři" :-) mívají, na něco "tak podružného", jako je doladění uživatelského rozhraní, jednak nemají čas a za druhé "nevadí, když se to samý jmenuje pokaždý trochu jinak - vždyť to je přece každému jasné".  :-)
Tudíž jsem některé vlastnosti programu pochopil až dlouho po pořádaných závodech po diskusi s autorem [zde](https://github.com/fvacek/quickbox/issues/255). Jedná se zejména o rozdíl mezi "mezičasy" ("receipt") a "surovými daty čipu" ("card raw data"), což jsem se následně pokusil vysvětlit [zde](https://github.com/fvacek/quickbox/wiki/%C4%8Cipy%2C-mezi%C4%8Dasy-a-trocha-z%C3%A1kladn%C3%AD-filozofie-programu).

Proto **doporučuju v prvním kroku upravit text kontextových menu** (podle toho, co už teď opravdu dělají) **následovně:**

### Kontextové menu v tabulce ve Vyčítání SI čipů (při přepnutí na CZ)
_Ukázat mezičasy_ -  OK, ponechat
_Vytisknout mezičasy_ - OK, ponechat
_Zobrazit čip_ - Změnit na _Ukázat surová data čipu_
_Print card_ - Změnit na _Vytisknout surová data čipu_
_Přiřadit čip závodníkovi_ - OK, ponechat

### Kontextové menu v tabulce v Mezičasy (při přepnutí na CZ)
_Vytisknout vybrané čipy_ - Změnit na _Vytisknout mezičasy pro vybrané řádky_

### Kontextové menu v tabulce v Úseky/Etapy (při přepnutí na CZ)
_Zobrazit záznamy z čipu_ - Změnit na _Ukázat mezičasy_
_Nahrát časy z čipu ve vybraných řádcích_ - Pokud fakt funguje i pro více řádků najednou, tak OK, ponechat, jinak smazat _ve vybraných řádcích_
_Vytisknout čip_ - Změnit na _Vytisknout mezičasy_
_Shift start times in selected rows_ - Dolokalizovat na _Posunout čas startu ve vybraných řádcích_ 

---

### Kontextové menu v tabulce v Card reader (při přepnutí na EN)
_Show receipt_ -  OK, ponechat
_Print receipt_ - OK, ponechat
_Show card_ - Změnit na _Show card raw data_
_Print card_ - Změnit na _Print card raw data_
_Assign card to runner_ - OK, ponechat

### Kontextové menu v tabulce v Receipts (při přepnutí na EN)
_Print selected cards_ - Změnit na _Print receipts for selected rows_ 

### Kontextové menu v tabulce v Runs (při přepnutí na EN)
_Show receipt_ - OK, ponechat
_Load times from card in selected rows_ - Pokud fakt funguje i pro více řádků najednou, tak OK, ponechat, jinak smazat _in selected rows_
_Print card_ - Změnit na _Print receipt_
_Shift start times in selected rows_ - OK, ponechat

**Comment by fvacek** [comment]
Ja navrhuji dusledne pouzivat:
* Card == Čip
* Receipt == Mezičasy

surová data se mi nelíbí, to by mohl taky byt HEX dump obsahu čipu:))

**Comment by Czelda** [comment]
2fvacek:
Ano, a proto to GUI vypadá, jak to vypadá :-0 :-) - Položka _Print card_ v kontextovém menu Card reader tiskne surová data čipu, zatímco položka _Print card_ v kontextovém menu Runs tiskne mezičasy ...

Právě proto, že řada lidí netuší, že lze vytisknout jen surová data čipu, a právě proto, že se to (oproti tisku mezičasů) dělá spíše vyjímečně, tak by dle mého názoru tam **mělo být explicitně uvedeno, že jde o surová data, ne o** (standardní) **mezičasy.**

**Comment by fvacek** [comment]
ale to nejsou surova data, tak nejdeme lepsi nazev, surova dat na cipu vypadaji jinak
```
00000000 50 52 41 47 │ 4D 41 20 66 │ 6F 72 65 69 │ 67 6E 5F 6B │ 65 79 73 3D │ 4F 46 46 3B │ 0A 42 45 47 │ 49 4E 20 54 │ 52 41 4E 53 │ 41 43 54 49 │ 4F 4E 3B 0A │ 43 52 45 41 │ 54 45 20 54 │ 41 42 4C 45
00000038 20 69 6E 66 │ 6F 20 28 20 │ 49 44 20 49 │ 4E 54 45 47 │ 45 52 20 50 │ 52 49 4D 41 │ 52 59 20 4B │ 45 59 20 41 │ 55 54 4F 49 │ 4E 43 52 45 │ 4D 45 4E 54 │ 2C 20 78 6D │ 6C 64 6F 74 │ 61 7A 6E 69
00000070 6B 20 54 45 │ 58 54 20 29 │ 3B 0A 49 4E │ 53 45 52 54 │ 20 49 4E 54 │ 4F 20 22 69 │ 6E 66 6F 22 │ 20 56 41 4C │ 55 45 53 28 │ 31 2C 27 3C │ 71 75 65 73 │ 74 69 6F 6E │ 61 72 79 20 │ 76 65 72 73
000000A8 69 6F 6E 3D │ 22 30 2E 33 │ 22 3E 0A 3C │ 71 75 65 73 │ 74 69 6F 6E │ 20 65 78 70 │ 6F 72 74 6E │ 61 6D 65 3D │ 22 5A 31 30 │ 52 65 67 69 │ 6F 6E 22 20 │ 78 6D 6C 69 │ 64 3D 22 32 │ 22 20 6E 75
000000E0 6D 62 65 72 │ 3D 22 31 22 │ 3E 0A 3C 63 │ 61 70 74 69 │ 6F 6E 3E 30 │ 2E 52 65 67 │ 69 6F 6E 3C │ 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 63 │ 68 65 63 6B │ 20 78 6D 6C │ 69 64 3D 22 │ 34 22 3E 0A
00000118 3C 63 61 70 │ 74 69 6F 6E │ 3E 45 78 70 │ 6F 6E 6F 76 │ 61 6E C3 A1 │ 20 6F 62 6C │ 61 73 74 3C │ 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 2F │ 63 68 65 63 │ 6B 3E 0A 3C │ 63 68 65 63 │ 6B 20 78 6D
00000150 6C 69 64 3D │ 22 36 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 56 C3 │ BD 63 68 6F │ 64 6F C4 8D │ 65 73 6B C3 │ BD 3C 2F 63 │ 61 70 74 69 │ 6F 6E 3E 0A │ 3C 2F 63 68 │ 65 63 6B 3E │ 0A 3C 2F 71
00000188 75 65 73 74 │ 69 6F 6E 3E │ 0A 3C 71 75 │ 65 73 74 69 │ 6F 6E 20 65 │ 78 70 6F 72 │ 74 6E 61 6D │ 65 3D 22 5A │ 32 31 50 6F │ 68 6C 61 76 │ 69 22 20 78 │ 6D 6C 69 64 │ 3D 22 38 22 │ 20 6E 75 6D
000001C0 62 65 72 3D │ 22 32 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 31 2E │ 20 50 6F 68 │ 6C 61 76 C3 │ AD 3C 2F 63 │ 61 70 74 69 │ 6F 6E 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 31 30
000001F8 22 3E 0A 3C │ 63 61 70 74 │ 69 6F 6E 3E │ 6D 75 C5 BE │ 3C 2F 63 61 │ 70 74 69 6F │ 6E 3E 0A 3C │ 2F 63 68 65 │ 63 6B 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 31 32 │ 22 3E 0A 3C
00000230 63 61 70 74 │ 69 6F 6E 3E │ C5 BE 65 6E │ 61 3C 2F 63 │ 61 70 74 69 │ 6F 6E 3E 0A │ 3C 2F 63 68 │ 65 63 6B 3E │ 0A 3C 2F 71 │ 75 65 73 74 │ 69 6F 6E 3E │ 0A 3C 71 75 │ 65 73 74 69 │ 6F 6E 20 65
00000268 78 70 6F 72 │ 74 6E 61 6D │ 65 3D 22 5A │ 33 32 56 65 │ 6B 22 20 78 │ 6D 6C 69 64 │ 3D 22 31 34 │ 22 20 6E 75 │ 6D 62 65 72 │ 3D 22 33 22 │ 3E 0A 3C 63 │ 61 70 74 69 │ 6F 6E 3E 32 │ 2E 20 56 C4
000002A0 9B 6B 3C 2F │ 63 61 70 74 │ 69 6F 6E 3E │ 0A 3C 6E 75 │ 6D 62 65 72 │ 20 78 6D 6C │ 69 64 3D 22 │ 31 36 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 70 6F │ C4 8D 65 74 │ 20 6C 65 74 │ 3C 2F 63 61
000002D8 70 74 69 6F │ 6E 3E 0A 3C │ 72 61 6E 67 │ 65 20 64 65 │ 63 69 6D 61 │ 6C 73 3D 22 │ 30 22 20 6D │ 69 6E 3D 22 │ 31 35 22 20 │ 6D 61 78 3D │ 22 36 39 22 │ 2F 3E 0A 3C │ 6F 72 64 69 │ 6E 61 6C 69
00000310 7A 61 74 69 │ 6F 6E 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 35 33 │ 38 22 20 6E │ 75 6D 70 6F │ 69 6E 74 3D │ 22 31 39 2E │ 30 30 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 64 6F
00000348 20 31 39 20 │ 6C 65 74 3C │ 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 2F │ 63 68 65 63 │ 6B 3E 0A 3C │ 63 68 65 63 │ 6B 20 78 6D │ 6C 69 64 3D │ 22 35 34 30 │ 22 20 6E 75 │ 6D 70 6F 69 │ 6E 74 3D 22
00000380 33 34 2E 30 │ 30 22 3E 0A │ 3C 63 61 70 │ 74 69 6F 6E │ 3E 64 6F 20 │ 33 34 20 6C │ 65 74 3C 2F │ 63 61 70 74 │ 69 6F 6E 3E │ 0A 3C 2F 63 │ 68 65 63 6B │ 3E 0A 3C 63 │ 68 65 63 6B │ 20 78 6D 6C
000003B8 69 64 3D 22 │ 35 34 32 22 │ 20 6E 75 6D │ 70 6F 69 6E │ 74 3D 22 34 │ 39 2E 30 30 │ 22 3E 0A 3C │ 63 61 70 74 │ 69 6F 6E 3E │ 64 6F 20 34 │ 39 20 6C 65 │ 74 3C 2F 63 │ 61 70 74 69 │ 6F 6E 3E 0A
000003F0 3C 2F 63 68 │ 65 63 6B 3E │ 0A 3C 63 68 │ 65 63 6B 20 │ 78 6D 6C 69 │ 64 3D 22 35 │ 34 34 22 20 │ 6E 75 6D 70 │ 6F 69 6E 74 │ 3D 22 36 34 │ 2E 30 30 22 │ 3E 0A 3C 63 │ 61 70 74 69 │ 6F 6E 3E 64
00000428 6F 20 36 34 │ 20 6C 65 74 │ 3C 2F 63 61 │ 70 74 69 6F │ 6E 3E 0A 3C │ 2F 63 68 65 │ 63 6B 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 35 34 │ 36 22 20 6E │ 75 6D 70 6F │ 69 6E 74 3D
00000460 22 36 39 2E │ 30 30 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 64 6F │ 20 36 39 20 │ 6C 65 74 3C │ 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 2F │ 63 68 65 63 │ 6B 3E 0A 3C │ 63 61 70 74 │ 69 6F 6E 3E
00000498 76 C4 9B 6B │ 3C 2F 63 61 │ 70 74 69 6F │ 6E 3E 0A 3C │ 2F 6F 72 64 │ 69 6E 61 6C │ 69 7A 61 74 │ 69 6F 6E 3E │ 0A 3C 2F 6E │ 75 6D 62 65 │ 72 3E 0A 3C │ 2F 71 75 65 │ 73 74 69 6F │ 6E 3E 0A 3C
000004D0 71 75 65 73 │ 74 69 6F 6E │ 20 65 78 70 │ 6F 72 74 6E │ 61 6D 65 3D │ 22 5A 34 33 │ 4E 65 6A 76 │ 79 73 73 69 │ 44 6F 73 61 │ 7A 65 6E 65 │ 56 7A 64 65 │ 6C 61 6E 69 │ 22 20 78 6D │ 6C 69 64 3D
00000508 22 31 38 22 │ 20 6E 75 6D │ 62 65 72 3D │ 22 34 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 33 2E │ 20 4E 65 6A │ 76 79 C5 A1 │ C5 A1 C3 AD │ 20 64 6F 73 │ 61 C5 BE 65 │ 6E C3 A9 20 │ 76 7A 64 C4
00000540 9B 6C C3 A1 │ 6E C3 AD 3C │ 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 63 │ 68 65 63 6B │ 20 78 6D 6C │ 69 64 3D 22 │ 32 30 22 3E │ 0A 3C 63 61 │ 70 74 69 6F │ 6E 3E 7A C3 │ A1 6B 6C 61 │ 64 6E C3 AD
00000578 3C 2F 63 61 │ 70 74 69 6F │ 6E 3E 0A 3C │ 2F 63 68 65 │ 63 6B 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 32 32 │ 22 3E 0A 3C │ 63 61 70 74 │ 69 6F 6E 3E │ 76 79 75 C4 │ 8D 65 6E 3C
000005B0 2F 63 61 70 │ 74 69 6F 6E │ 3E 0A 3C 2F │ 63 68 65 63 │ 6B 3E 0A 3C │ 63 68 65 63 │ 6B 20 78 6D │ 6C 69 64 3D │ 22 32 34 22 │ 3E 0A 3C 63 │ 61 70 74 69 │ 6F 6E 3E 6D │ 61 74 75 72 │ 69 74 61 2C
000005E8 20 42 63 2E │ 3C 2F 63 61 │ 70 74 69 6F │ 6E 3E 0A 3C │ 2F 63 68 65 │ 63 6B 3E 0A │ 3C 63 68 65 │ 63 6B 20 78 │ 6D 6C 69 64 │ 3D 22 32 36 │ 22 3E 0A 3C │ 63 61 70 74 │ 69 6F 6E 3E │ 76 79 73 6F
```

**Comment by Czelda** [comment]
Ustupuji hrubé síle !!! :-0 :-)
Tak co třeba vynechat slovo "surová", když Ti data nepřipadají dost surová ? Pak by to bylo "data čipu" a "card data". Ale stejně by se mně víc líbilo, kdyby z toho bylo jasné, že se jedná o nezpracovaná data čipu, tak jak je závodník orazil, bez dalšího zpracování (teda když nepočítám převedení do lidsky čitelné formy ...), prostě aby bylo na první pohled jasné, že je to něco jiného než mezičasy. Ale zrovna slova "nezpracovaná" a "unprocessed" jsou zatraceně dlouhá ...

**Comment by fvacek** [comment]
s vynechanim slova surova jsem v pohode, to se mi libi

**Comment by paukert** [comment]
Zmíněné překlady do češtiny upraveny, překládat lze případně na adrese: https://hosted.weblate.org/projects/quickbox/

**Comment by paukert** [comment]
Done in #406
