### ISSUE TITLE
Pri vytvareni nove SQlite database spadne

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#26]
Pri vytvareni nove SQlite database program spadne. Muze za to nejspise chovani kdy se nikde nezkontroluje ze db neobsahuje zadne tabulky a v EventConfig::load() se rovnou zacne poustet query na tabulku 'config'.
Je zajimave ze pred commity ze 7.5.2015 se tabulky vytvorili, a ted ne. Pusobi to jako nejaky side effect jednoho z commitu - resp. jsem primou navaznost v diffech neobjevil.

Toto je stav vzhledem ke commitu b09d06edd3ca433a7234339a7095507a0245b404

**Comment by arnost00** [comment]
Tyka se to situace kdy pri startu applikace se zobrazi dialog "Data storage setup" a pri vybrani single event se do EventID vyplni jmeno souboru ktery neexistuje.
V pripade ze existuje spravne se spusti. V pripade ze je prazdne tak to natvrdo zavola dialog "Select event".

Dale je zajimave ze pokud v dialogu "Data storage setup" se do EventID da i koncovka ".qbe" tak program rovnou pri otevirani prida dalsi na konec (cili dojde ke zdvojeni).

**Comment by fvacek** [comment]
Quickevent vzdy pridava .qbe koncovku za jmeno eventu, zakazu asi tecku ve jmene eventu. To, ze program spadne pokud nekdu zada neexistujici event je chyba a je to potreba nejak fixnout.

**Comment by fvacek** [comment]
fixed in d21b465c8df2b7c01313912cd77f6ab7bb97f0b3
