### ISSUE TITLE
chyba zalomeni pro dlouha jmena v tisku startovek pro startéry

### ISSUE THREAD

**Issue by rjelin** [fvacek/quickbox#264]
Při tisku startovek pro startéry, došlo vlivem dlouhého jména závodnice k rozhození tisku této sestavy, což zkomplikovalo práci startérům. Navrhuji délku jména hlídat a ev. zkrátit aby sestava zůstala čitelná.
[report.pdf](https://github.com/fvacek/quickbox/files/1405143/report.pdf)

**Comment by rjelin** [comment]
`
[report.pdf](https://github.com/fvacek/quickbox/files/1405142/report.pdf)
`

**Comment by fvacek** [comment]
K teto chybe dochazi pouze kdyz je nastavena vyska radku ve startovce natvrdo na 10 mm.

**Comment by fvacek** [comment]
Navic k chybe dochazi puze, kdyz je dlouhe jmeno prvni hned za headerem s udajem o startovnim case, 1 radek st. casu + 2 radky dlouheho jmena se do 10 mm nevejdou a program zalomi sloupec.

**Comment by fvacek** [comment]
fixed in 0b24d2872deb07802dbfc4968762ced892e4e26f
