### ISSUE TITLE
zasekávání pri tisku mezičasů

### ISSUE THREAD

**Issue by fialot** [fvacek/quickbox#265]
Díky za tento program. Zatím nejlepší, co jsem používal na pořádání závodů.

Jediná věc, co se nám stávala, bylo to, že při vyčítání zhruba u každého 20. závodníka program začal chvíli šrotovat a nereagoval (na 5-30 vteřin) a až pak vytiskl mezičasy a zase běžel svižně jako předtím. Čím více už bylo v databázi vyčtených čipů, tím déle program nereagoval. Používali jsme QE 1.1.12, postgreSQL 9.6 a Windows 10 x64.

**Comment by arnost00** [comment]
Jak si mel nastaven tisk listecku ? graficky/textove ?
Mam dojem ze u grafickeho zpusobu se tohle objevovalo (ale uz si moc nepamatuju duvod).

**Comment by mezkov** [comment]
Zasekávání se projevovalo u grafického tisku na pomalých počítačích, ale ten zásek byl tak půl sekundy. Tohle bude asi něco jiného.

**Comment by fialot** [comment]
měl jsem to nastaveno graficky. Záseky při malém počtu načtených závodníků byly malé (ze začátku to mohly být sekundy), ale postupně se prodlužovaly. Tady je uložený závod:
[lv2017_results.zip](https://github.com/fvacek/quickbox/files/1407935/lv2017_results.zip)

**Comment by fvacek** [comment]
necelych 300 zavodniku nemuze byt zadny problem, jedine, ze bych nejakou chybu pri vylepsovani napsal ja. Na HSH jsme v textovem rezimu tiskli bez problemu listecky pro 1000 zavodniku. Byl bych rad, kdyby se na to prislo, ale obavam se, ze to nebude snadne zreprodukovat.

@fialot mohl by sis zkusit vytisknout par listecku z prilozeneho QBE souboru, jestli bude stale dochazet k zasekavani. Pokud tu chybu nedokazeme zreprodukovat, bude velice obtizne ji opravit.
