### ISSUE TITLE
Použití jednoho čipu vícekrát v jednom závodě

### ISSUE THREAD

**Issue by Osin01** [fvacek/quickbox#268]
Omlouvám se za další corner case, Tenhle corner case už jsem ale použil mnohokrát.
Program by mohl umožňovat použít jeden čip vícekrát. A to tak, že by se při vyčtení jen vybral konkrétní závodník (třeba z vyskočené nabídky).  Nebo by to mohl řešit program sám na základě startovního času, ale to nejde při startu na krabičku.
Aktuálně to jde řešit tak, že se musí ručně změnit po prvním vyčtení číslo čipu SIID v tabulce CARDS (v SQL tool) a poté přiřadit konkrétnímu závodníkovi. V tomto případě je výhodné u závodníků, kteří poběží se stejným čipem nezadávat číslo Actual SI a tím pádem je to donutí to řešit při vyčítání.

**Comment by fvacek** [comment]
Program umoznuje pouziti 1 cipu klidne n-krat. Jedine omezeni je, ze pokud chceme cip priradit jinemu zavodnikovi, je jej treba nejprve odebrat tomu stavajicimu, protoze existuje unikatni klic pro SI v ramci jednoho zavodu

**Comment by Osin01** [comment]
Takže, jestli to chápu správně, čip zadám v části Runs v sloupci Actual SI prvnímu závodníkovi, u druhého nechám prázdně,  po prvním vyčtení čipu se  pak Actual SI vynuluje u prvního závodníka a přiřadí se druhému a při druhém vyčtení se to správně přiřadí druhému závodníkovi?
Jinak není potřeba nic jiného upravovat?

**Comment by fvacek** [comment]
presne tak

**Comment by Osin01** [comment]
Pokud u prvního závodníka zůstane 0, tak by se mu při budoucí aplikaci funkce rekonstrukce výsledků nepřepočítá čas. Ale jinak je to jednoduché a rychlé.

**Comment by fvacek** [comment]
bude to fungovat i v tomto pripade, protoze vyctene cipy jsou parovany se zavodniky pres runId ne pres SI. Teoreticky lze kartu priradit zavodnikovi s jakymkoliv SI.
