### ISSUE TITLE
Export startovek a vysledku v HTML

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#271]

**Comment by frantisekpasek** [comment]
Bylo by pěkný mít něco, pomocí čeho by se výsledky/startovky daly zobrazovat přes lokální wifi na shromaždišti anebo online na webu. Díky!

**Comment by fvacek** [comment]
myslis zobrazovat nebo, ktere by si zavodnici mohli prohlizet na svych mobilech? Pokud zobrazovat, je to quickshow.

**Comment by frantisekpasek** [comment]
Myslím tím dvě věci:
- zobrazování výsledků/startovek na mobilech a jiných zařízeních závodníků přímo na shromaždišti (přes lokální wifi)
- zobrazování výsledků/startovek na mobilech a jiných zařízeních závodníků online na internetu

**Comment by fvacek** [comment]
Nevim, jestli na to uz neni issue, muj plan je takovy, ze bych napsal HTTP server, ktery by to delal. Ten by se dal pouzit pro lokalni WIFI. Krome toho by v pravidelnem casovem intervalu ukladal vysledky, startovky do souboru, takze pokud by je nekdo pravidelne kopiroval nekam na internet, muhly by byt aktualni i na internetu.

**Comment by fvacek** [comment]
dokonce jsem takovy server uz jednou napsal pro predchozi verzi programu na poradani zavodu, takze by to nemuselo dat ani tolik prace, jenom je to potreba projit a prepsat z mysql na postgres a trochu jinou strukturu tabulek. 

[sihttpd.py.zip](https://github.com/fvacek/quickbox/files/1800843/sihttpd.py.zip)

**Comment by frantisekpasek** [comment]
Tuším, že to asi nemá prioritu (a času je málo), ale nedalo by se v tom trošku :-) pokročit?
Věřím, že by to dnešní generace fungující ve světě internetu a mobilů ocenila. Dík!

**Comment by fvacek** [comment]
je to hotovy, soucasti instalace je quickhttpd.exe, ktery to uz dela. Samozrejme bez dokumentace atd, ale to uz opravdu nestiham :)

```
[~/proj/_build/quickbox/bin]$ ./quickhttpd -h                                                                                                                                                                                                    
quickhttpd [OPTIONS]

OPTIONS:

--abort-on-exception
        Abort application on exception
--html-dir 'string' [default(./html)]
        directory where HTML pages will be stored
--refresh-time number [default(1000)]
        refresh time in msec
--config 'string'
        Application config name, it is loaded from {config}[.conf] if file exists in {config-path}, deault value is {app-name}.conf
--config-dir 'string'
        Directory where application config fiels are searched, default value: {app-dir-path}.
--classes-like 'string'
        SQL LIKE expression to filter classes to show, for ex. --classes-like "H%"
--classes-not-like 'string'
        SQL LIKE expression to filter classes not to show, for ex. --not-classes-like "HDR"
-e, --event 'string'
-n, --stage number
        If not set, the current stage number is loaded from database.
-h, --help
        Print help
--http-port number [default(8888)]
-b, --sql-database 'string' [default(quickevent)]
--sql-sql-driver 'string' [default(QPSQL)]
-s, --sql-host 'string' [default(localhost)]
-p, --sql-password 'string'
--sql-port number [default(5432)]
-u, --sql-user 'string' [default(quickevent)]
-lfn, --log-long-file-names
         log long file names
-d,--debug [PATTERN[:TRESHOLD][,PATTERN[:TRESHOLD]]]
         set file log pattern and treshold
                 PATTERN: any substring of source module, for example 'mymod' prints debug info from every source file with name containing 'mymod', mymodule.cpp, tomymod.cpp, ...
                 TRESHOLD: any of DEB, INFO, WARN, ERR, [D,I,W,E] can be used as well, default level is INFO
         when pattern is not set, set treshold for all files
         when treshold is not set, set treshold D (Debug) for all files containing pattern
         when nothing is not set, set treshold D (Debug) for all files
         Examples:
                -d              set treshold D (Debug) for all files
                -d :W           set treshold W (Warning) for all files
                -d foo          set treshold D for all files containing 'foo'
                -d bar:W        set treshold W (Warning) for all files containing 'bar'
```

**Comment by fvacek** [comment]
Ten server krome toho, ze umi HTTP requesty, vyrabi i staticke stranky, ktere neustale dopluje, takze kdyz je budete kazdych 5 minut kopirovat ne nejaky svuj HTTP server, muzete mit vysledky on-line na internetu.
