### ISSUE TITLE
Štafety

### ISSUE THREAD

**Issue by mezkov** [fvacek/quickbox#273]
Tak nám Lešťa přichystal nádherný dáreček na příští rok: pořádáme oblastní štafety. Jupí! :-)

Jak to vidíte s podporou štafet v QE? Jak těžké by bylo to doprogramovat?

**Comment by fvacek** [comment]
v lednu urcite ne, kdy by se mely poradat ty oblastni? Udelat stafety mam jeste urcite v planu, ovsem cas je nas nepritel :)

**Comment by fvacek** [comment]
tezke to moc neni, pokud to bude dobre rozmyslene. V podstate neni moc velky rozdil mezi stafetami a vice dennimi zavody, maximalne pribyde jedna tabulka, maximalne 2. Rad bych se stafetmi sfouknul i druzstva. Spis jde o to, jak udelat sikovne UI, aby se to dobre pouzivalo, bylo to jednoduche a prehledne.

**Comment by mezkov** [comment]
Mělo by se to pořádat 2. června. 

Rozdíl mezi štafetami a družstvy je pouze v počtu závodníků, ne?

Já bohužel nikdy štafety nepořádal, takže nemám moc představu o tom, co a jak je potřeba dělat. Zejména nevím, jak se definují jednotlivé varianty farstovaných tratí a jak se pak přiřazují závodníkům.

**Comment by fvacek** [comment]
V podstate to neni tak, ze kazda kategorie ma vlastni trat, ale ma ji kazdy zavodnik podle kategorie a farsty, ale to taky neni problem. Ja stafety poradal jen asi 3x, takze taky se necitim byt ten, kdo by to mel vymejslet.

**Comment by fvacek** [comment]
stafety by mely byt 2.6. 2018
