### ISSUE TITLE
Rename Card Lent to Card Rent

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#274]

**Comment by paukert** [comment]
Klidně to změním, jen prosím o potvrzení:
- v záložce Competitor:
1. v menu – Lent cards -> Cards to rent (to samé i u nadpisu daného formuláře)
- v záložce Runs:
1. sloupec – LR (Card rent requested) -> RR (Card rent requested)
2. sloupec – LT (Card in lent table) -> RT (Card in rent table)
3. v menu – Competitors with card rent -> Competitors with rented cards (stejná změna v daném reportu)
- v záložce Card reader:
1. sloupec – L (Card lent) -> RC (Rented card)

V záložce Card reader je ještě sloupec R (Card returned), snad by se to nepletlo..

**Comment by fvacek** [comment]
jj, to je presne ono, dik :)

**Comment by paukert** [comment]
úprava je připravená v #398 :)
