### ISSUE TITLE
Automatický export IOF-XML s výsledky

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#275]
Zdravím, chtěl bych navrhnout novou funkcionalitu programu, která by umožňovala automatický export IOF-XML 3 s výsledky závodu do daného adresáře např. každou minutu. Bylo by tak umožněno nahrávat průběžné výsledky na server http://liveresultat.orientering.se. LiveResults Client, pak automaticky složku vybírá a nahrává mezičasy na server.
Ideálně pokud by byl interval a výstupní adresář modifikovatelný.

Mnohokrát díky za tento software.

**Comment by fvacek** [comment]
v zasade je to docela jednoduche, pokud by se to nechalo naimplementovat v ramci aplikacniho threadu, jenze to by pak mohlo zpomalovat napr. vycitani, takze jsou 2 moznosti:
1. pro exportovani spustit specialni QE
1. napsat export tak, aby bezel v separatnim threadu

**Comment by fvacek** [comment]
related (possibly can implement) #271

**Comment by arnost00** [comment]
Hlasuji pro použití separatního (worker) threadu.
Obecně, pravidelně spouštěné exporty / importy by neměli blokovat UI (tj aplikačni / hlavní thread).

**Comment by martinkrivda** [comment]
jasně ... jedná se o neklíčovou funkcionalitu, která, když spadne, tak se nic podstatného nestane .. blokovat vyčítání a zpomalovalo ho atd. by nemělo. Nicméně netuším, jak je to časově náročné na provedení, tomuto už nerozumím.

**Comment by fvacek** [comment]
7f4bbd7c87eee41d2ebbdf989df263545c10bc9d

**Comment by fvacek** [comment]
Export nebezi v separatnim threadu.
