### ISSUE TITLE
IOF XML - winsplits

### ISSUE THREAD

**Issue by janzhanal** [fvacek/quickbox#276]
Ahoj, 
vcera jsem se pokousel pouzit [`wisplits`](http://obasen.orientering.se/winsplits/online/en/default.asp) pro zobrazeni mezicasu.
Vyexportoval jsem IOF XML vysledky, po importu mi winsplits nezobrazilo kontroly, ktere nemeli DISK zavodnici, predpokladam, ze winsplits specifikace IOF XML (2.3) je jina nez v quickeventu, slo by tuto pridat?
Data zavodu: [bzl-jelen.qbe.zip](https://github.com/fvacek/quickbox/files/1546970/bzl-jelen.qbe.zip)

Diky!

**Comment by fvacek** [comment]
I QE exportuje vysledky v IOF XML (2.3), takze je mozne, ze je v implementaci nekde chyba, ale vzhledem k tomu, ze se jedna o DISK zavodniky, asi nebude nikdo, kdo by ji hledal.

**Comment by janzhanal** [comment]
Jenze on pak winsplits nezobrazi ty kontroly vsem, nejen tem diskum...

**Comment by fvacek** [comment]
Ted tomu nerozumim, jake kontroly tedy winsplits zobrazi? Zadne, nektere?

**Comment by janzhanal** [comment]
Zobrazi jen kotroly, ktere maji orazene vsichni zavodnici, tzn v mezicasech pak chybi kontroly, ktere nekdo neorazil... Ale netvrdim, ze neni chyba na jejich strane

**Comment by fvacek** [comment]
jednoduche reseni na strane QE by bylo vyjmout z exportu DISQ zavodniky

**Comment by janzhanal** [comment]
ano, to taky rucne delam, jeste zkusim jednou projit, jeslit v specifikaci neni nejaka finta, jakoze musi by mp nebo tak neco, aby je to bralo...

**Comment by fvacek** [comment]
tak jo, v 1.1.18 je volba export->winsplits, kde se to vyexportuje do iofxml 2.3 bez dikvalifikovanych

**Comment by janzhanal** [comment]
Dekuji!

**Comment by fvacek** [comment]
muzes to prosim vyzkouset?

**Comment by janzhanal** [comment]
vypada to OK, Diky!
