### ISSUE TITLE
Oris import

### ISSUE THREAD

**Issue by janzhanal** [fvacek/quickbox#280]
Pri vsech pokusech o import z orisu dostanu: 
JSON document parse error: illegal value
![1](https://user-images.githubusercontent.com/34436593/36117086-b83b9ec2-1038-11e8-9b30-992f7ae998fb.png)
nastala zmena v orisu?

muzu naimportovat lonske registrace jinak, nez v kodu rucne opravim ktery rok chci? (ty letosni jsou zatim nepouzitelne)

**Comment by fvacek** [comment]
co jsi importoval?

**Comment by fvacek** [comment]
je to tim, ze Oris presel z http ma https a QE parsuje redirect stranku, opravim to co nejdriv asi zitra

``

**Comment by janzhanal** [comment]
Diky!
Jinak dneska bzl bez problemu!

**Comment by frantisekpasek** [comment]
- ve verzi 1.1.16 otevřu tento závod: https://github.com/fvacek/quickbox/files/1151110/hsh2017.qbe.zip
- v Závodníci > vlož nový řádek > zkusím někoho dohlásit > zdá se, že načítání registrací funguje

![obrazek](https://user-images.githubusercontent.com/18633350/37245528-b02636aa-2499-11e8-987e-11f61af11abd.png)


- pak přes Soubor > Import > Oris > Registrace zkusím naimportovat registrace
- pak znovu zkusím vložit nový řádek přes Závodníci > vlož nový řádek > zkusím někoho dohlásit > zdá se mi, že načítání registrací přestane fungovat

![obrazek](https://user-images.githubusercontent.com/18633350/37245536-ccf4abd6-2499-11e8-89f7-7c33f85afe17.png)

**Comment by fvacek** [comment]
a pomuze restart aplikace?

**Comment by frantisekpasek** [comment]
Ne.

**Comment by fvacek** [comment]
a co je v tabulce registrations? ( ctrl+shift+R )

**Comment by frantisekpasek** [comment]
Před importem z Orisu.

![obrazek](https://user-images.githubusercontent.com/18633350/37258343-d10970f2-2576-11e8-8f1f-4bbdb043c506.png)


Po importu z Orisu.

![obrazek](https://user-images.githubusercontent.com/18633350/37258348-dda6832c-2576-11e8-83a1-4b26d2cea500.png)

**Comment by fvacek** [comment]
tak to je jina chyba, to vypada, ze nefunguje import z Orisu, ale mne funguje, ted jsem to zkousel. Muzes to vyzkouset v 1.1.17?

**Comment by frantisekpasek** [comment]
Ano, asi nefunguje import z Orisu.
Můžu, když verzi 1.1.17 zveřejníš.

**Comment by fvacek** [comment]
uz je tam, je to ale 1.1.18 :)

**Comment by frantisekpasek** [comment]
V 1.1.18 se to chová stejně, nic se nezměnilo.

**Comment by fvacek** [comment]
pise to neco do logu? mne to registrace stahuje, potreboval bych to nejak zreprodukovat

**Comment by frantisekpasek** [comment]
Po spuštění importu z Orisu se zapíše řádek 100:

![obrazek](https://user-images.githubusercontent.com/18633350/37367035-8b36e2f2-2702-11e8-8aa6-79d38969f19d.png)

![obrazek](https://user-images.githubusercontent.com/18633350/37367046-95c64a78-2702-11e8-8d9b-3f4effea0ad4.png)

Tohle by tě možná taky mohlo zajímat:

![obrazek](https://user-images.githubusercontent.com/18633350/37367227-1a18bcfc-2703-11e8-9edd-3f3369335e48.png)

![obrazek](https://user-images.githubusercontent.com/18633350/37367243-2109bce6-2703-11e8-856f-c391f406356d.png)

**Comment by janzhanal** [comment]
kdyz das editovat zavod, mas vybrany sport OB?

**Comment by frantisekpasek** [comment]
Ne.

**Comment by frantisekpasek** [comment]
Po vybrání sportu už to funguje.

**Comment by fvacek** [comment]
tak ti jsem rad, ze se to vysvetlilo. mozna by to chtelo nejakej message box

**Comment by fvacek** [comment]
sport je automaticky OB, pokud neni zadan
