### ISSUE TITLE
Konzistentnost názvů

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#282]
Prosím o sjednocení názvů polí, např. L = Card Lent a P = Čip půjčen, D = Disqualified a DISK = Diskvalifikace. Asi je to jen otázka lokalizace, viz #281.

**Comment by paukert** [comment]
Všude by to nyní mělo být sjednoceno (#398)

RR (Card rent requested) = VP (Vyžádáno půjčení čipu)
RT (Card in rent table) = ČT (Čip z tabulky čipů k zapůjčení)
DISQ (Disqualified) = DISK (Diskvalifikace)
