### ISSUE TITLE
Nazornejsi zobrazovani vakantů (zelena oddelovaci cara?)

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#283]
V Úsecích/Etapách se vakanti zobrazují pomocí zelené barvy. Přijde mi to nevhodné a matoucí. 
Nechceme je zobrazovat spíše jako prázdné řádky, aby uživatel hned viděl, kde je vakant? Takhle u toho uživatel musí přemýšlet, kde ten vakant skutečně je (Nahoře nad zelenou? Dole pod zelenou? V místě zelené?).

**Comment by fvacek** [comment]
je to pred zelenou

**Comment by fvacek** [comment]
mozna bych mohl treba kreslit zelenou caru na miste chybejiciho radku s vakantem. Vakanti nejsou ulozeny v DB, takze vymyslet pro ne prazdny radek je problem, staci ze to delam, kdyz generuji sestavy

**Comment by frantisekpasek** [comment]
Čára přes celý řádek bude lepší řešení, ale i tak si myslím, že to nebude ono. :-) Pořád si člověk musí pamatovat, kde se ten vakant nachází ... Kdyby tam byl prázdný řádek (s časem), tak to ví hned.

**Comment by fvacek** [comment]
ja to chapu, ale musel bych kvuli tomu davat do databaze prazdne radky a to fakt nechci

**Comment by fvacek** [comment]
done
