### ISSUE TITLE
Zobrazování výsledků na monitorech

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#284]
Rádi bysme zkusili výsledky místo klasického tisku a vyvěšování zobrazovat přímo na monitorech. 
Výsledky by byly aktuální a nemuselo by se nic tisknout a vyvěšovat. Je to teď již řešitelné? 
Ideální by bylo, aby na každém monitoru byly jiné výsledky (např. 1. monitor D10, D12, D14, 2. monitor H10, H12, H14, ...).

**Comment by fvacek** [comment]
soucasti instalace je i program quickshow, ktery presne toto dela https://github.com/fvacek/quickbox/wiki/QuickShow-Users-Guide

**Comment by frantisekpasek** [comment]
OK, díky.

**Comment by frantisekpasek** [comment]
Podařilo se mi QuickShow rozchodit, mám k tomu dotaz.
Jak docílím toho, že na každém monitoru uvidím něco jiného?
Na 1. monitoru např. jenom kategorie D10, D12, D14, na 2. monitoru jenom kategorie H10, H12, H14, ...
V helpu jsem na žádné takové nastavení nenarazil.

**Comment by fvacek** [comment]
to v tuto chvili nejde, mohl bych pridelat option do prikazove radky, ale nevim, nevim

**Comment by fvacek** [comment]
done

**Comment by frantisekpasek** [comment]
Ve verzi 1.1.16 jsem si zkusil nastavit classes-like a classes-not-like. 
Přijde mi, že to nefunguje. Anebo jsem nepochopil jak to nastavit.

**Comment by fvacek** [comment]
a co jsi tam napsal?

**Comment by frantisekpasek** [comment]
"application": {
		"refreshTime": 400,
		"columnCount": 5,
		"classesLike": "h%"
	}

**Comment by fvacek** [comment]
zkus "event": {"classesLike": "H%"}

**Comment by frantisekpasek** [comment]
Díky, to je lepší! :-)
Jak dosáhnu toho, abych na každém monitoru viděl něco jiného?

**Comment by frantisekpasek** [comment]
@fvacek, prosím, jak dosáhnu toho, abych na každém monitoru viděl něco jiného?
Pustím to na více počítačích a na každém nastavím jiný quickshow.conf?

**Comment by fvacek** [comment]
presne tak

**Comment by frantisekpasek** [comment]
- bylo by, prosím, @fvacek možné do výsledků zobrazovaných přes QuickShow za čas přidat sloupec se ztrátou na vítěze? Totéž by bylo fajn i u normálních výsledků.
- registračka je někdy ořízlá, ač prostoru na její zobrazení je dostatek

![obrazek](https://user-images.githubusercontent.com/18633350/41559604-c62f36f0-7344-11e8-93df-c2fd58b6bcea.png)

**Comment by fvacek** [comment]
> bylo by, prosím, @fvacek možné do výsledků zobrazovaných přes QuickShow za čas přidat sloupec se ztrátou na vítěze? Totéž by bylo fajn i u normálních výsledků.

mozne by to bylo, ale je to boj s mistem, obvykle promitame vysledky ve dvou sloupcich, takze by to asi chtelo pridat volitelne do konfigurace

**Comment by fvacek** [comment]
ve ver 2.0.0 by to uz melo byt sirsi
