### ISSUE TITLE
Import klubů a registrací z Orisu

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#292]
Nedaly by se importy:

- Soubor > Import > Oris > Kluby 
- Soubor > Import > Oris > Registrace 

spojit do jednoho? 
Laicky mi přijde lepší kliknout jen jednou než dvakrát. Ale třeba to má nějaký důvod.

**Comment by fvacek** [comment]
nema to zadny duvod, slo by to

**Comment by paukert** [comment]
Tyto importy jsou spojené od verze 2.3.0
