### ISSUE TITLE
Potvrzení startovního času pomocí Cancel

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#295]
Startovní čas se při editaci závodníka naprosto nepochopitelně potvrzuje pomocí Cancel.
Lepší by bylo tam dát třeba OK.

![obrazek](https://user-images.githubusercontent.com/18633350/36564325-26c9aa14-181d-11e8-9b36-beac7d7b3d0b.png)

**Comment by fvacek** [comment]
fixed in 1.1.16
