### ISSUE TITLE
Importovat ID

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#296]
Čekal bych, že do pole Importovat ID bude při vytváření závodu možné vložit ID závodu a závod tak při kliknutí na OK naimportovat z Orisu. Buď to špatně chápu anebo to nefunguje (pole je nepřístupné).

![obrazek](https://user-images.githubusercontent.com/18633350/36564751-a27ac782-181e-11e8-8eab-3ae415ba4b9d.png)

**Comment by fvacek** [comment]
id zavodu se vyplni automaticky vybranim zavodu v listboxu predchoziho dialogu

**Comment by frantisekpasek** [comment]
Pole je nepřístupné, když zakládám nový závod přes Soubor > Závod > Vytvořit závod.

**Comment by fvacek** [comment]
to je pravda :)

**Comment by fvacek** [comment]
zkousel jsem to a mne pole ID zavodu editovat jde, takze tobe take

**Comment by fvacek** [comment]
nejde editovat Import ID, ale to je v poradku

**Comment by frantisekpasek** [comment]
Při zakládání závodu přes Soubor > Závod > Vytvořit závod pole Importovat ID nedává žadný smysl.

**Comment by fvacek** [comment]
proto je read-only
