### ISSUE TITLE
Formátování startovní listiny po klubech

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#297]
Nový sloupec v sestavě zřejmě rozhodil formátování.

![obrazek](https://user-images.githubusercontent.com/18633350/36644833-403df2ee-1a60-11e8-8472-f6d44901aed6.png)

**Comment by fvacek** [comment]
to opravim snadno :)

**Comment by fvacek** [comment]
fixed in 1.1.17
