### ISSUE TITLE
Formátování sestavy Print results for classes with new runners

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#299]
Sestava spuštěná přes Statistiky závodu > Print results for classes with new runners má podivné formátování.

![obrazek](https://user-images.githubusercontent.com/18633350/36645157-fd4c5052-1a64-11e8-942b-6f4a98aa0cd4.png)

Obdobně se chová sestava spuštěná přes Statistiky závodu > Vytisknout výsledky vybraných kategorií.

**Comment by fvacek** [comment]
fixed in 1.1.17
