### ISSUE TITLE
Cannot edit new rows in Classes window

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#30]
Can add new row, but unable to edit it. Same for Codes side window (with exception of column with caption of "0", the check box can be checked ). Cannot save added rows (or at least the floppy disk icon with hint "post row edits" doesn't prevent row from disappearing after reload icon is used)

Btw. floppy disk icon? Bit old school, isn't it?

**Comment by fvacek** [comment]
Only OCad import is currently implemented. It is rather a feature request than a bug.

**Comment by fvacek** [comment]
closing as #81 duplicate
