### ISSUE TITLE
Vytisknout vybrané čipy

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#300]
Spuštění Vytisknout vybrané čipy v Mezičasech způsobí pád aplikace.

![obrazek](https://user-images.githubusercontent.com/18633350/36645271-549a7ed2-1a66-11e8-9141-d67defd20926.png)

**Comment by fvacek** [comment]
to se mi nedari zreprodukovat, 

* jake je nastaveni tiskarny? 
* Pada to pri jakemkoliv nastaveni tiskarny (text i graficka) nebo jenom pro nekterou/

**Comment by Paukert** [comment]
Něco podobného se nám několikrát stalo při pořádání ODM.

Myslím, že je to způsobené špatně nastavenou tiskárnou (viz screen, kde je sice nastavená grafická tiskárna, ale není tam její název; nebo alespoň mně se tam vždy název zobrazuje). Program potom padal i na jiných místech, jak psal Viktor v #277

**Comment by fvacek** [comment]
Mozna to bude neco Windows specific, coz je pro me skutecne problem zreprodukovat, protoze Windows nepouzivam. Ani Viktorovy pady se mi nepodarilo zreprodukovat. Mozna kluci z Brna @arnost00 maji z padanim pri tisku mezicasu nejake zkusenosti.

**Comment by arnost00** [comment]
Prosim @frantisekpasek o screenshot dialogu nastaveni tiskarny. Kouknu i na #277

**Comment by fvacek** [comment]
podle #277 jsem to uz zkousel nekolikrat, nespadlo mi to ani jednou

**Comment by frantisekpasek** [comment]
Fyzicky nemám připojenou žádnou tiskárnu.
S tímhle nastavením to padá.

![obrazek](https://user-images.githubusercontent.com/18633350/36695198-e569a0ca-1b40-11e8-9a33-d8561b409aed.png)

**Comment by frantisekpasek** [comment]
S tímhle to taky padá.

![obrazek](https://user-images.githubusercontent.com/18633350/36695408-88e76494-1b41-11e8-82b5-944d0f243415.png)

**Comment by frantisekpasek** [comment]
Při tomhle nastavení to nepadá.

![obrazek](https://user-images.githubusercontent.com/18633350/36695949-0c52c570-1b43-11e8-8b3b-3be2a3203e66.png)

**Comment by Paukert** [comment]
Já si myslím, že nám pomohlo opětovné vybrání (klidně i stejné) tiskárny.

Když koukám na ty tvé SS, tak to nastavení u prvního a třetího je stejné.

**Comment by frantisekpasek** [comment]
Tohle je taky OK.

![obrazek](https://user-images.githubusercontent.com/18633350/36696062-7691394e-1b43-11e8-88d9-755b1a9e749f.png)

**Comment by frantisekpasek** [comment]
První případ oproti třetímu neměl vybranou žádnou tiskárnu.
Žádnou tiskárnu neměl ani druhý případ.

**Comment by fvacek** [comment]
mozna je problem v tom, ze je vybrana graficka tiskarna a zobrazeno nastaveni pro textovou, spravne tam ma byt toto:

![image](https://user-images.githubusercontent.com/4949019/36949710-6345190c-1fec-11e8-8c03-8e4b6b7b2f98.png)

**Comment by paukert** [comment]
Opraveno, viz issue #305
