### ISSUE TITLE
Nastavení šablony diplomu

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#302]
V podkladovém obrázku (který je přes celou stránku) mám volná pole kam bych rád dostal data (pořadí, jméno, atd.). Jde to? Jak?

**Comment by fvacek** [comment]
nejjednodussi je vzit si nejaky diplom ( https://github.com/fvacek/quickbox/tree/master/quickevent/app/plugins/qml/Runs/qml/reports/awards ) a poeditovat ho.

**Comment by frantisekpasek** [comment]
Jo, to jsem dělal. 
Otázka zní, zdali je možné do diplomu, který je přes celou stránku diplomu dostat výsledky tak, abych mohl tisknout zároveň obrázek diplomu a výsledky. Dostal jsem se do stavu, že v jedné části jsem měl obrázek diplomu a v druhé výsledky a nebyl schopnej to udělat tak, aby se výsledky dostaly do obrázku.

**Comment by fvacek** [comment]
ano, to jde to, muzes to snadno vyzkouset napr na results_stage_awards-apple.qml
```qml
						Frame {
							width: "%"
							halign: Frame.AlignHCenter
							hinset: 20
							layout: Frame.LayoutStacked
							Image {
								height: 70
								dataSource: "./images/apple.svg"
							}
							Para {
								width: "%"
								halign: Frame.AlignHCenter
								text: "Libovolny text"
							}
						}
```
`layout: Frame.LayoutStacked` zpusobi to, ze se vsechny objekty v nadrazenem Frame budou tisknout pres sebe

**Comment by fvacek** [comment]
v 1.1.18 je sablona Apple-2, kde je text pres obrazek 1c8c0aabbe86a71d623eaabffaa3a8c7d15f7f57

**Comment by fvacek** [comment]
to jsem rad :)

**Comment by frantisekpasek** [comment]
- jak změním font?
- pole se do diplomu berou z DB?
- jaký "jazyk" používá šablona?

Klidně si to nějak dohledám, když mě trošku postrčíš, díky.

**Comment by fvacek** [comment]
* jazyk jsem, bohuzel, vymyslel ja :(
* pole se berou z DB, ale ne primo, pro kazdy report se udela SELECT dat, ktre jsou z neho potom pristupna
* font se da predepsat atributem `family`, podivej se napr do `results_stage_award.qml`

```
		fonts: [
			Font {
				id: fontDiplom
				name: "diplom"
				family: "Times"
				hint: Font.HintSerif
				pointSize: myStyle.textStyleDefault.font.pointSize * 10
			},
			Font {
				id: fontNormal
				pointSize: myStyle.textStyleDefault.font.pointSize * 3
			}
		]
```

**Comment by frantisekpasek** [comment]
Tisk diplomů jsme teď použili pro školní závod a musím opakovat svou pochvalu. Je to obrovská pomoc! Stresy před vyhlašováním jsou pryč. :-) Díky moc! @fvacek
