### ISSUE TITLE
QuickBox on Android?

### ISSUE THREAD

**Issue by jmacura** [fvacek/quickbox#306]
Ahoj,

je někde dostupná verze pro Android? Jestli-ne, mohl bych dostat nějakou radu, jak udělat build ze zdrojového kódu do .apk?

Díky

**Comment by fvacek** [comment]
teoreticky to na Android prelozit lze (protoze QT), prakticky se obavam, ze pokud nebudes mit stylus, UI bude nepouzitelne.

**Comment by jmacura** [comment]
To problém není. Mám Galaxy Tab A.
Našel jsem nějaký [návod](https://www.codeproject.com/Tips/1191289/How-to-Make-a-Cplusplus-Qt-Android-Project-with-CM), jak z Qt kódu udělat apk, ale instalovat 40 GB Qt se mi zrovna nechce... QuickBox momentálně využívá Qt verze 5.9.1? Abych to aspoň nemusel dělat víckrát...

**Comment by dg0yt** [comment]
> prakticky se obavam, ze pokud nebudes mit stylus, UI bude nepouzitelne.

A bluetooth mouse and keyboard may help.

**Comment by fvacek** [comment]
> To problém není. Mám Galaxy Tab A.
Našel jsem nějaký návod, jak z Qt kódu udělat apk, ale instalovat 40 GB Qt se mi zrovna nechce... QuickBox momentálně využívá Qt verze 5.9.1? Abych to aspoň nemusel dělat víckrát...

nene, Qt je ve skutecnosti < 500 MB, pokud si nainstalujes jen to, co potrebujes. Ja bych se spis ridil podle pokynu na http://doc.qt.io/qt-5/androidgs.html

**Comment by dg0yt** [comment]
Regarding size: The OpenOrienteering Mapper for Android armeabi-v7a APK is app. 18 MB. The unpacked contents are app. 29 MB binaries, 10 MB translations (21 languages), and 8 MB other data. 

However, there are other issues on Android:
- Qt recommends a fairly old NDK, with the deprecated/now removed gcc 4.9. This toolchain comes with incomplete support for C++11. (However, Qt provides alternatives in many cases.)
- The application life cycle is different from desktop. Apps may get killed while in background.
- Handling data, especially files, is very different from the desktop.

Dealing with these particularities requires significant effort, likely to take away resources from other developments.

**Comment by jmacura** [comment]
@dg0yt: I was actually mentioning the size of Qt for Windows, which is huge (sorry for not being English-speaking from the beginning).
Thanks for your notes about the known issues. Right now, I don't have time to dig through the process, but I would like to give it a try.
I wish I had enough knowledge about software development so I can provide such effort, but sadly I don't.

**Comment by dg0yt** [comment]
@jmacura No need to worry about language. I'm only an observer here. Trosku rozumim. But trying to write would be too much fun ;-) 
Even for Windows, it is only the Qt development kit with many tools, libraries, documentation and debugging support which is so huge. In an application package ("release"), there will be only a few (dozens of) mega bytes. Actually as we can see in the Windows downloads here.

**Comment by xkenia** [comment]
Any progress on this?

**Comment by fvacek** [comment]
nop

**Comment by jmacura** [comment]
nope. For some time I felt like trying it, but... nothing really pushed me to do so. I was generally interested in the possibility of having the same SW for organizing event on both desktop and mobile devices. But as long as there is a decent SW for simple measured trainings on Android (SI-Droid Event), I don't feel like spending time on this option...

**Comment by fvacek** [comment]
I have the same opinion. If we plan to build QE for Android or better say for mobile platform, we should consider to create different project sharing DB tables and maybe some libraries, like SI reader protocol. Rest of app I feel to be better to build from scratch. Current QE UI is far away from sufficient mobile experience.
