### ISSUE TITLE
Problém s importem rankingu

### ISSUE THREAD

**Issue by pese76** [fvacek/quickbox#307]
Zdravím,
připravujeme mistrovství oblasti a snažím se otestovat losování HD21 dle rankingu. Ale at dělám co dělám neproběhne import csv vyexportovaný z orisu k 31.3. Neporadíte někdo, kde bych mohl hledat problém.

**Comment by fvacek** [comment]
![image](https://user-images.githubusercontent.com/4949019/38470769-dc7b3bf8-3b67-11e8-892f-1a455b78c9b5.png)

tohle jsi zkousel?

**Comment by pese76** [comment]
Ano přesně toto. Nejspíše bude problém v odřádkování.  Na Win se mi to zobrazuje vše v jednom řádku. Už  jsem to na daný závod přepral přímým importem z dbf do PSQL. Ale očekávanou funkčnost: stáhnu, tak jak mi dá ORIS a nahraju do systému, jsem na WIN nerozběhnul.

**Comment by fvacek** [comment]
takhle by to melo fungovat, vcera jsem stahnul tento soubor a v pohode ho naimportoval

[1.txt](https://github.com/fvacek/quickbox/files/1888569/1.txt)

**Comment by fvacek** [comment]
muzes mi poslat soubor, ktery importujes ty?

**Comment by pese76** [comment]
Zde je
[export_ranking_2018-03-31_20180410_000644.txt](https://github.com/fvacek/quickbox/files/1892071/export_ranking_2018-03-31_20180410_000644.txt)

**Comment by fvacek** [comment]
pak je to jasny, to co importujes neni CSV, stahni si to z linku, na kterym je napsano `(csv)`
