### ISSUE TITLE
Dialog pro tisk novych vysledku

### ISSUE THREAD

**Issue by Tomaqa** [fvacek/quickbox#309]
Pro tisk jen kategorii s novymi vysledky od posledniho tisku ze zalozky "Statistika zavodu" mi chybi stejny dialog jako pri tisku z "Useky"->"Tisk"->Kategorie.. Nemuzu nastavit typ zalomeni a pokud vyvesovaci jedou na 1 kategorie/1 list papiru, tak je to pro me nepouzitelne a musim tisknout bud vse, nebo rucne vybrane kategorie.

**Comment by fvacek** [comment]
Pri tisku ze zalozky "Statistika zavodu" se bere nastaveni, ktere se vybere v ze zalozky "Statistika zavodu" a ulozi se jako vychozi
