### ISSUE TITLE
Zarizeni znakove tiskarny v Linuxu

### ISSUE THREAD

**Issue by Tomaqa** [fvacek/quickbox#310]
Ve vyberu '/dev/usb/lp*' zarizeni pro znakove tiskarny mi chybela kolonka '/dev/usb/lp0', na kterou se mi to namapovalo, a musel jsem vytvaret symlink lp1->lp0 ..

**Comment by fvacek** [comment]
Combo pro vyber tiskarny je editovatelne, stacilo prepsat lpt1 na lpt0
