### ISSUE TITLE
vynechání času mezi dvěma kontrolami v celkovém čase

### ISSUE THREAD

**Issue by dudasekk** [fvacek/quickbox#311]
Ahoj,
kdybych chtěl vynechat čas mezi dvěma následujícími kontrolami z celkového výsledku.
Vymyslel jsem toto řešení. Je to v pořádku ?
Doplnil bych do tabulky s kontrolama trati položku ignore_split, která by indikovala vynechání postupu
z celkového času. Nejsem si ale jistý v kterém pluginu mám opravit výpočet mezičasů a celkového času.
Díky

**Comment by xkenia** [comment]
Muzes prosim popsat nejakou situaci, kdy je toto potreba? Na zavodech CSOS toto urcite (alespon za poslednich min. 10 let) nenastalo. Diky Kenia

**Comment by dudasekk** [comment]
No, byla to jedna z variant, kdy by na jedné straně silnice byla jedna kontrola a druhá kontrola na druhé straně silnice. A tento úsek by se prostě nezapočítával do času. Jinak teď v  zimě to bylo na Hradubické lize. Karel

**Comment by dudasekk** [comment]
Možná by se to dalo použít i v případě, kdy by se závod končil na dřívější kontrole.

**Comment by fvacek** [comment]
je to vetsi problem, nez by se mohlo na prvni pohled zdat, to ze QE chodi bez problemu je do jiste miry dano tim, ze je dosud jednoduchy, tohle je vec, ktera by kvuli par zavodum za 5 let, mohla veci dost zkomplikovat, takze bych doporucoval to nevymyslet a stavet peclive kontroly, aby se nemusely zavody zkracovat :)
