### ISSUE TITLE
Git build - umisteni aplikacnich dat

### ISSUE THREAD

**Issue by Tomaqa** [fvacek/quickbox#312]
V Git buildu ze zdrojaku jsem nemohl najit soubory, ktere jsou pritomny v releasech napr. pro Win, jako 'translations' nebo zvuky. Uzivatele QE nemaji pouzivat dev verzi ale jen releasy? Nebo jakym zpusobem dodat tyto soubory? Ja jsem to zatim resil jen nesikovnym zkopirovanim techto souboru do 'bin/'. Bez toho jsem nebyl schopen napr. pustit cesky locale.

**Comment by fvacek** [comment]
pro generovani `translations` pouzivam `quickbox/devutils/lctools/lctool.sh`, nevola se automaticky pri CI buildech a je to mozna skoda, ale nestiham :)

zvuky se automaticky zkopiruji pri buildu do adresare `bin/quickevent-dat` je to v https://github.com/fvacek/quickbox/blob/master/appdatafiles.pri
