### ISSUE TITLE
Prilis siroky tiskovy vystup v PDF

### ISSUE THREAD

**Issue by tsieger** [fvacek/quickbox#314]
Pri tisku startovek, vysledku apod. z QE 1.1.18 bylo vygenerovane PDF sirsi, nez co zvladla A4 tiskarna, a tak cca posledni 2 znaky vpravo chybely. 
Vyresili jsme to tim, ze jsme PDF neposilali primo na tiskarnu, ale otevreli vzdy v Acrobat Reader a tam pred tiskem nastavili "zmensit prilis velke stranky".

Nejsem si jisty, ze problem byl na strane QE, ale pro pripad, ze ano, na to radeji upozornuji.

Detaily, budou-li potreba (tiskarna, driver, ukazka PDF dodam dle potreby).

**Comment by fvacek** [comment]
To je zvlastni, sirka stranky je nastavena na 210 mm, prokladm PDF s vysledky z nami naposled poradanych zavodu. 

[report.pdf](https://github.com/fvacek/quickbox/files/1931517/report.pdf)

jinak jze sirku stranky menit v souboru qml/quickevent/Runs/reports/results_stage.qml na radku 34

**Comment by VoiToi** [comment]
Potvrzuji, toto mi dělá QE 1.1.12 i 1.1.20 a také jsem to loni řešil tiskem do PDF a zmenšením stránky v Acrobat Readeru.

**Comment by VoiToi** [comment]
Není těch 210mm náhodou šířka tištěného bloku? Když jsem to změnil na 200mm, tiskne to dobře a mám po každé straně cca 1 cm okraj, tedy jen o pár mm víc, než zvládne tiskárna.

**Comment by VoiToi** [comment]
Jinak, úpravu pro startovky je třeba udělat v qml\quickevent\Runs\reports\startList_classes.qml na řádku 35, který vypadá prakticky stejně jako u výsledků (results_stage.qml).
Pokud si nejsme jistí, co to těch 210mm přesně znamená a pokud se to třeba na linuxu chová jinak, bylo by dobré to vytáhnout do nějakého globálnějšího nastavení, ať se to nemusí měnit ve všech šablonách.

**Comment by fvacek** [comment]
210 je sirka stranky + 5 mm na kazde strane. Pokud to zmenis na 200 a tiskarna tiskne na stred, vychazi to presne na kazde strane 5+5mm. QE nedela rozdil mezi tim, jestli tiskne do PDF nebo na tiskarnu, PDF je take tiskarna. Pokud v PDF a na papire jsou jine vysledky, musi to byt nastavenim tiskarny. Pokud nekdo z QE obdrzel jine PDF nez sirka stranky 210 mm s 5 mm okraji na kazde strane, je to chyba QE, ale mne se to jeste nestalo.

V nekterych sestavach je dost mista, takze je muzeme prozatim zuzit, nez prijdeme na to, cim je zpusoben tento problem. 

Dalsi moznost je, pridat do nastaveni tisku volitelnou sirku okraju

**Comment by VoiToi** [comment]
Ale on není rozdíl při tisku do PDF a při tisku přímo. Právě že to je stejné, i při tisku přímo mi kus na papíře chybí (při šířce 210). Akorát že pokud to vytisknu do PDF, tak to můžu zmenšit v Acrobat Readeru a vytisknout to celé (i bez úpravy šablony, která je ale pohodlnější).

**Comment by fvacek** [comment]
Pokud to dokazes spatne vytisknout do PDF, pak je chyba v QE, jenom ji nedokazu zreprodukovat. Muzes prosim prilozit takove PDF?

**Comment by VoiToi** [comment]
Přikládám.

[report.pdf](https://github.com/fvacek/quickbox/files/1975892/report.pdf)

Mimochodem, to PDF vypadá jako v pohodě, jen má malé okraje. Je možné, že některá tiskárna to dá a zvládne to vytisknout i takto bez změny měřítka, ale laser Canon 6310 ořízne vpravo asi 2 - 3mm.

**Comment by VoiToi** [comment]
Takže není vidět 2 znaky z převýšení a poslední 2 čísla SI čipu, což je blbé. :-)

**Comment by fvacek** [comment]
Nektere tiskarny nedokazou tisknout s 5 mm okrajem, proto by bylo asi nejjednodussi reseni nastavit ve vsech sestavach horizontalni okraje na 10 mm (QML property `hinset: 10`)

**Comment by fvacek** [comment]
fixed in 6d5c7c201fcc1ca3a8d32f6bdfe8e7395236c2cb
