### ISSUE TITLE
Otázka ohledně vyčítání

### ISSUE THREAD

**Issue by melimat** [fvacek/quickbox#316]
Moc se omlouvám, ale u mě nejde o žádnou chybu, ale o otázku, a to jestli quickevent umožňuje paralerní vyčítání na dvou počítačích nezávisle. Samozřejmě zpojených v síti.

**Comment by mezkov** [comment]
Ahoj, QE umí vyčítat ze dvou i více počítačů. Jedinou podmínkou je použití databáze PostgreSQL, při použití SQLite souboru to nejde.

Pokud bys chtěl na obou počítačích i tisknout lístečky, musíš si v panelu pro tisk lístečků zaškrtnout, aby to tisklo čipy vyčtené pouze na tom samém počítači. Jinak by to tisklo nahodile na obou tiskárničkách.

**Comment by melimat** [comment]
Děkuji moc.
