### ISSUE TITLE
Option to filter classes when print Start list for starters

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#318]
regression

**Comment by VoiToi** [comment]
Toto se dá opravit na verzi 1.1.20 tak, že v souboru QuickEvent_1.1.20\qml\quickevent\Runs\StartLists.qml na řádku 302 změním příznak *dlg.classFilterVisible* z false na true. :-)
Zdá se mi, že to funguje správně a není tedy důvod, aby to bylo vypnuté.

**Comment by fvacek** [comment]
asi nejaky preklep :)
