### ISSUE TITLE
Startovka - chyba zalomení po sloupcích, vytékání textu ze stránky

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#319]
Pokud zkusím tisk startovky ve dvou sloupcích, začínají některé sloupce níže než u horního okraje (někdy až skoro na konci stránky) a část sloupce pak přetéká ven ze stránky a tedy se nevytiskne.
[startofka_fuj.pdf](https://github.com/fvacek/quickbox/files/1975606/startofka_fuj.pdf)

Takto se chovají verze 1.1.12 i 1.1.20, tedy pravděpodobně i všechny mezi tím.

Je to škoda, zalomení po sloupcích by mi často nejvíce vyhovovalo.

**Comment by VoiToi** [comment]
Zalomení se nejspíše rozbíjí jen v případě, že nějaká kategorie má více závodníků, než se vejde na výšku jednoho sloupce.

**Comment by VoiToi** [comment]
Problém je i se startovkou bez startovních šísel. Přikládám i data závodu.
[ZA_3305.ZIP](https://github.com/fvacek/quickbox/files/1975716/ZA_3305.ZIP)
[startofka2_fuj.pdf](https://github.com/fvacek/quickbox/files/1975718/startofka2_fuj.pdf)

**Comment by VoiToi** [comment]
A stejný problém je i se startovkou bez vakantů.

**Comment by fvacek** [comment]
#264 podobny problem se resil jiz zde, ale tady bych rekl, ze se jedna o jiny problem.

aby bylo mozne chybu zreprodukovat, je nutne zvolit zalomeni po sloupcich

**Comment by fvacek** [comment]
fixed
