### ISSUE TITLE
Klávesová zkratka pro přidání závodníka

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#320]
O víkendu jsme pořádali ŽA, myslím, že jsme ve dvou lidech dohlásili tak 100 - 150 lidí, plus další změny.
Při takhle hromadném datlování se ukázala jako největší brzda malinká ikonka pro přidání závodníka, v podstatě to byl často jediný úkon vyžadující myš, někdy mi i kurzor zůstal na stejném místě.
Každopádně velice by pomohla klávesová zkratka pro přidání závodníka. Pokud existuje, tak prosím o její zveřejnění. Pokud neexistuje, mohlo by to být třeba Alt+D, stejně jako v OB2000, ale skoro cokoliv bude lepší než jen pidi ikonka. A také prosím o doplnění popisu zkratky do tooltipu k ikonce.
Jinak by k tomu mohla existovat i duplicitně položka v menu, která má vždy nějakou zkratku, pak zkratka ale musí být unikátní přes obě zobrazená menu.

Díky, Vojta

**Comment by fvacek** [comment]
je to Ctrl+Ins

**Comment by jmacura** [comment]
Řekl bych, že takovou informaci bude časem hledat víc lidí, a určite ji nebudou hledat procházením starých issues. Dovolil jsem si tedy založit novou stránku na wiki, kde by mohly být použité klávesové zkratky vypsané.
Feel free to delete it or improve it :-)

**Comment by fvacek** [comment]
to je supr, jinak je ale divny, ze se zkratky nevypisuji v menu vedle nazvu, myslim, ze to drive tak bylo, proto je nebylo nutne hledat, bud v QT neco vylepsili nebo pohnojili. Brzi maji vyjit Qt 5.11, tak uvidime, jestli se to nevrati.

**Comment by fvacek** [comment]
jaky je link na tu wiki stranku?

**Comment by Paukert** [comment]
[https://github.com/fvacek/quickbox/wiki/Kl%C3%A1vesov%C3%A9-zkratky](https://github.com/fvacek/quickbox/wiki/Kl%C3%A1vesov%C3%A9-zkratky)

**Comment by fvacek** [comment]
klavesove zkratky z kontextovych menu  vymizely v Qt 5.10, je to chyba v Qt https://bugreports.qt.io/browse/QTBUG-69452
