### ISSUE TITLE
Při dohlašování nejsou vidět vakanti na konci kategorie

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#321]
Pokud jsou v kategorii definováni vakanti pouze na konci kategorie, pak při dohlašování nového závodníka není vidět, zda na konci ještě zbývá nějaký vakant, ani kolik jich případně je. Navíc okno se startovkou se otevře s focusem na začátek kategorie, takže se musím podívat na konec, přičíst jeden interval k poslendímu zaávodníkovi, vrátit se na začátek a start zapsat do volného (nového) řádku.
Použitelnost tohoto je nízká a kontrola toho, zda nedohlašuju i přes počet vakantů, je taky velmi špatná (toto naštěstí je u nás řešeno offline kontrolou lidí na prezentaci vůči vytištěné startovce, ale počítač by mohl být spolehlivější).

**Comment by fvacek** [comment]
V Statistics window vidis pocet volnych map

**Comment by VoiToi** [comment]
Ano, to vím taky. Ale pokud zadávám desitky dohlášek za sebou, tak nechci kontrolovat ještě další okno. Z hlediska použitelnosti (usability) by mě to, že chybí vakant v kategorii, mělo praštit do očí hned, jak se pokusím tam někoho dohlásit, tedy pokud možno by to mělo být vidět přímo v tom workflow, které dělám. A vakanti na začátku a uprostřed kategorie tam vidět jsou (zelenou), tak by bylo dobré tam podobně zobrazit i ty na konci.

**Comment by fvacek** [comment]
souhlasim s tim, ze zelena cara na konci a na zacatku by byla fajn, souvisi to s issue #283

**Comment by fvacek** [comment]
done 
c783a7f
