### ISSUE TITLE
Use all maps

### ISSUE THREAD

**Issue by jakub-h** [fvacek/quickbox#324]
Ahoj,
není mi úplně jasné, co by měl dělat checkbox Use all maps. Myslel jsem, že bude nějak přidávat vakanty do losování podle volných map, ale vždy způsobí pád. 

Verze 1.1.20 na Centosu

**Comment by fvacek** [comment]
ucel funkce je pridat tolik vakantu do startovek, aby se pouzily vsechny mapy, pokud to zpusobuje pad, napis, co mam udelat, abych to zreprodukoval a ja to opravim

**Comment by janzhanal** [comment]
Podle nas se to stava, pokud jdes losovat a jedna kategorie je prazdna (zadne prihlasky, zadne mapy)

**Comment by krizek007** [comment]
Pri priprave na nas zavod se mi stalo, ze Use all maps mi vkladalo vic vakantu, bylo potreba (vetsinou na konec startovniho pole. Nakonec jsem use all maps nepouzival, a pouzival pocet vakantu po kazdych x startujicich. Nicmene, taky se obcas stalo, ze se vakant pridal i nakonec, i kdyz nemel... 
Verze 1.1.20 na Windows 10. Vsechno ostatni bylo v pohode. Diky!
