### ISSUE TITLE
Anglické názvy OB disciplín

### ISSUE THREAD

**Issue by lpechacek** [fvacek/quickbox#325]
Při vytváření testovacího závodu jsem narazil v anglické lokalizaci QE na nestandardní názvy OB disciplín. Klasika se nyní anglicky nazývá "[Long distance](https://en.wikipedia.org/wiki/Orienteering#Competition_types)". "Short distance" interpretuji podle [výstupů z ORISu](https://oris.orientacnisporty.cz/API/?format=xml&method=getEvent&id=3905) jako krátkou trať, která se v angličtině nazývá "Middle distance".  "Relays" navrhuji přejmenovat na "Relay", v souladu s [IOF Rules](http://orienteering.org/wp-content/uploads/2010/12/IOF-Rules-2018-v1.14final.pdf), bod 1.5.

Navrhovaná úprava kódu:
```
diff --git a/quickevent/app/plugins/qml/Event/src/eventdialogwidget.ui b/quickevent/app/plugins/qml/Event/src/eventdialogwidget.ui
index f2fae3377d61..85adf4446fc1 100644
--- a/quickevent/app/plugins/qml/Event/src/eventdialogwidget.ui
+++ b/quickevent/app/plugins/qml/Event/src/eventdialogwidget.ui
@@ -254,12 +254,12 @@
     <widget class="QComboBox" name="cbxDisciplineId">
      <item>
       <property name="text">
-       <string>Classic</string>
+       <string>Long distance</string>
       </property>
      </item>
      <item>
       <property name="text">
-       <string>Short distance</string>
+       <string>Middle distance</string>
       </property>
      </item>
      <item>
@@ -274,7 +274,7 @@
      </item>
      <item>
       <property name="text">
-       <string>Relays</string>
+       <string>Relay</string>
       </property>
      </item>
     </widget>
```

ORIS id 4, který je teď "Middle", je potřeba ověřit. Pravděpodobně se jedná o dlouhou trať.

Další typy závodů objevené v ORISu jsou:
6 = Družstva / Teams
9 = Noční / Night
13 = Etapový závod / Multi-stage

**Comment by lpechacek** [comment]
> ORIS id 4, který je teď "Middle", je potřeba ověřit. Pravděpodobně se jedná o dlouhou trať.

Potvrzeno. 4 je DT.
https://oris.orientacnisporty.cz/API/?format=xml&method=getEvent&id=4726

**Comment by fvacek** [comment]
muzes prosim udelat pull request?

**Comment by lpechacek** [comment]
Hotovo.
