### ISSUE TITLE
Neoražený cíl - chybí ve výsledcích

### ISSUE THREAD

**Issue by nitschk** [fvacek/quickbox#326]
Pokud závodník zapomene orazit cíl, na lístečku s mezičasy se mu objeví nějaký nesmyslný čas. To asi úplně nevadí, lepší by teda bylo tam napsat něco jako DNF, nebo Missing Finish.
Co je ale větší problém je, že závodník není vůbec ve výsledcích (nebo výsledkách?).
V příloze je soubor z našeho sobotního závodu. Závodník, který cíl neorazil a ve výsledcích chybí je Svítil Patrik, kategorie H12 
[180603_2054.zip](https://github.com/fvacek/quickbox/files/2069974/180603_2054.zip)

Abych ho do výsledků dostal, ručně jsem mu zadal nějaký čas a nechal ho Disk. Ale sám jsem nepřišel na to že v těch výsledkách chybí....

**Comment by fvacek** [comment]
`Classic race` card checker should fix this since QE 2.2.0

**Comment by fvacek** [comment]
muze to prosim nekdo otestovat?
