### ISSUE TITLE
Alternativni navod

### ISSUE THREAD

**Issue by Tomaqa** [fvacek/quickbox#329]
Ahoj, behem poradani s QE jsem prubezne sepisoval nas interni (zlinsky) [navod](https://docs.google.com/document/d/1W8cPFhdmi7qP76Qv8TkzROivUucRSOzlqyeKix4pB7U/edit?usp=sharing) pro praci s programem. Je to psane trochu blbuvzdorne (resp. snaha byla) i pro lidi ne prilis orientujici se v IT.
Davam to sem jen pro pripad, ze by byl zajem to referencovat nebo zaintegrovat do Wiki. Spis mi to ale prijde lepsi to nechat oddelene, protoze pro nektere to je zbytecne podrobne.
Pokud by vam to pripadalo pouzitelne, vyuzijte toho jak uznate za vhodne. Mozna se budu moci zaangazovat i primo ja, ale asi bych to odlozil az k nejakemu nasemu dalsimu poradani.

**Comment by fvacek** [comment]
Super, diky moc, dal jsem link do titulni stranky ve Wiki
