### ISSUE TITLE
Export výsledků jako HTML

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#333]
Export výsledků jako HTML ve verzi 1.1.20 vygeneruje nepěknou sestavu.

![obrazek](https://user-images.githubusercontent.com/18633350/41617231-3827f2fe-7400-11e8-929b-c8dab17943b1.png)

**Comment by fvacek** [comment]
to je cena za to, ze se HTML generuje z tiskove sestavy, jestli chces mit sestavu peknou, je tu moznost vyuzit quickhttpd, uznavam, ze je to trochu nesikovne, ale takovy je aktualni stav vyvoje.
