### ISSUE TITLE
Auto označení off-race závodníků vyctenim krabicky

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#334]
Líbí se mi nápad @petrsv, viz https://github.com/fvacek/quickbox/issues/269.
Jak píše Petr níže, ušetřilo by to spousty práce při ručním dohledávání lidí podle startovek ze startu. Vždy strávíme spousty času ručním odškrtáváním, dohledáváním a vyptáváním (ne vždy jsou informace ze startovek ze startu úplně přesné či jasné) zdali závodník odstartoval/neodstartoval. Asi by se to dalo rozšířit též na mazací a startovací krabičky. Díky moc, pokud se v tom podaří něco udělat. Každá taková pomoc je vítána!

> Bylo by super a ušetřilo by hodně práce mít možnost načíst check krabičky (nebo importovat jejich obsah v nějakém formátu z SI configu) po ukončení startu s kontrolou a auto označením off-race závodníků, kteří neodstartovali - u nás skoro 100, které jsme dlouho ručně dohledávali a odškrtávali z vrácené papírové startovky ke schválení finálních výsledků a vyhlášení.

**Comment by fvacek** [comment]
vycitani funguje, zbyva dodelat `označení off-race závodníků`

**Comment by fvacek** [comment]
zatim jsem pridal do `Runs` sloupec `Check`, ktery zobrazuje check time z krabicky, pokud ho najde. Pro oznacovani off-race zavodniku jsem jeste nevymyslel logiku, hlavne bych chtel predejit situaci, kdy bude oznacen zbloudily zavodnik off-race jenom proto, protoze check krabicka byla vyctena driv, nez pribehl, coz se snadno muze stat, protoze start se boura relativne brzy.

**Comment by mezkov** [comment]
Možná to ani není potřeba překlápět do off-race. Můžeme tak rozlišovat stavy off-race(=závodník běží mimo soutěž) a DNS(=závodník neodstartoval)

**Comment by xkenia** [comment]
Mozna by stalo za to si rici, co znamena "off-race". Zavodnik je timto oznacen jako "mimo soutez" nebo jako "mimo zavod" (tedy DNS)?

**Comment by fvacek** [comment]
mimo zavod, je to kvuli vicedennim zavodum, kdy zavodnik chce nekterou etapu nebezet

**Comment by fvacek** [comment]
jinak jsem naimplementoval razeni podle vic sloupcu, tak uz to nebude problem vyhledat
