### ISSUE TITLE
QE 1.1.20 Oblastní žebříček - Říčany u Brna - 16.6.2018

### ISSUE THREAD

**Issue by Czelda** [fvacek/quickbox#336]
ORIS:   [https://oris.orientacnisporty.cz/Zavod?id=4390](https://oris.orientacnisporty.cz/Zavod?id=4390)
QE:   [soubor QBE pro QE 1.1.20](https://github.com/fvacek/quickbox/files/2130861/10poSkonceniZavodu.zip)
Konfigurace: 2 stroje s Windows propojené patch kabelem

Tak další úspěšně zvládnutý závod na QE ! Díky.

Poznámky:
1. **Občas vytuhlo vyčítání** - prostě závodník vložil čip do vyčítací krabičky a nic se nestalo (ani po opakovaném vložení). Pomohl restart QE. Stalo se cca 4x během vyčítání (vyčítalo celkem 309 závodníků) a mám pocit, že většinou tehdy, když bylo zrovna zobrazeno okno se statistikami závodu.
2. **Time to close** ve statistikách závodu - skvělá funkce k odhadnutí, zda se již můžou vyhlašovat výsledky "na bedně", k dokonalosti by to ale chtělo vylepšit ještě jednu věc. A sice - nějak rozlišit stav "zatím nelze stanovit" (v současnosti hodnota 0.00, když např. ještě nikdo v příslušné kategorii nedoběhl nebo pokud je tam přihlášeno méně závodníků než 3) od stavu "už první tři místa nikdo neovlivní" (taky hodnota 0.00). V prvním případě by se tam mohla zobrazovat třeba hodnota -1, aby člověk měl jistotu, že když jsou ve všech kategoriích 0.00, může se fakt jít vyhlašovat. (Ano, já vím, je potřeba jako rezervu ještě počítat nějaký čas mezi doběhem a vyčtením, ale to teď neřeším.)
3. **Špatné přiřazení čipu zjištěné po vyčtení** Když má závodník špatně zadáno číslo čipu, zjistí se to při vyčtení - zahraje to takový upozorňovací zvuk, což je bezva. Několikrát se nám to stalo, a tak jsme zkusili  použít funkci "Přiřadit či závodníkovi", která by v kontextovém menu vyčtených záznamů v okně "Vyčítání SI čipů" měla přesně pro tento účel být. Ta sice dočasně problém vyřeší (vyjedou správně mezičasy), ale bohužel to NENÍ to samé, jako když namísto toho člověk v okně "Závodníci" ručně zadá správné číslo čipu a pak nechá závodníka znovu vyčíst !!! Nešlo by to časem upravit tak, aby to to samé bylo ?!!

**Comment by fvacek** [comment]
> Občas vytuhlo vyčítání - prostě závodník vložil čip do vyčítací krabičky a nic se nestalo (ani po opakovaném vložení). Pomohl restart QE. Stalo se cca 4x během vyčítání (vyčítalo celkem 309 závodníků) a mám pocit, že většinou tehdy, když bylo zrovna zobrazeno okno se statistikami závodu.

Verim, ale tezko to zreprodukovat. Mne se treba toto nikdy nestalo. Vycitani bezi ve stejne threadu jako zbytek aplikce, takze se teoreticky muze stat, ze by se to nestihalo, ale moc se mi to nezda. Meli jste vycitaci krabicku na auto-send?

**Comment by fvacek** [comment]
> Time to close ve statistikách závodu - skvělá funkce k odhadnutí, zda se již můžou vyhlašovat výsledky "na bedně", k dokonalosti by to ale chtělo vylepšit ještě jednu věc. A sice - nějak rozlišit stav "zatím nelze stanovit" (v současnosti hodnota 0.00, když např. ještě nikdo v příslušné kategorii nedoběhl nebo pokud je tam přihlášeno méně závodníků než 3) od stavu "už první tři místa nikdo neovlivní" (taky hodnota 0.00). V prvním případě by se tam mohla zobrazovat třeba hodnota -1, aby člověk měl jistotu, že když jsou ve všech kategoriích 0.00, může se fakt jít vyhlašovat. (Ano, já vím, je potřeba jako rezervu ještě počítat nějaký čas mezi doběhem a vyčtením, ale to teď neřeším.)

Time to close extended #337

**Comment by fvacek** [comment]
> Špatné přiřazení čipu zjištěné po vyčtení Když má závodník špatně zadáno číslo čipu, zjistí se to při vyčtení - zahraje to takový upozorňovací zvuk, což je bezva. Několikrát se nám to stalo, a tak jsme zkusili použít funkci "Přiřadit či závodníkovi", která by v kontextovém menu vyčtených záznamů v okně "Vyčítání SI čipů" měla přesně pro tento účel být. Ta sice dočasně problém vyřeší (vyjedou správně mezičasy), ale bohužel to NENÍ to samé, jako když namísto toho člověk v okně "Závodníci" ručně zadá správné číslo čipu a pak nechá závodníka znovu vyčíst !!! Nešlo by to časem upravit tak, aby to to samé bylo ?!!

Je to to same, v cem se to lisi? 

Priradit cip zavodnikovi nezpusobi, prepsani jeho SI, takze pri dalsim vycteni nebude opet nalezen, ale to je jediny rozdil. Duvod proc je tomu tak je ten, ze QE diky tomu podporuje start vice zavodniku s jednim cipem.

**Comment by Czelda** [comment]
>  Je to to same, v cem se to lisi?
> 
> Priradit cip zavodnikovi nezpusobi, prepsani jeho SI, takze pri dalsim vycteni nebude opet nalezen, ale to je jediny rozdil. Duvod proc je tomu tak je ten, ze QE diky tomu podporuje start vice zavodniku s jednim cipem.

No udělali jsme to tak a když jsme se chtěli po chvíli na mezičasy dotyčného znovu podívat, zase byl nepřiřazený čip. Kdybychom si třeba chtěli vyjet seznam, jaký kdo čip teda vlastně měl, zase to tam nebude správně atd. Proto jsme to raději u dalších zjištění špatně přiřazených čipů po vyčtení dělali tak, že jsme číslo čipu opravili v okně "Závodníci" a nechali ho znovu vyčíst, i když tyto operace nebyly tak rychlé.
Mimochodem - implementovat možnost, aby jeden čip šel závodem s více závodníky, tímto způsobem není šťastné. ta funkce by se buď neměla implemetovat vůbec (což doporučuju - jak by se třeba řešily protesty, kdy je potřeba zkoumat v krabičkách po závodě, jak a kdy tam který čip prošel, když tam chodil s více závodníky ?) nebo pořádně (pokud možno v programu nepoužívat čip jako ID a tam, kde to jinak nejde (třeba při vyčítání),  při více závodnících v etapě se stejným čipem nějak systémově vyřešit - třeba dotazem - o koho z nich jde) .

**Comment by Czelda** [comment]
> Občas vytuhlo vyčítání - prostě závodník vložil čip do vyčítací krabičky a nic se nestalo (ani po opakovaném vložení). Pomohl restart QE. Stalo se cca 4x během vyčítání (vyčítalo celkem 309 závodníků) a mám pocit, že většinou tehdy, když bylo zrovna zobrazeno okno se statistikami závodu.
> 
> Verim, ale tezko to zreprodukovat. Mne se treba toto nikdy nestalo. Vycitani bezi ve stejne threadu jako zbytek aplikce, takze se teoreticky muze stat, ze by se to nestihalo, ale moc se mi to nezda. Meli jste vycitaci krabicku na auto-send?
Nevím a obávám se, že už to teď zpětně nezjistíme. Ale to by se pak mohlo tak chovat, že po většinu doby (vyčítání 309 závodníků) to funguje OK a jen 4x to vytuhne ?

**Comment by fvacek** [comment]
> No udělali jsme to tak a když jsme se chtěli po chvíli na mezičasy dotyčného znovu podívat, zase byl nepřiřazený čip. 

To neni mozne, ve skutecnosti to je tak, ze cipu priradis zavodnika, pokud jste po chvili meli zase zavodnika z neprirazenym cipem, musela tam probehnout jeste nejaka akce. Pri zavodech byvaji zmatky, takze si myslim, ze to bylo trosku jinak.

> Mimochodem - implementovat možnost, aby jeden čip šel závodem s více závodníky, tímto způsobem není šťastné. Ta funkce by se buď neměla implemetovat vůbec (což doporučuju - jak by se třeba řešily protesty, kdy je potřeba zkoumat v krabičkách po závodě, jak a kdy tam který čip prošel, když tam chodil s více závodníky ?)

prave tim, ze se prirazuje zavodnik vycteni. Timto zpusobem se vi naprosto presne, kolikrat byl cip vycten a kdo s nim bezel. Krabicky neni treba vycitat.

> nebo pořádně (pokud možno v programu nepoužívat čip jako ID a tam, kde to jinak nejde (třeba při vyčítání), při více závodnících v etapě se stejným čipem nějak systémově vyřešit - třeba dotazem - o koho z nich jde) .

QE nepouziva SI jako ID nikde

**Comment by fvacek** [comment]
> Nevím a obávám se, že už to teď zpětně nezjistíme. Ale to by se pak mohlo tak chovat, že po většinu doby (vyčítání 309 závodníků) to funguje OK a jen 4x to vytuhne ?

jak rikam nemam tuseni, nikdy se mi to nestalo. Proto jsem se ptal na auto-send, protoze takhle to pouzivam ja uz roky bez nejmensiho problemu. Vycitani v auto-send je jednodussi, protoze je o jednu komunikaci kratsi. Mozna by se neco naslo v logu. Je potreba se podivat jestli treba neupadl seriovy port nebo neco podobneho. Zatuhnuti vycitani je siroky pojem, obzvlast v pripade, kdy to nejde zreprodukovat.

**Comment by Czelda** [comment]
> No udělali jsme to tak a když jsme se chtěli po chvíli na mezičasy dotyčného znovu podívat, zase byl nepřiřazený čip.
> 
> To neni mozne, ve skutecnosti to je tak, ze cipu priradis zavodnika, pokud jste po chvili meli zase zavodnika z neprirazenym cipem, musela tam probehnout jeste nejaka akce. Pri zavodech byvaji zmatky, takze si myslim, ze to bylo trosku jinak.

Samozřejmě, že při závodech toho bylo hodně, ale jedno vím jistě - nikdo nám tam nevyčítal jen tak zbůhdarma nějaký čip, který by v závodě nešel a zároveň se nestalo, že bychom po vyčtení nakonec úspěšně pro závodníka z tiskárničky nevyloudili lístek s mezičasy. Když si otevřeš data závodu (přiložil jsem je na začátku vlákna) a u prvního neúspěšného vyčtení v okně "Vyčítání SI čipů" (vyčtení s ID 66) si dáš v kontextovém menu "Ukázat mezičasy", tak to nic neukáže !! **Jak to, když jsem si skoro jistý, že jsme přes "Přiřadit čip závodníkovi" pro něho jednorázově lístek vytiskli ?!!!** (Ale už si bohužel nepamatuju, komu jsme tento čip přiřazovali.) 
U dalších neúspěšných vyčtení už jsme šli cestou, že jsme opravili čislo čipu u závodníka a vyčetli znovu (vyčtení s ID 97+98, 144+146, 230+231). Ovšem ani u těchto vyčtení (pokud kliknu na vyčtení s nižším ID)  ani po opravě "Ukázat mezičasy" nic neukáže.

**Comment by fvacek** [comment]
oka, podivame se na to, udelal jsem na to separatni issue #338

**Comment by fvacek** [comment]
co budeme delat s tim obcasnym vytuhnutim vycitani, mas log?

**Comment by Czelda** [comment]
Pokud log není schován někde uvnitř QBE souboru, tak nemám a ani nevím, jak ho získat (nejen teď zpětně ale ani obecně). Problém jsem popsal spíš pro všeobecné povědomí, že se něco takového může dít, ale vyřešení problému asi není akutní. Možná to byla záležitost jen naší konkrétní konfigurace, navíc snadno řešitelná restartem programu.

**Comment by fvacek** [comment]
Pokud se QE nepusti s parametrem `--log-file <file>`, tak se loguje na stderr, coz je ve Windows nikam. Mozna by stalo za umahu toto zmenit, abychom meli postmorten log, coz muze byt casto jedine voditko.

**Comment by fvacek** [comment]
7a09fc458e8d75f4ac17a97800b4975d7645fe57

**Comment by Czelda** [comment]
Hmm, tak to se k logu asi nedostaneme. Navíc jsme při závodech používali pro QE noťály půjčené od "Keni" (? "Köni" :-) ) , které jsme už vrátili. :-(

**Comment by xkenia** [comment]
Notebook je samozrejme k dispozici, takze se zkusime podivat, co tam najdeme. Jen to tak 1-2 dny potrva, mame jej ve "skladu".

**Comment by xkenia** [comment]
Tak jsem to prosel a logy jsou nenasel.
Menu - > view -> Application log zobrazuje pouze aktualni log, jak psal Fanda, windows si je neuklada.

**Comment by fvacek** [comment]
log se defaultne do souboru uklada az od verze 2.0.0, ktera na tech NB urcite nebyla, protoze vysla vcera :(
