### ISSUE TITLE
Špatné přiřazení čipu zjištěné po vyčtení

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#338]

**Comment by fvacek** [comment]
> No udělali jsme to tak a když jsme se chtěli po chvíli na mezičasy dotyčného znovu podívat, zase byl nepřiřazený čip.
> 
> To neni mozne, ve skutecnosti to je tak, ze cipu priradis zavodnika, pokud jste po chvili meli zase zavodnika z neprirazenym cipem, musela tam probehnout jeste nejaka akce. Pri zavodech byvaji zmatky, takze si myslim, ze to bylo trosku jinak.

Samozřejmě, že při závodech toho bylo hodně, ale jedno vím jistě - nikdo nám tam nevyčítal jen tak zbůhdarma nějaký čip, který by v závodě nešel a zároveň se nestalo, že bychom po vyčtení nakonec úspěšně pro závodníka z tiskárničky nevyloudili lístek s mezičasy. Když si otevřeš data závodu (přiložil jsem je na začátku vlákna) a u prvního neúspěšného vyčtení v okně "Vyčítání SI čipů" (vyčtení s ID 66) si dáš v kontextovém menu "Ukázat mezičasy", tak to nic neukáže !! **Jak to, když jsem si skoro jistý, že jsme přes "Přiřadit čip závodníkovi" pro něho jednorázově lístek vytiskli ?!!!** (Ale už si bohužel nepamatuju, komu jsme tento čip přiřazovali.) 
U dalších neúspěšných vyčtení už jsme šli cestou, že jsme opravili čislo čipu u závodníka a vyčetli znovu (vyčtení s ID 97+98, 144+146, 230+231). Ovšem ani u těchto vyčtení (pokud kliknu na vyčtení s nižším ID)  ani po opravě "Ukázat mezičasy" nic neukáže.

**Comment by fvacek** [comment]
Podnikl jsem nasledujici kroky:
1. v tabulce cards jsem pomoci SQL tool smazal zaznam s ID=231
1. zaznamu s ID=230 jsem pres kontextove menu priradil zavodnika `Svirák Timotei`

je to takhle v poradku?

**Comment by Czelda** [comment]
No u těch s vyšším ID je to jiné, protože už mají u závodníka čip zadaný správně. Co ale nechápu, je, že když dám teď "Přiřadit čip závodníkovi" u vyčtení s ID 66, fakt tam ten přiřazený závodník je už OK a zůstane tam. Jsem si skoro jistý, že přesně takhle jsem to udělal i v závodě, lístek vytiskl, ale závodník tam přiřazený nezůstal ???!!! Rozdíl je v tom, že jsme běželi na jiných PC a pracovali s PostgreSQL, ale jinak fakt nevím. Tak to asi zatím nechme - třeba něco podobného bude časem pozorovat i někdo jiný.

**Comment by fvacek** [comment]
za 14 dni poradame HSH, tam by se ta chyba projevit mela, pokud tam je.
