### ISSUE TITLE
Edit stage time format not handy

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#34]
AM/PM switching is obstruction, 24h format is faster for input, more readable too, and much more common in current czech ob culture

**Comment by fvacek** [comment]
SI stations itself are using 12hr time, so there is no gain from using 24hr time in application

**Comment by Amaroun** [comment]
The dialog is in fact 24h, but using am/pm notation. And if the time will be reduced to 12h only format, two different stages could end up having same time (8:00 and 20:00 in the same day)

**Comment by Amaroun** [comment]
And by the way, base design decisions on unrelated plugin, which is dependant to one of multiple providers of punch tracking systems, is hardly relevant

**Comment by fvacek** [comment]
Yes, it is. I just have no opinion. When more providers will be supported, we will get information enough to make decisions. But now it is equal for me. If you need/want this currently cosmetic change, I can change it.  It is a trivial change.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: AmarounSent: Tuesday, May 19, 2015 11:00To: fvacek/quickboxReply To: fvacek/quickboxCc: Fanda VacekSubject: Re: [quickbox] Edit stage time format not handy (#34)And by the way, base design decisions on unrelated plugin, which is dependant to one of multiple providers of punch tracking systems, is hardly relevant

—Reply to this email directly or view it on GitHub.

**Comment by fvacek** [comment]
ok, well, it's faster to change it than talk about it :) reopening

**Comment by Amaroun** [comment]
I admit this issue may seem like a nitpicking, but ergonomics of the software is from may point of view important.
The time needed for operations should be minimal possible, and I think that frequent users will appreciate any possible speedup.

In this case it means time format one can be entered without users hands leaving numerical keyboard or row (to change am/pm you need to go to alphabetical or cursor keys, which is unnecessarily disturbing)

Another example would be properly set focus when entering the dialog. Save key is not right choice. If you enter the dialog for the first time, you want to change values, because default one are never what you want. And if open the dialog next time, you either want to change the values, so save is not interesting till you have done it, or you just want to look at them, in witch case you mostly want to cancel afterward, but thats easier to be done by esc key. So the focus should lay on first editable item.

And yet another user feature (I admit it's not relevant to current case) and by the way strong point of popular OB2000 application is ability to use keyboard shorcuts to get to frequently used functions any time.

I admit ergonomic is not very exact and hugely subjective, and those are only my opinions. If you prefer me not reporting such opinions through issues, I would not. I just think that user comes first an such details polishes any application to a form liked by users.

**Comment by fvacek** [comment]
These are all relevant points, not nitpicking. But whole project is in early stage and I'm still only one developer so I have lot of more serious bugs/features to implement. Anyway its important to gather such a minor issues since they has crucial impact to end user experience. So please, fire every minor issue regardless what is my instant opinion. 

Minor issues are also good entry point for potential beginner contributors to project. What about you. Wouldn't you try to take some minor issue?

**Comment by Amaroun** [comment]
I will try to create time budget for active development, but as I'm not a Qt or qml programmer and not really fluent with git either, it will take some time before I make reasonable impact.

**Comment by fvacek** [comment]
no problem, testing is enough :)

**Comment by fvacek** [comment]
It seems that QTimeEdit is using host system time format. I think that it is enough, since user will se consistent time information in the same for as his OS presents

**Comment by fvacek** [comment]
I have 24 hr format on my Kubuntu

**Comment by Amaroun** [comment]
I have 24-hour system format, still I'm getting 12h from QE. It seems this format has something to do with default style of Qt, but I cannot  find how to change it. Will look closer into this.
