### ISSUE TITLE
Export vycteni ciloveho casu pro EmmaClient

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#341]
Po vycteni cipu pridat do noveho souboru informaci o dobehnutem zavodnikovi ve formatu:
` 8619494: FIN/09:58:25.0000/MP  `
` 8620034: FIN/09:00:00.0000/DNF `
` 8620034: FIN/10:38:49.0000/O.K.`

Toto je potom schopen cist EmmaClient.

**Comment by fvacek** [comment]
1. to je cas na trati nebo cas v cilove kontrole?
1. co znamenaji MP a DNF? je to mimo soutez a DISK?

**Comment by janzhanal** [comment]
2. MP = misspunch
DNF = did not finish (projevujici se jako neorazeny cil)

**Comment by xkenia** [comment]
1.toto jsou cilove casy

Pred lomitkem je FIN jako finish. Stejny format ma i soubor, ktery chodi pres Racom, tam je potom misto FIN kod kontroly z lesa. Takze pripadne QuickShow by se mohl naucit toto cist.
Priklad [rawsplits](https://drive.google.com/file/d/0B-Rkbm3FZI8ZTEo4VmRvNjA0akU/view?usp=sharing)

**Comment by fvacek** [comment]
> toto jsou cilove casy
takze zavodnik v prikladu byl v lese 10 hodin?

**Comment by xkenia** [comment]
To je realny cas dobehu zavodnika, tedy 9:58:25AM.

Tim padem pro export budu muset vzit cas 00 zavodu z tabulky stages a pricist finishTimeMS z tabulky runs.
