### ISSUE TITLE
Make user aware of virtual folders in Windows when saving into QE directory in Program Files/

### ISSUE THREAD

**Issue by jmacura** [fvacek/quickbox#342]
Already mentioned in #340 . It is not actually an issue of QuickEvent itself, but I think it's worth eliminate the trouble in the sake of user-friendliness.

**Problem:**
Files created with QE in its /Program Files directory cannot be found outside the program itself.
Proofs:
![cesta_k_db](https://user-images.githubusercontent.com/5598693/42138548-303b0b0c-7d7f-11e8-955a-22689ef9c09c.PNG)
![totalcmd_adresar](https://user-images.githubusercontent.com/5598693/42138549-371125c4-7d7f-11e8-8ef2-906dbffd6575.PNG)
![cmd_adresar](https://user-images.githubusercontent.com/5598693/42138550-38fa9a0a-7d7f-11e8-90a1-98222fcadb25.PNG)

As is evident from the attached files, the db exists in the directory, but is totally invisible outside of QE.

**Solution:**
https://stackoverflow.com/questions/19163699/qt-windows-cannot-find-file-that-qt-open-file-dialog-can

There is no solution which would be easy and obvious. It's a Windows shitty hack. I propose to either warn the user of this problem, or to disallow to save QE files in the protected directories (C:/, C:/Program Files/, C:/Program Files (x86)/ and C:/Windows/). It's really cumbersome to search then for the files in the VirtualStore when one wants to e.g. backup them.

![totalcmd_virtualstore](https://user-images.githubusercontent.com/5598693/42138580-dd136018-7d7f-11e8-919f-8377c18834f6.PNG)

**Comment by fvacek** [comment]
does somebody know, what is a complete list of shitty Win directories?

**Comment by jmacura** [comment]
According to: https://answers.microsoft.com/en-us/windows/forum/windows_vista-files/windows-explorer-compatibility-files/5b377209-cfe4-4be6-959d-e1de4b8be16d
They are these:

- %programfiles%
- %systemroot%
- %systemdrive%
- %programdata%

in the terms of system variables, i.e. on most Win-running computers it will be:

- C:\Program Files and C:\Program Files (x86)
- C:\Windows
- C:\
- C:\ProgramData

respectively.

**Comment by fvacek** [comment]
what about sub-folder rules? If the sub-folders are included, then `C:\` means entire disk C. If they are not, `C:\Program Files and C:\Program Files (x86)\quickevent\data\event.qbe` is a correct place.

**Comment by dg0yt** [comment]
`QStandardPaths::DocumentsLocation` and friends should be the most portable Qt way to determine writable locations: https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by nufue** [comment]
This problem only occurs when the application is not "Run as Administrator" and tries to write files to one of the previously mentioned directories (Program Files etc.). Best practice would be to save "working files" to `C:\Users\<user>\AppData\Local`.

Also the files saved by QE to Program Files should be available at `C:\Users\[username]\AppData\Local\VirtualStore`. See [this SU answer](https://superuser.com/questions/384107/why-cant-i-edit-a-program-files-file-on-windows-7/384116#384116) for more information.

**Comment by fvacek** [comment]
QStandardPaths::writableLocation(QStandardPaths::DataLocation) should be the right choice, see 
7e32b52
