### ISSUE TITLE
Závod štafet a jednotlivců dohromady

### ISSUE THREAD

**Issue by frantisekpasek** [fvacek/quickbox#349]
Je možné ve verzi 2.0.0 pořádat závod štafet a jednotlivců dohromady?
Na vysvětlení: občas pořádáme štafety a k tomu postavíme pár kategorií jednotlivců pro lidi co nedají dohromady štafetu anebo štafetu běžet nechtějí.
Jde mi o to, jestli je možné si to zjednodušit a využít vyčítání do jednoho závodu. Pokud ano, bylo by to super, protože bysme nemuseli řešit, kdo běžel štafetu a kdo jednotlivce.

**Comment by fvacek** [comment]
jenotlivci by museli byt stafeta s jednim usekem

**Comment by xkenia** [comment]
Tady vidim problem se startovnim casem. Pokud jim nedate hromadny start, tak to vidim blede.
Pokud nevadi hromadny start, tak bych to neresil a kazdy by mel normalne svou stafetu - treba i s tim, ze se vi, ze se 2. a dalsi useky nemusi tisknout  ;)
A jeste bacha na cilovou kontrolu, ktera byva casto az za cilem.

**Comment by frantisekpasek** [comment]
OK, díky.
