### ISSUE TITLE
Open COM in card reader plugin window gui is not user friendly

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#35]
Open COM in card reader plugin window is tricky to find, seems like some random decoration, especially as two lines above is the Card reader window caption with decorating icon on same location.

In menu Station I'm not able to tell if the com is currently on or off

Open Com is in local menu of the reader, station setup in main menu of the application

**Comment by fvacek** [comment]
Yes, I'm aware of this inconsistency. There are 2 solutions:

* move SI station setup menu to plugin local menu
* Create Preferencies menu in the main menu and agregate all the plugins setup here, like most of plugin based applications does.

I still don't know which one is better to choose.

**Comment by Amaroun** [comment]
I'm not really sure if the si station is actually part of the plugin configuration.
If you have a computer used for card read out, you most likely just want all stations connected to provide read-out data.
So if autodetection is possible, I wold consider a list-box or a table to display stations available, each with checkbox to switch data acceptance from that station, defaulted to yes. Of course some kind of master switch to turn start/stop accepting data from selected stations is necessery.

If there is no autodetection, the list box would have to be filled in by hand. In such case is difficult to define correct behavior between two contradictory scenarios:

1. A user who needed to restart the app for some reason doesn't want to fill in all the station again, just want to continue operations as before restart. 
2. A user who configured stations yesterday, but now have for example GSM modem on ttyUSB0, and cannot see why his configured port doesn't read anything

Anyway, from my point of view the readout stations configuration should be part of plugin GUI window rather than some in menu preferences dialog.

**Comment by fvacek** [comment]
I have similar opinion, let move SI reader configuration to the local menu

**Comment by paukert** [comment]
SI reader configuration is in the local menu,  there is displayed message "Connected to %1 in direct mode." after opening COM.
