### ISSUE TITLE
Chybějící knihovna ve verzi 2.0.2

### ISSUE THREAD

**Issue by Paukert** [fvacek/quickbox#350]
Při pokusu o spuštění QuickEventu po aktualizaci na verzi 2.0.2 dostávám tuto chybu:

![chyba](https://user-images.githubusercontent.com/15065907/45288815-e8bfd380-b4eb-11e8-9dbe-92f38b0f3511.png)

Testováno na 2 PC se stejným výsledkem.

**Comment by lukaskett** [comment]
Stejný problém, také jsem testoval na dvou pc.

**Comment by fvacek** [comment]
to je divny, mrknu na to, dik

**Comment by fvacek** [comment]
je to opraveny

**Comment by Paukert** [comment]
Udělal bys prosím novou verzi?

**Comment by fvacek** [comment]
je tam
