### ISSUE TITLE
Neorazeni cile - zavodnik neni ve vysledcich

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#352]
zaznamenali jsme na včerejším závodě ŽB, že závodník, který neorazil cíl avšak vyčetl si čip není zařazen ve výsledcích.
Takovýto závodník by však měl být posouzen jako „vzdal závod“ a do výsledků by zařazen být měl.

Milan Venhoda

**Comment by fvacek** [comment]
to by urcite mel, muzete prilozit qbe soubor, prosim

**Comment by Paukert** [comment]
Duplicate of #326

**Comment by fvacek** [comment]
diky Lukasi :)
