### ISSUE TITLE
Nefunkční checkbox "Show off-race"

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#353]
Ahoj, ve verzi 2.0.2 mi nefunguje zaškrtávací pole pro zobrazení sloupce s neodstartovanými závodníky. Nevím jestli se něco změnilo, či je to chyba? 
Při zatrhnutí checkboxu se horizontální scroll bar posune, jakoby tam sloupec s checkboxy přibyl, nicméně tabulka zůstane beze změny. Mohl by ses na to mrknout prosím? Díky.
![show_off-race](https://user-images.githubusercontent.com/30177677/45932449-75eb3980-bf7c-11e8-95e6-9540bfaab224.PNG)

**Comment by fvacek** [comment]
diky za report, mrknu na to

**Comment by fvacek** [comment]
muzes zkusit dat 

<img width="359" alt="image" src="https://user-images.githubusercontent.com/4949019/45959893-37f12280-c01b-11e8-8f4e-4354375a0a1f.png">

jestli to pak nezacne fungovat?

**Comment by fvacek** [comment]
fixed
