### ISSUE TITLE
Štafety: Nefunkční starty jednotlivých vln, ver. 2.0.0

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#354]
V záložce kategorie jsem nastavil čas startu jednotlivých kategorií(minuty od času 00). Nastavení nefungovalo, tak jsem musel v záložce Úseky/Etapy ručně nastavit všem prvním úsekům(šikovný filtr podle úseků) správný čast startu, pokud nebyl 00. Přikládám obrázek nastavení času startu jednotlivých vln.

![startovni_vlny](https://user-images.githubusercontent.com/29544822/46172711-79483300-c2a4-11e8-8158-f0f2cc1350ca.png)

**Comment by fvacek** [comment]
tady existuje workaround, ze se kategorie nalosuji s intervalem 0 minut, ale uznavam, ze by to chtelo vylepsit

**Comment by fvacek** [comment]
Nevim uplne, co s tim, kdyz udelam funkci, ze se po editaci startu kategorie v zalozce Kategorie, nastavi start vsech prvnich useku v dane kategorii, bude to zase nachylne na nechtena prepsani. Nalosovani stafety mi prijde vlastne docela dobry, neda to moc prace a neudela to nikdo omylem. Nastaveni casu prvnich useku je vlastne losovani.

**Comment by fvacek** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4949019/71313024-6e426b00-2433-11ea-9fd4-aa8140ec8cda.png">

na nastaveni casu prvnich useku stafet existuje specialni typ losovani, viz screen-shot. Navic jsem ve verzi 2.3.0 pridal cervene podbarveni startovniho casu prvnich useku  stafet s odlisnym startovnim casem, nez je uvedeno v `classes`
