### ISSUE TITLE
Štafety: Import tratí - počet úseků a startovní čísla

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#355]
Tratě štafet jsem dostal postavené v Ocadu a importoval je ve formátu  OCad v8 _Courses version 8(Text)..._. Import tratí proběhl v pořádku, to jsem si zkontroloval v Edit/Courses. Problémem je nenačtení počtu úseků (Legs) a počátečního startovního čísla v kategorii(Rel.num). Bez vyplnění těchto sloupců nejde správně nalosovat/přiřadit startovní čísla. Oba sloupce jsem ručně vyplnil a pak vše běželo. Opět přikládám screenshot pro upřesnění situace.

![startovni_cisla_useky](https://user-images.githubusercontent.com/29544822/46173543-c88f6300-c2a6-11e8-980b-28b58e6af0ed.png)

**Comment by fvacek** [comment]
mohl by jsi prosim pripojit jeste soubory, ktere jsi importoval a QBE soubor, ktery jsi pouzival?

**Comment by lukaskett** [comment]
jasná věc, jsou tam tratě a konečný qbe soubor
[QE_import_trati.zip](https://github.com/fvacek/quickbox/files/2431905/QE_import_trati.zip)

**Comment by lukaskett** [comment]
ještě přidávám soubor, co jsem importoval
[trate_import.txt](https://github.com/fvacek/quickbox/files/2435514/trate_import.txt)

**Comment by fvacek** [comment]
ja bych rekl, ze problem je v tom, ze tvuj soubor s tratemi neobsahuje cisla stafet a useky, QE umit tento format https://github.com/fvacek/quickbox/wiki/relays-courses-export-v8 , najdes ho na strance https://github.com/fvacek/quickbox/wiki/%C5%A0tafety-v%C3%BDvoj

**Comment by lukaskett** [comment]
mně přijde že obsahuje, nemůže být problém v tom, že se mi classes(kategorie) negenerují automaticky(checkbox není označeny), ale mám je dopsané ručně?

**Comment by fvacek** [comment]
Ahoj, otevrel jsem v QE tvuj zavod, dal jsem import OCad v8 na `trate_import.txt` a vse probehlo v poradku

**Comment by lukaskett** [comment]
Ahoj, v závodě co jsi otevřel jsou tratě už nadefinované, zkus všechny řádky smazat a provést import znovu. Sledy kontrol se načtou, počty úseků(Legs) a starovní čísla(Rel.num) nikoliv. Import nehodí chybu, ale hodnoty ve sloupečcích se nevyplní, viz obrázek.
![import_legs_relnum](https://user-images.githubusercontent.com/29544822/48095787-e0e38d80-e215-11e8-8fa3-eded1d61ce91.jpg)
