### ISSUE TITLE
Štafety: Štafeta mimo soutěž

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#357]
Nepodařilo se mi dát štafetu mimo soutěž. V záložce Úseky/Etapy jsem sice našel sloupeček MS, ten se ale chová jako off start, tedy že závodník neběží. Pokud jsem MS zaškrt, po rozkliknutí štafety se u příslišného bežce objevilo zaškrtnuté políčko NC. Chybí možnost označit MS štafetu jako celek, je jedno z jakého důvodu MS bude. Jako MS bych si představoval, že bude štafeta úplně na konci výsledků a místo pořadového čísla bude mít MS. Zároveň ale bude mít celkový čas a i jednotlivý členové štafety budou mít čas v pořádku.

**Comment by fvacek** [comment]
toto neni dosud naimplementovano

**Comment by fvacek** [comment]
melo by stacit oznacit kterehokoliv zavodnika stafety MS (od verze 2.3.3)
