### ISSUE TITLE
Štafety: Neoražený cíl

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#359]
Pokud závodník neorzí cíl, měl by být disk. Ve výsledcích se zobrazují jen čárky.

![neorazeny cil](https://user-images.githubusercontent.com/29544822/46174927-a4ce1c00-c2aa-11e8-842a-0af329a29a34.png)

![neorazeny cil vysledky](https://user-images.githubusercontent.com/29544822/46175063-fecee180-c2aa-11e8-9665-beff11af4471.png)

**Comment by fvacek** [comment]
dulicate of #326
