### ISSUE TITLE
Cannot read an SI card

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#36]
debug log from plugin (inserting card and removing it later on, with no visible read out. Card log set in plugin settings is not even created, the card is not empty):

<DEB>[sidevicedriver.cpp] >>>> ENTER FN void siut::DeviceDriver::processRxData()
<DEB>[sidevicedriver.cpp] >>>> ENTER FN void siut::DeviceDriver::packetReceived(const QByteArray &)
<DEB>[sidevicedriver.cpp] EXIT FN void siut::DeviceDriver::packetReceived(const QByteArray &)
<DEB>[sidevicedriver.cpp] EXIT FN void siut::DeviceDriver::processRxData()
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processDriverInfo(int, const QString &) 4 "CRC check - data CRC is: 27686 0x6c26 computed CRC: 27686 0x6c26"
<DEB>[cardreaderwidget.cpp] "DriverInfo: CRC check - data CRC is: 27686 0x6c26 computed CRC: 27686 0x6c26"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processDriverInfo(int, const QString &)
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processDriverInfo(int, const QString &) 4 "packetReceived, packetToFinishCount: 0"
<DEB>[cardreaderwidget.cpp] "DriverInfo: packetReceived, packetToFinishCount: 0"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processDriverInfo(int, const QString &)
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processSIMessage(const SIMessageData &)
<DEB>[cardreaderwidget.cpp] "
command: CmdSICard8AndHigherDetectedExt
header: length: 8 [ e8 06 00 08 0f 76 8f 90 ]
"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processSIMessage(const SIMessageData &)
<DEB>[sidevicedriver.cpp] >>>> ENTER FN void siut::DeviceDriver::sendCommand(int, const QByteArray &)
<INFO>[sidevicedriver.cpp] sending command: "length: 8 [ 02 ef 02 01 08 ca 35 03 ]"
<DEB>[sidevicedriver.cpp] EXIT FN void siut::DeviceDriver::sendCommand(int, const QByteArray &)
<DEB>[sidevicedriver.cpp] >>>> ENTER FN void siut::DeviceDriver::processRxData()
<DEB>[sidevicedriver.cpp] >>>> ENTER FN void siut::DeviceDriver::packetReceived(const QByteArray &)
<DEB>[sidevicedriver.cpp] EXIT FN void siut::DeviceDriver::packetReceived(const QByteArray &)
<DEB>[sidevicedriver.cpp] EXIT FN void siut::DeviceDriver::processRxData()
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processDriverInfo(int, const QString &) 4 "CRC check - data CRC is: 20484 0x5004 computed CRC: 20484 0x5004"
<DEB>[cardreaderwidget.cpp] "DriverInfo: CRC check - data CRC is: 20484 0x5004 computed CRC: 20484 0x5004"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processDriverInfo(int, const QString &)
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processDriverInfo(int, const QString &) 4 "packetReceived, packetToFinishCount: 0"
<DEB>[cardreaderwidget.cpp] "DriverInfo: packetReceived, packetToFinishCount: 0"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processDriverInfo(int, const QString &)
<DEB>[cardreaderwidget.cpp] >>>> ENTER FN void CardReaderWidget::processSIMessage(const SIMessageData &)
<DEB>[cardreaderwidget.cpp] "
command: CmdSICardRemovedExt
header: length: 8 [ e7 06 00 08 00 76 8f 90 ]
"
<DEB>[cardreaderwidget.cpp] EXIT FN void CardReaderWidget::processSIMessage(const SIMessageData &)

**Comment by fvacek** [comment]
SI station have to be programed in AUTOSEND EXTENDED mode, other modes are not currently supported. Some dialog with an explanation should be nice for now.

**Comment by fvacek** [comment]
changed to feature request;

#38 Support SI reader station in different modes than AUTOSEND EXTENDED mode
