### ISSUE TITLE
Štafety: Pořadí kategorií ve filtru

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#360]
V záložce Úseky/Etapy jsou v menu _Kategorie:_ jednoltlivé kategorie seřazeny abecedně.

![filtr poradi](https://user-images.githubusercontent.com/29544822/46175361-02169d00-c2ac-11e8-9094-b7b20ca51def.png)

Přišlo by mi lepší je řadit podle id, které odpovídá pořadí tratí v ocadu. Při větším množství kategorií to usnadní vyhledávání.

![filtr poradi kategorie](https://user-images.githubusercontent.com/29544822/46175400-21152f00-c2ac-11e8-8969-9c3c4acb32e0.png)

Ještě přikládám pořadi v Ocadu.

![filtr poradi ocad](https://user-images.githubusercontent.com/29544822/46175420-35592c00-c2ac-11e8-829d-610a80bbbc6f.png)

**Comment by fvacek** [comment]
to nevim, ja bych rekl, ze abecedni razeni je lepsi, kdyz je 50 kategorii, tak jsem rad, ze jesou serazeny podle abecedy, navic abecedni poradi umoznuje inkrementalni vyhledavani v listboxu klavesnici

**Comment by lukaskett** [comment]
máš pravdu, jen mě překvapilo, že si řazení na dvou kartách neodpovídala

**Comment by fvacek** [comment]
tak to muzu zavrit?

**Comment by lukaskett** [comment]
jo můžeš,dík
