### ISSUE TITLE
QE v 2.2.2 SLA 30.-31.3.2019

### ISSUE THREAD

**Issue by petrsv** [fvacek/quickbox#370]
Pořádali jsme 2 závody (NOB 150 závodníků a OŽ 1000 závodníků).
Program fungoval dobře, oceňuji implementaci nových věcí (seznam půjčovaných čipů, grafické zobrazení vakantů, automatická kontrola check time, Services, apod). Jen bych zmínil pár věcí s kterými jsme si nevěděli rady:

1. Jak na on-line výsledky na liveresultat.orienteering.se? Je někde prosím návod, jak to správně nastavit? Službu EmmaClient jsme bohužel nerozchodili. Metodou pokus-omyl jsme nakonec použili službu ResultsExplorer formát IOF-XML 3.0. Fungovalo to dobře, nicméně bez startovních časů a klubů. Je třeba nějak využít - úseky/export/startlist/txt/emmaclient ?

1. #334 je to nějak implementováno nebo ne? Ve Vyčítání je Station/Read station memory - což se mi na několikátý pokus podařilo, ale když dám uložit, přijde mi, že se nestane nic. Dále v závodnících vidím tabulky stations backup memory - není třeba to tam nějak přes ctrl-v nakopírovat podobně jako půjčované čipy?

1.   Od verze 2.0.0 nejsem schopen QE nainstalovat na HP notebook Win 10 v 1809 s hláškou 
![image](https://user-images.githubusercontent.com/33401076/55648508-cde2e280-57e0-11e9-8558-d01e5c5ca799.png). 
Na stejném typu notebooku s Win 10 v 1803 QE funguje bez problémů. Nějaký tip, čím by to mohlo být, nějaká souvislost třeba s #340? 

1. Export výsledků do Orisu fungoval jen ve verzi IOF XML 2.3, verze 3.0 mi nešla.

1. Škoda, že volba shrink page v print/results nezmenší stránku ještě víc (v případě, že by se tam netiskly registračky, bylo by možné vytisknout rychlé výsledky na termotiskárně).  

Díky za odpověď
Petr

**Comment by fvacek** [comment]
> Jak na on-line výsledky na liveresultat.orienteering.se? Je někde prosím návod, jak to správně nastavit? Službu EmmaClient jsme bohužel nerozchodili. Metodou pokus-omyl jsme nakonec použili službu ResultsExplorer formát IOF-XML 3.0. Fungovalo to dobře, nicméně bez startovních časů a klubů. Je třeba nějak využít - úseky/export/startlist/txt/emmaclient ?

Sluzbu EmmaClient si objednal Kena z Brna, pak to ale nejak nedotestovali, takze je mozne, ze to nefunguje spravne. Ja to nepouzivam, takze to testovat neumim, pokud prijdete na to, proc to nefunguje, co se druhe strane nelibi, rad to opravim/upravim

**Comment by fvacek** [comment]
ad 2

to, ze vycitani krabicky nefunguje spolehlive muze byt zpusobeno spatnou el-mag vazbou mezi master a slave krabickou, to se deje i SI-configu, urcite bych doporucil SI-STICK nebo nejakou feritovou tycku. 

Na zalozce Runs pribyl soupec Check, kam se tento cas ulozi po vycteni z krabicky.

**Comment by fvacek** [comment]
ad 3

Od verze 2.0 je QE sestaven 64 bitove, jednim z moznych vyzvetleni je, ze Windows na NB jsou jeste 32-bit

**Comment by fvacek** [comment]
ad 4

zalozil jsem issue #372, muzes tam dopsat, co bylo spatne?

**Comment by fvacek** [comment]
ad 5

kolik ti chybi, mozna by stacilo zmensit okraje

**Comment by petrsv** [comment]
Díky
Ad 3 - Ano, bylo to tím 32-bit
Ad 5 - Okraj jsem zmenšil co šlo, ale nestačilo to - chtělo by to vynechat registračky, což nevím jestli není komplikace?

**Comment by Pjootr** [comment]
Ad 1 - liveresultat.orienteering.se jsem rozhýbal taky metodou pokus omyl, ale manuálním exportem
           z úseky/etapy -> Export ->Results -> IOF-XML 2.3 (bylo to včetně start.časů, ale bez klubů)
           Ukládal jsem manuálně jednou za cca. 2 minuty. Kdyby byl v ResultsExporter formát IOF-XML 2.3           
           měl bych to bez práce (a bez klubů)
Ad 4 - potvrzuji problém s exportem výsledků do ORISu ve formát IOF-XML 3.0 zatímco IOF-XML 2.3 bez problému.

PetrJ

QE ver. 2.2.0

**Comment by fvacek** [comment]
4 jsem snad opravil v #372

**Comment by fvacek** [comment]
ad 5 komplikace to je, leda ze bych udelal dalsi report nebo v report options zaskrtnuti sloupcu, jenz se tam maji objevit. Ani jedno se mi moc nelibi.

**Comment by fvacek** [comment]
Udelal jsem moznost nastaveni sirky stranky, kdyz se nastavi na 80mm a okraj na 1mm, da se to cist, myslim, ze to takhle pujde. Melo by to byt ve verzi 2.2.4
