### ISSUE TITLE
Export výsledků do Orisu IOF XML 3.0 nefunguje

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#372]

**Comment by petrsv** [comment]
Při importu do Orisu se mi tam v posledním kroku zobrazily jen názvy kategorií a žádní závodníci.

**Comment by fvacek** [comment]
Porovnal jsem export QE s exportem z Orisu, zjistil jsem, ze mi chybi TAG `position`, bohuzel ted nemohu vyzkouset jestli tato oprava staci.

**Comment by fvacek** [comment]
Stale nefunguje, je to ale chyba v Orisu https://oris.orientacnisporty.cz/helpdesk

**Comment by arnost00** [comment]
Tak nejak se mi nepodarilo se podivat v ORISu na tuto issue. Vidim jenom svoje.

**Comment by jmacura** [comment]
@arnost00 : Ano, issues v ORISu nejsou veřejné jako na GitHubu, ale vázané na uživatele, takže se na to hlášení nepodíváme...

**Comment by fvacek** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/4949019/60297724-241b7980-9929-11e9-8874-463b59a7f6c7.png">

**Comment by janpalas** [comment]
Chyba importu byla dnes opravena na straně ORISu. Po opravě jsem to ověřil importem výsledků ve formátu IOF XML 3.0 - vše proběhlo v pořádku.

![Capture](https://user-images.githubusercontent.com/14836471/63372547-a0a96200-c386-11e9-9090-eae8c9937a9d.PNG)

**Comment by fvacek** [comment]
mel by fungovat od verze 2.3.2
