### ISSUE TITLE
Štafety - chybný startovní čas při vyčtení čipů ve špatném pořadí. Verze 2.2.2

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#376]
Pokud si někdo z jednoho úseku nevyčte čip (nebo má špatně nahlášené číslo čipu a proto se nepřiřadí jeho data ke správnému závodníkovi), pak si vyčte následující úsek a teprve poté předchozí úsek, má štafeta mnohem vyšší výsledný čas, než by měla mít, protože se nepřenastaví startovní čas dříve vyčtenému úseku.

Příklad:
vyčte 1. úsek - start 10:00, finish 35:00, čas: 25:00
vyčte 3. úsek - start **00:00**, finish 70:00, čas: **70:00**  _! špatně start, špatně celkový čas štafety 95:00_
vyčte 2. úsek - start **00:00**, finish 105:00, čas: **105:00** _! špatně start, špatně celkový čas štafety **200:00**. 3. úseku se nyní doplnil (správný) startovní čas: 70:00, ovšem závodníkovi zůstal výsledný čas 70:00._

Nyní postup pro zotavení existuje, ale je dost pracný a náchylný na chybu:
1) Asi jedině ručně změnit startovní čas 2. úseku v záložce Runs na 35:00. Tím se spraví čas druhého úseku (na 35:00) i celkový čas po 2. úseku (na 50:00), ale stále je špatně čas 3. úseku. PS: postup "Assign card to runner..." nic neudělá.
2) U 3. úseku musím zaktualizovat startovní čas, nejjednoduššeji pomocí Assign card to runner - přiřadím stejného závodníka, čímž se znovu načte a přepočte se mu startovní čas i celkový čas štafety.

Výše uvedený problém nastane během běžného závodu štafet podle mě několikrát, protože občas někdo má špatně nahlášený čip a může se stát, že pořadatel to nestihne vyřešit dříve, než doběhne následující úsek.

V okamžiku, kdy je vyčten 3. úsek, a ještě není vyčten 2. úsek, je chování celkem v pořádku,
protože nyní prostě nelze určit statovní čas, a tak je lepší, když je to 0, než cokoliv jiného, protože
jakákoliv jiná hodnota by mohla znamenat, že štafeta bude mít lepší čas než má mít správně.

V okamžiku, kdy je vyčten 2. úsek po 3. úseku, ale je možné vše automaticky napravit.

Podle mě jsou nutné 2 opravy, aby se to chovalo trochu "slušněji":
Pokud si vyčte úsek X a v dané štafetě už jsou vyčtené čipy úseků vyšších než X, pak:
1) Pokud X>1, nastavit tomuto úseku X normálně startovní čas dle cílového času úseku X-1 (nyní to funguje tak, že u tohoto úseku zůstane startovní čas NULL, není mi úplně jasné proč). Po změně startovního času přepočítat čas úseku X a celkový čas štafety po úseku X.
2) Přenastavit startovní časy a přepočítat výsledné časy všech po sobě jdoucích úseků vyšších než X (pokud zde ale je mezera, nějaký úsek chybí, pak asi končit a nic zatím dál nedělat).

Vojta

**Comment by VoiToi** [comment]
A ještě bych se rád připomněl s snad jednoduchým požadavkem z issue #104, nevím jak ostatní, ale já docela hodně často potřebuju přepočítat závodníka, většinou v případě řešení problémů jako viz výše. Nyní to asi lze udělat jen pomocí Assign card to runner...

Nebylo by možné v card readeru do kontextového menu kromě Assign card to runner přidat možnost "Reassign card" nebo "Recalculate" nebo nějaký podobný název, který udělá úplně to samé co Assign card to runner, ale ten runner bude právě ten, na kterém položku zvolím.

Díky, Vojta

**Comment by fvacek** [comment]
je to hotovy, ale bylo by fajn to nekde vyzkouset :)
