### ISSUE TITLE
Závodníci bez oraženého cíle se neexportují do výsledků - v2.2.0

### ISSUE THREAD

**Issue by janpalas** [fvacek/quickbox#379]
Všichni závodníci, kteří neorazili cíl a vyčetli si (typicky zabalení závodu, pochopitelně jsou DISK), se nevyexportují do výsledků (formát IOF XML 2.3) a tedy nejsou ve výsledcích.

(Jako workaround jsem musel ručně nastavit čas oražení cíle všem takovým závodníkům.)

Verze 2.2.0

**Comment by paukert** [comment]
> `Classic race` card checker should fix this since QE 2.2.0

viz #326 asi to ještě nebude úplně opravené..
