### ISSUE TITLE
Support SI reader station in different modes than AUTOSEND EXTENDED mode

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#38]

**Comment by OndrejSpanel** [comment]
Myslím, že už je vyřešeno, a může se zavřít.

**Comment by fvacek** [comment]
bylo by dobry, kdyby to nekdo otestoval

**Comment by OndrejSpanel** [comment]
AUTOSEND jsme teď v sobotu nepoužívali a celý závod (přes 800 lidí) vyčítali bez problémů.

**Comment by mezkov** [comment]
Při závodě 8.5. jsme také nepoužívali autosend a všech 1000+ lidí vyčetlo bez problému. Byly tam čipy řad 5, 6, 8, 9, 10, 11, SIAC a také jeden p-card a jeden čip, který začíná číslem 20, což nevím, co je.

**Comment by fvacek** [comment]
a pouzivali jste extended protokol?

**Comment by OndrejSpanel** [comment]
Měli jsme vypnuté Legacy i Autosend - nevím, jaký vztah to má k Extended.

**Comment by mezkov** [comment]
Použili jsme extended. Legacy se na doporučení SportIdentu používat nemá.

**Comment by fvacek** [comment]
Extended je opak legacy. Jestli se legacy nema pouzivat, je to otestovano a muzu zavrit issue. Diky za testovani.
