### ISSUE TITLE
QE 2.2.2 - Mistrovství pražské a středočeské oblasti štafet

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#383]
ORIS: https://oris.orientacnisporty.cz/Zavod?id=4963
Soubor QBE pro QE 2.2.2, dump a sledy: 
[staf_pgp_2019.zip](https://github.com/fvacek/quickbox/files/3104540/staf_pgp_2019.zip)

Konfigurace: 1 počítač Windows, druhý vypnutý jen tak pro sichr

Poznámky: vše klapalo, měl jsem vyzkoušené již předem klasické situace viz #376 a #378.
Na místě jsme přišli na to, že nejsme schopni identifikovat nové výsledky, tak jsme museli tisknout vždy všechny najednou - viz #381. A po závodě se ozvali 2 rankoholici, že chtějí výsledky s mezičasy, a ty neumím s "úsilím úměrným hodnotě mezičasů štafet" vyrobit (viz #382).
Potěšilo mě doplnění kódování ISO-8859-2 pro znakový tisk mezičasů přes EPSON, takže se tiskne rychle a zároveň česky a už ne bez háčků.

Jinak všechny zmíněné problémy jsou vlastně drobnosti, se kterými je pořádání docela pohodové. Za implementaci štafet do QE moc děkuji!

Vojta

**Comment by fvacek** [comment]
ja dekuji za zpetnou vazbu a testovani :)

**Comment by arnost00** [comment]
@VoiToi: Nemel bys zalohu qbe souboru stafet nekde behem zavodu nebo pred zavodem ?

**Comment by VoiToi** [comment]
> 
> 
> @VoiToi: Nemel bys zalohu qbe souboru stafet nekde behem zavodu nebo pred zavodem ?

Ahoj, nestačil by databázový dump? Dumpy se mi vytvářely snad každých 5 minut, večer se doma podívám, kolik jsem jich po závodech promazal, něco staršího tam asi bude. Pokud potřebuješ fakt QBE, tak jsem schopen je z dumpu taky za chvíli vytvořit.

**Comment by arnost00** [comment]
Stacil by mi i dump. Nemusi to byt nutne qbe. Idealne pred vyctenim prvnich zavodniku a pak treba nekde z pulky zavodu. Dik

**Comment by VoiToi** [comment]
Ahoj, doplnil přilohu jsem do prvního commentu. Vojta
