### ISSUE TITLE
Fancier module switch toolbar icons

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#384]

**Comment by otahirs** [comment]
jaké jsou požadavky na tyto ikony? 
obecné představy, formát, velikost,.. 

mohl bych zkusit přijít s nějakým návrhem

**Comment by fvacek** [comment]
Nejlepsi jsou ikony v SVG, tim se resi problemy s velikosti celkem elegantne. Jinak je to celkem otevrene. Posledni dobou frci minimalisticke ikony, coz je prima, protoze nedaji tolik prace.

**Comment by fvacek** [comment]
see branch no-qml
