### ISSUE TITLE
Špatné znázornění vakantů a vyhodnocení kolizí v záložce Runs

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#385]
Při losování jsem narazil na špatné znázorňování vakantů a vyhodnocování kolizí startovního času v záložce Runs. Pro opravu stačí vypnout a zapnout QE nebo se přepnout do jiné kategorie a zase nazpátek.

Pokud nejdříve kategorii nastavím startovní interval 2 minuty, nalosuju, poté se rozhodnu, že ten inteval by měl být třeba 4 minuty, nalosuju znovu, tak potom to vypadá nějak takhle:
![vakanti](https://user-images.githubusercontent.com/15065907/56659764-3addef80-669e-11e9-9d11-62b73ad80d8c.png)

Pokud 4 minutový interval následně změním na 3 minutový a nalosuju, tak mi zase všude hlásí kolize:
![fccab4796092af4b2bd84d911982087b](https://user-images.githubusercontent.com/15065907/56660293-8a70eb00-669f-11e9-9b22-4fba831027cf.png)

Takže bych usuzoval, že část programu, která vyhodnocuje vakanty a kolize startovních časů pracuje se starou hodnotou startovního intervalu.

**Comment by fvacek** [comment]
fixed
