### ISSUE TITLE
Neočekávané chování nástroje pro losování

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#386]
Pokud si v záložce Classes vyplním k jednotlivým kategoriím jejich start a interval a poté otevřu nástroj pro losování, tak všechny kategorie mají start stejný – 0 (v případě, že mají některé kategorie stejnou trať, tak je QE dá za sebe). Očekával bych, že pokud však vyplním pole start, tak se nástroj pro losování bude řídit tím.

Nevím, jestli je to záměr, ale nástroj pro losování vlastně na pole start vůbec nekouká, ale pouze do něj zapisuje, což může způsobit určité problémy. Pokud např. v nástroji pro losování nastavím nějaké kategorii offset 10, nástroj pro losování zavřu a za chvíli zjistím, že bych potřeboval start dané kategorie třeba o 2 minuty posunout, tak to rychleji udělám tak, že jen v poli start číslo jednoduše změním. Pokud ale následně opět otevřu nástroj pro losování, tak tam je stále ta stará hodnota startu a pokud např. po úpravě jiných kategorií kliknu na uložit, tak mi to start u té kategorie, co jsem ručně upravil, zase změní na ten původní.

**Comment by zprecek** [comment]
Chová se mi to stejně. Doplním, že pracuji s verzí 2.2.2. na Linuxu
Vypozoroval jsem, že Draw tool po spuštění vynuluje startovní časy všech kategorií, které jsou v příslušném "slotu" první v pořadí. Pokud kategorie není první, nastaví se jí startovní čas stejný, jako vypočtený poslední start v předchozí kategorii a to i přesto, že má losování uzamčeno (budiž).
Nastavení startovního času v dialogu "Edit Class" se vůbec nebere v úvahu, ani po uložení.

**Comment by zprecek** [comment]
Hm, tak fungl nová verze 2.2.3 se chová úplně stejně.
Starší verze (třeba 2.0.4) už nejsou kompatibilní s neustále se měnícím ORIS API a závod se nedá ani naimportovat.
Dost hustý vzhledem k tomu, že ráno potřebuji mít startovky na nedělní závod. :-(

**Comment by paukert** [comment]
Veškeré nastavení startovního času je potřeba udělat v drawing toolu (pokud to chceš vidět nějak znázorněné). Jak jsem psal výše, drawing tool nekouká na to, co je v poli start napsáno, ale pouze po kliknutí na uložit do něj zapíše časy, které v něm nastavíš. Pokud změníš start mimo drawing tool, tak se to v něm NIKDY neprojeví.

**Comment by fvacek** [comment]
ano, je ro tak, muzeme diskutovat o tom, jestli je to vlastnost nebo chyba, ale urcite to jeste nikomu nezabranilo v tom udelat startovky. Nastroj je tak myslen, ze startovni casy jsou presunuty, pokud se spusti, neumi totiz mezeey mezi kategoriemi.

**Comment by fvacek** [comment]
Je to dan za jednoduchost, uzivatel pak musi pouzivat jedno (rucni editaci startu) nebo druhe (tool). Kdyz to pouziva dohromady, chova se to presne takto ve vsech verzich. Drawing tool by vysel mnohem sloziteji, kdyby si nemohl presunout start kategorie. vyjjiku tvori start prvni kategorie ve slotu, to by sice slo, ale pak bych musel zase vysvetlovat, proc nekde rucni editaci zachova a u nasledujicich kategorii uz ne.

**Comment by zprecek** [comment]
Beru to spíš jako vlastnost. Díky za vysvětlení.

**Comment by fvacek** [comment]
takze ja to zavru

**Comment by paukert** [comment]
Taky v tom nevidím žádný problém, když už vím, jak to funguje. Jen se trochu obávám, že spoustu lidí, kteří začnou QE používat, by to mohlo dost překvapit. Možná by stálo za zvážení, zda při prvním otevření toolu nezobrazovat nějakou hlášku ve stylu:

"Všechny startovní časy kategorií budou po uložení změněny na hodnotu nastavenou v tomto nástroji. Při použití nástroje pro losování není doporučeno měnit startovní časy ručně v záložce kategorie (tyto změny by se v nástroji pro losování nikdy neprojevily)."

**Comment by fvacek** [comment]
to je dobrej napad

**Comment by zprecek** [comment]
Jenže když mám otevřený Draw tool, tak si kliknutím na kategorii můžu otevřít dialog Edit Class. A změna startovního času zadaná v něm se v DT taky nijak neprojeví (zatímco změna intervalu a počty vakantů ano).
Možná by stačilo v tom dialogu startovní čas jen zobrazovat.

**Comment by paukert** [comment]
jo, to by se určitě mělo nastavit jenom na read-only
