### ISSUE TITLE
QE 2.2.3 – 6. kolo VčP – 27. 4. 2019

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#388]
ORIS: https://oris.orientacnisporty.cz/Zavod?id=4866
QE soubor: [kuo_vcp2019_pozavode_final.zip](https://github.com/fvacek/quickbox/files/3141426/kuo_vcp2019_pozavode_final.zip)

Závodu se zúčastnilo 820 lidí, s QE jsme neřešili žádný zásadní problém. V zásadě jsme narazili/řešili jenom 2 věci:
1) Horizontální scrollbar ve statistikách závodu neposouvá součty:
![stat1](https://user-images.githubusercontent.com/15065907/57131681-7151f380-6d9d-11e9-9e53-c8aad1e55469.png)
![stat2](https://user-images.githubusercontent.com/15065907/57131685-731bb700-6d9d-11e9-89ac-ca4c5ebcb42e.png)

2) Nevíme, zda jsme to způsobili my nějakou špatnou manipulací s programem nebo jestli je problém s vyčítáním nějakých specifických čipů, ale asi 18x (z 846 vyčtení) se nám stalo, že při vyčítání čipu přibyly hned 2 záznamy do vyčítací fronty. První záznam byl vyčtený čip daného závodníka a druhý záznam byl celý prázdný (tj. také vyjely 2 lístečky a program začal na základě druhého záznamu pískat, že nastala chyba – "Nenalezen závodník s čipem: 0")
![chyba](https://user-images.githubusercontent.com/15065907/57132052-a0b53000-6d9e-11e9-8a1e-74d07bea60bb.png)
Bohužel mě při závodě nenapadlo zkopírovat soubor s logem programu a nyní se již k němu nedostanu (po zavření programu a jeho opětovném zapnutí byl soubor přepsán novým logem). Když koukám ale nyní zpětně do vyčítací fronty, tak se to stalo až nápadně krát u čipů s číslem 68xxxx (v závodě byl takový čip použit 7x a z toho 6x se špatně vyčetl)

Jinak všechno běželo bez problémů, díky za program :-)

**Comment by fvacek** [comment]
ad 1) #389

**Comment by fvacek** [comment]
ad 2) Vycitani bylo prepsano od zakladu a vyada to, ze s cipy rady 68xxxx jsem se dopustil nejake chyby, moc by mi pomohlo, kdybych si takovy cip mohl vypujcit.

#390

**Comment by fvacek** [comment]
diky za testovani a report :)

**Comment by arnost00** [comment]
@paukert - muzes zkusit dodat FW vycitaci krabicky a v jak byla presne nastavena ?

**Comment by paukert** [comment]
@arnost00 vyčítací krabičky jsme měli půjčené, takže se zkusím poptat a uvidím.. Každopádně máme i nějaký export z vyčítací krabičky, tak se zkusím podívat i tam.

**Comment by paukert** [comment]
V exportu dat z vyčítací krabičky bohužel žádné info o jejím nastavení není. Psal jsem lidem z VAM, kteří si brali krabičky po nás, ale žádnou odpověď jsem nedostal. Zkusím napsat ještě oddílu, kterému ty krabičky patří, protože nyní budou asi už u nich.

Co si pamatuju, tak jsme je ale měli nastavené takto (u některých voleb nevím, jestli šli nastavit..):
![3c3619059e4528148860204de3bdd98f](https://user-images.githubusercontent.com/15065907/57544022-688d8e80-7356-11e9-958f-3fb6e7300b28.png)

**Comment by fvacek** [comment]
ja si myslim, ze je to spis programem nez krabickou. Prepsal jsem vycitani from scratch a bylo by divny, kdybych tam alespon jednu chybu neudelal. U novych cipu se vycitaji pouze ty bloky, ktere jsou zaplneny, aby to bylo rychlejsi, takze je mozne, ze to nektere cipy 68xxxx vycte a nektere ne, zalezi jeste na jejich zaplneni. Moc by mi pomohlo mit cip, ktery zlobi pri vycitani k disposici.

**Comment by paukert** [comment]
Bohužel nikoho z těch lidí, co měli "problémové" čipy, asi neznáme.

**Comment by fvacek** [comment]
takze ja to tu zavru a dislusi prevedeme do #390
