### ISSUE TITLE
SI cards serie 68xxxx are not read properly

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#390]

**Comment by arnost00** [comment]
Verze 2.2.3 - 27.04.2019 - M JmO Mikulov - SI cipy v6 :
7x 51xxxx
1x 68xxxx
2x 88xxxx
2x 9xxxxx
Vsechny vycteny bez problemu. Win7 64b
Zkusim jeste najit vycitaci krabicku a napisu v jakem byla nastaveni. A jaky FW ma.

**Comment by arnost00** [comment]
Vycitaci krabicka byla :

**Comment by arnost00** [comment]
Vycitaci krabicka byla : BSM7 USB
FW : 656
Mode : RDO
Autosend : ne
Legacy protocol : ne
Si-Card6 with 192 punches : ne

**Comment by paukert** [comment]
Krabičky, které jsme používali při závodě my, byly nastavené úplně stejně. Jednalo se i o stejný typ krabičky a měla stejný FW.

Jak už jsem psal v #388, asi se mi bohužel nepodaří sehnat problémový čip, takže se to bude jen obtížně testovat.

Zatím nikdo jiný se s tímto problémem nesetkal (nebo minimálně o tom nedal vědět), takže je možné, že jsme něco pokazili my (i když teda popravdě netuším, kde bychom nějakou chybu mohli udělat).

**Comment by Osin01** [comment]
jestli se nejedná o problém se zaškrtnutím volby SI-card 6 with 192 punches při programování vyčítací krabičky viz. #239.

**Comment by paukert** [comment]
Před závodem jsem všechny krabičky procházel a pokud jsem to někde nepřehlédl, tak volba "Si-Card6 with 192 punches" byla na všech vypnuta. Stejně tomu bylo i u vyčítací krabičky, kde to bylo vypnuté určitě.

U nás k žádnému problému s mezičasy navíc nedocházelo. Pouze se kromě korektního záznamu přidal do DB i záznam, který vůbec nic neobsahoval.

**Comment by fvacek** [comment]
i tohle by bylo ale dobry opravit

**Comment by arnost00** [comment]
Jenom hlasim, ze ted na GPS se nevyskytl zadny problematicky cip v6,

**Comment by fvacek** [comment]
skvely, na HSH taky ne, tak to asi zavreme

**Comment by fvacek** [comment]
Rekl bych, ze se to deje pouze pokud je vycitaci krabicka v auto-send modu
