### ISSUE TITLE
Drawing tool shazuje QE

### ISSUE THREAD

**Issue by janzhanal** [fvacek/quickbox#392]
Pri pretazeni celeho slotu upadne QE s chybou:
[qlist.h:560]|F|  ASSERT failure in QList<T>::take: "index out of range", file /home/ota/Apps/Qt/5.12.3/gcc_64/include/QtCore/qlist.h, line 560

**Comment by otahirs** [comment]
![qe_bug](https://user-images.githubusercontent.com/24588500/57200015-5a222a00-6f86-11e9-801b-3294feb3a443.png)

**Comment by fvacek** [comment]
diky za screen-shot, je to za 20 radku vysvetlujiciho textu, opravime v pristi verzi :)
