### ISSUE TITLE
Typ kontroly ražení

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#395]
V pluginu Card reader je hned na hlavní obrazovce možnost nastavit check type (nyní možná jen jedna hodnota – Classic race). Pokud přes navigaci pluginu přistoupím na Tools/Card readout settings -> Plugin, tak se zde nachází asi pozůstatek po "starém" vyčítání.

Pokud to chápu dobře, tak se toto nastavení přesunulo na hlavní obrazovku a záložka Plugin by tedy nebyla vůbec potřeba.

![card_check](https://user-images.githubusercontent.com/15065907/57302278-1987f500-70db-11e9-9351-f55d66e1606e.png)

**Comment by fvacek** [comment]
chapes to uplne spravne :)
