### ISSUE TITLE
Classes import from ocad is not functional

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#40]
If I create new event, I'm not able to import clases from ocad. I got some ocad exports for testing, but I'm not able to import them. Log contains either those type of errors (for each class):

<ERR>[classesplugin.cpp] "W50 2,8 95 11 S1-33-54-50-62-77-60-81-70-48-75-100-F1" not found in defined classes

or warnings like this one (again, the cannot deduce... line is present for each class in import file):

<WARN>[classeswidget.cpp] "Courses are not imported, class table is read only."
<WARN>[classeswidget.cpp] cannot deduce class name, skipping line: ";D16A;0;2.200;160;S1;0.210;52;0.199;44;0.076;46;0.170;77;0.286;61;0.093;62;0.134;95;0.118;87;0.185;102;0.282;114;0.076;113;0.199;103;0.098;100;0.082;F1"

<INFO>[transaction.cpp] COMMIT
<WARN>[classeswidget.cpp] "Courses are not imported, class table is read only."

Either way, no classes are imported to the table. 
With add row button disabled, I'm not able to create event from the scratch, both options to get classes fail.

**Comment by fvacek** [comment]
W50 2,8 95 11 S1-33-54-50-62-77-60-81-70-48-75-100-F1 format is not currently supported, second one should work, Can you send me your *.qdb and faulty ocad courses export, please?

**Comment by fvacek** [comment]
fixed
