### ISSUE TITLE
Chyba založení vakantů

### ISSUE THREAD

**Issue by iriseecz** [fvacek/quickbox#400]
Při zadávání vakantů jsme nechali některá políčka prázdná, přesto se nám do každé kategorie nalosovali vakanti po.

**Comment by paukert** [comment]
Doplním, že nezáleží na tom, zda je nastavené u VA (Vacants after) 0 nebo null hodnota, pokaždé mi to přidalo na konec jednoho vakanta.

A ještě jsem si teď zpětně vzpomněl, že při losování startovky na náš závod jsem zkoušel použít funkci "Use all maps", ale např. místo 3 vakantů (měli jsme 3 mapy navíc oproti přihlášeným závodníkům) mi to do startovky nalosovalo 6 vakantů (chová se to stejně i v nejnovější verzi QE).

**Comment by fvacek** [comment]
opraveno ve verzi >= 2.2.5
