### ISSUE TITLE
QE 2.2.4 Žebříček B-Čechy východ, oblastní žebříček, 01.06.2019

### ISSUE THREAD

**Issue by ikanakova** [fvacek/quickbox#401]
Řešili jsme pouze divné chování čipu 442882, ale při odhlašování závodníků, kteří neprošli startem, jsme přišli na to, že problém byl způsoben tím, že oddíl neodhlásil závodnici, která standartně běhá s čipem 442882 a zároveň nahlásili změnu, že s jejím čipem poběží jiná závodnice - v QE mohli být přihlášeny dva závodníci se stejným čipem, bez jakéhokoliv upozornění.

[zbc_so.zip](https://github.com/fvacek/quickbox/files/3244109/zbc_so.zip)

**Comment by fvacek** [comment]
dekuji za data :)

**Comment by fvacek** [comment]
QE umoznuje start 2 i vice zavodniku se stejnym cipem, pokud se jejich pobyt v lese neprekryva. Na zebricku se to nevyuzije, ale pri ruznych treningovych zavodech ano.

**Comment by iriseecz** [comment]
Aspoň by bylo dobré nějaké upozornění ve stylu, "opravdu chcete dohlásit závodníka s čipem, který je už použit", aby si na to dal pořadatel pozor.

**Comment by fvacek** [comment]
> Aspoň by bylo dobré nějaké upozornění ve stylu, "opravdu chcete dohlásit závodníka s čipem, který je už použit", aby si na to dal pořadatel pozor.

ono to neni tak jednoduche, napriklad Oris tuto kontrolu neprovadi, takze by toto upozorneni muselo vyskakovat pomerne casto, pri kazde manipulaci s SI. QE mel puvodne unikatni klic, ktery toto zajistoval, duplicitu SI proste nedovolil na urovni databaze, jenze s tim bylo nakonec spojeno spoustu jinych uskali, jako napriklad vyse zminovane importy. Tak jsem nakonec presel na mene agresivni variantu reseni tohoto problemu, ze duplicitu povoluji. A pokud se pri vycitani podari bezrozporne priradit cip k zavodnikovi, vubec nicemu to nevadi. Ve vasem pripade se to nepodarilo a program spravne cip nepriradil, to je chvile pro operatora, ktery ma toto vyresit rucne. QE navic o teto skutecnosti informuje, viz screen-shot

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/4949019/58764968-1cf18d80-856e-11e9-8c0c-d53e7dd554fa.png">

**Comment by iriseecz** [comment]
Souhlasím - při přiřazování čipů se skutečně na problém přijde, ale pouze v případě, kdy si po přiřazení závodník znovu vyčte čip. Moje chyba, že jsem si nevšimla, že toto program umožňuje. Možná je to stejný problém jako v

**Comment by fvacek** [comment]
nene, kliknutim pravou mysi lze jakykoliv cip priradit libovolnemu zavodnikovi

**Comment by iriseecz** [comment]
To vím, ale pokud si tento závodník znovu vyčetl, QE si předchozí přiřazení nepamatoval.

**Comment by fvacek** [comment]
Ano, toto si QE nepamatuje, nemuze vedet, ze to dalsi vycteni je ten samy zavodnik, takze oped nedokaze vyhodnotit komu cip priradit. Uznavam, ze by mohl byt inteligentnejsi, ale nepodarilo se mi to vymyslet bezrozporne, tak jsem radsi zvolil variantu neprirazuj nikdy, kdyz nevis jiste. 

Resenim by mohlo byt naimplementovani funkce `FlyCheck`, ktera by zkontrolovala celou startovni listinu a upozornila poradatele na mozne problemy, myslim ze na to issue jiz existuje.
