### ISSUE TITLE
Turn on language consistency plugin in QuickBox Weblate

### ISSUE THREAD

**Issue by comradekingu** [fvacek/quickbox#404]
https://hosted.weblate.org/projects/quickbox/
It is a chore to add many components manually.
Also, having it turned on means nobody misses an added component.
Click a component, Manage* > addons/plugins> (Language consistency) +Install

**Comment by fvacek** [comment]
I'm afraid that I do not have rights to do it on my weblate account

<img width="789" alt="image" src="https://user-images.githubusercontent.com/4949019/59062609-88a56480-88a6-11e9-9cfd-d8b5a5658123.png">

**Comment by comradekingu** [comment]
@fvacek Sorry, it should be under "Manage" if QuickBox has a "administrator" tag next to it on https://hosted.weblate.org/projects/ for your account.

**Comment by fvacek** [comment]
No I do not have one. WebLate is hosting QuickBox for free. Is there something on code side (which is under my control) how I can help you with localization?

**Comment by fvacek** [comment]
5fe89dced3b8210989c56220f2b1af4913f4a9d9 might help
