### ISSUE TITLE
QE v 2.2.4 LME 9.6.2019

### ISSUE THREAD

**Issue by lme6300** [fvacek/quickbox#405]
Mam problem s importy z Orisu - napr. import registrovanych konci chybou 99 - TLS initialization failed. Co mam spatne?

**Comment by paukert** [comment]
Nevím, jestli by to tím mohlo být způsobeno, ale zkusil bych zkontrolovat nastavení závodu:

File -> Event -> Edit event -> Sport musí být nastaven na OB
(Soubor -> Závod -> Upravit závod -> Sport)

Mně jinak nyní import klubů i registrací proběhl v pořádku.

**Comment by lme6300** [comment]
To mam spravne. Jeste dodavam, ze jedu na Windows 10.

**Comment by strakator** [comment]
Videl jsem to u @lme6300 - tu adresu API, kterou to vola, mu Firefox normalne nacte. Jestli spis neni problem v ssl knihovne, kterou to pouziva nebo v korenovych certifikatech, ktere neznaji Let's Encrypt? Bohuzel to neozbrazi vic informaci, v cem je konkretne problem.

**Comment by fvacek** [comment]
Bohuzel nemam Windows, takze se to nemohu pokusit zreprodukovat. Muze nekdo, kdo ma Windows10, zkusit import z Orisu. V Linuxu mi to jde bez problemu. QE bez importu z Orisu by byl docela nesikovny.

**Comment by paukert** [comment]
Na NB, kde jsem to testoval mám:

Windows 10 Home, verze: 1903 (ale fungovalo mi to i na verzi 1809)

**Comment by janzhanal** [comment]
Otestoval jsem na win 10 PRO, 1809 bez problemu. 
@lme6300 - je mozny ze mas nejaky problem s autoritama ve svem pocitaci?
![Selection_005](https://user-images.githubusercontent.com/34436593/59089783-3ea29a00-890b-11e9-8a8f-590e3c13d22f.png)

**Comment by lme6300** [comment]
nic podezreleho jsem v "certech" nenasel, kolega se domniva, ze bych mohl mit problem ve spatne verzi OPENSSL, tak zkusim jeste instalaci SSL

**Comment by fvacek** [comment]
vygoogleoval jsem toto https://stackoverflow.com/questions/53805704/tls-initialization-failed-on-get-request 

instalace openssl by mohla pomoct

**Comment by fvacek** [comment]
https://doc.qt.io/qt-5/ssl.html

**Comment by Pjootr** [comment]
Windows 10 Pro v.1803  taky bez problému ...

**Comment by lme6300** [comment]
Musel jsem nainstalovat OpenSSSl (v 1.1.1c) a ta si vyzadala jeste instalaci vc_redist.x64, pak jiz importy zacaly chodit.

Poradani probehlo bez zadrhele, QE se jevi jako velmi spolehlivy. Zpracovali jsme 893 zavodniku, vycitani na 1 krabicku s jednou pokladni tiskarnou a bez front.

Existuje nejako soupis vsech funkci, ktere QE umi? Dostupna dokumentace pro rychle nauceni se s programem staci, ale rada ficur mi mozna zustava utajena ;-)

**Comment by fvacek** [comment]
Bohuzel ne, ja na to nemam cas, bylo par pokusu od poradatelu. Chtelo bu to asi zalozit wiki stranku *QE tips and tricks* a postupne tam dopisovat pro ostatni tato skandalni odhaleni :)

**Comment by fvacek** [comment]
https://github.com/fvacek/quickbox/wiki/Tipy-a-triky, stacilo by, kdyby tam kazdy pro ostatni napsal, na co bolestne prisel. :)
