### ISSUE TITLE
Kategorie bez vakantu - krome Nahodneho cisla nejde

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#412]
Snazim se nalosovat kategorii bez vakantu, ale furt mi to tam alespon jednoho cpe. 
Vak. P = null nebo 0, Vak. B = null nebo 0, Vak P0 = 0 (null uz tam zpetne nejde).

Je to feature nebo jsem nekde neco prehledl?

**Comment by paukert** [comment]
Myslím, že tohle by mělo být opraveno ve verzi 2.2.6

**Comment by xkenia** [comment]
Asi jsem to prave nasel, je potreba vybrat metodu losovani Nahodne cislo, pokud mam Nahodne rozmisteni klubu, tak mi tam toho vakanta cpe furt.

**Comment by paukert** [comment]
Buď asi nešlo docílit toho, aby nestartovali 2 závodníci ze stejného klubu za sebou, nebo tam někde bude chybka..

**Comment by xkenia** [comment]
V tomto pripade urcite nalosovat slo.

**Comment by fvacek** [comment]
bude tam chybka :)

**Comment by fvacek** [comment]
potreboval bych QBE soubor, nedari se mi to zreprodukovat

**Comment by xkenia** [comment]
Tak je to nejspis feature. Nevim uz to jiste, ale tipl bych, ze jsem mel zaskrtle v Kategorie -> Pouzit vsechny mapy, cimz losovani dava "Vakanty" na konec startovniho pole.

Uzviram
