### ISSUE TITLE
Nezobrazeni vakantu u kategorii typu Prichozi

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#414]
Pokud mam kategorii, kde je start 0, interval 0, tak mi statistiky zobrazi spravne pocty, ale ve vypisu kategorie vakanty nevidim, nejsou ani v tisku kategorie.

**Comment by fvacek** [comment]
Vakant je v QE mezera ve startovnim case, takze kategorie bez startovnich casu vakant mit nemohou by design.
