### ISSUE TITLE
Chyba v exportu výsledků IOF XML 2.3 - přebývá kontrola s kódem 500

### ISSUE THREAD

**Issue by janpalas** [fvacek/quickbox#420]
Když ve verzi QE 2.2.6 vyexportuji výsledky závodu do formátu IOF XML 2.3, tak všichni závodníci mají v exportu navíc poslední kontrolu s kódem 500. 

Při exportu do IOF XML 2.3 ve verzi QE 2.2.0 se tato chyba nevyskytovala. Stejně tak se chyba nevyskytuje při exportu do IOF XML 3.0 v QE 2.2.6

Přikládám tyto XML (přikládám jako TXT, XML nelze přiložit):
* Export tratí z OCADu, který byl importován do QE [E3_final.Courses.txt](https://github.com/fvacek/quickbox/files/3517238/E3_final.Courses.txt)
* Export výsledků ve formátu IOF XML 2.3 [e3-results-iof-2.3.txt](https://github.com/fvacek/quickbox/files/3517242/e3-results-iof-2.3.txt)
* Odkaz na výsledky v ORISu: https://oris.orientacnisporty.cz/Vysledky?id=4996

**Comment by janpalas** [comment]
@lukaskett Zde můžeš sledovat chybu týkající se přebývající kontroly č. 500 v mezičasech, na kterou jsi nás v neděli upozornil. Nicméně dnes došlo k opravě importu výsledků v IOF XML 3.0 na straně ORISu - viz #372 (tam se přebývající kontrola 500 nevyskytuje), takže to lze obejít tím.

**Comment by lukaskett** [comment]
@janpalas díky za upozornění. Věřím, že to @fvacek brzy opraví.

**Comment by fvacek** [comment]
potreboval bych jeste qbe soubor

**Comment by Pjootr** [comment]
Tady je jeden QBE = Rumcajsoovy Míle 2019
[mile_2019.zip](https://github.com/fvacek/quickbox/files/3563802/mile_2019.zip)

**Comment by fvacek** [comment]
diky, mrknu na to

**Comment by Pjootr** [comment]
po importu tratí z formátu IOF-XML 3.0 jsou v trati zahrnuty kontroly S(start) a F(finish) ve verzi 2.2.4 tomu tak nebylo ... zřejmě to souvisí s potřebou pro výpočet rychlosti v "min/km" **na přímém postupu** 
(což ovšem závodníky moc nezajímá), pak je ale problém při exportu do ORISu !

u Biků v Lužanech jsem smazal S(start) a nesmazal F(finish) a v ORISu se pak objevila "Kontrola (1)" před Cílem navíc -> viz. [ORIS](https://oris.orientacnisporty.cz/Mezicasy?compid=5127&classid=111842)

**Comment by fvacek** [comment]
fixed in 2.2.8
