### ISSUE TITLE
Nesjednocené názvosloví napříč programem

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#425]
Já vím, že to je asi symbol tohoto díla, ale neustálé překládání zkratek a luštění, jestli je tato zrovna v češtině či angličtině je poměrně vyčerpávající. Pro ilustraci přidávám obrázek napárování.
Čas = Time
MS = NC
VP = RR
ČT = RT
ČV = R
Chyba = E
DISK = D

Nedalo by se to sjednotit?
![Image 763](https://user-images.githubusercontent.com/18715961/64544701-be376f00-d327-11e9-9514-a0b50a8b6855.png)

**Comment by paukert** [comment]
Českou lokalizaci se snažím udžovat aktuální, ale zde asi nepomůžu.

Popravdě tohle už je dávno přeložené, jen program si to nedokáže načíst. Stejnou chybu registruju i u statistik závodu, kde jsou zdrojové řetězce taky přeložené, ale v programu je to stále v angličtině.

![preklady](https://user-images.githubusercontent.com/15065907/64546121-5898b200-d32a-11e9-9a22-3f21b702a93e.png)

**Comment by paukert** [comment]
Mělo by to být snad opraveno v #428 :-)

**Comment by fvacek** [comment]
to bude moje chyba
