### ISSUE TITLE
Stabilita vyčítání dat z krabiček

### ISSUE THREAD

**Issue by frostidllo** [fvacek/quickbox#427]
Vyčítání dat sice funguje, ale v případě, že mám v krabičce třeba 300 záznamů, tak už je extrémně nestabilní. V podstatě čím víc dat, tím větší pravděpodobnost chyby SIcommand timeout. Když jsem nebyl schopen vyčíst data z jedné krabičky ani po **100** pokusech, tak jsem se nasral a zkusil to ve SI config+. Proběhlo to na první pokus. Občas se to na pár blocích maličku zaseklo (ale třeba na sekundu), ale pak to pokračovalo dál. Problém u QE je, že když se to takhle na sekundu zasekne, tak už to nikdy nepokračuje. Šance na zásek na bloku je třeba 10% odhaduju. takže pokud mám 23 bloků, tak je pravděpodobnost vyčtení celé krabičky v podstatě nulová.

Pokud mají data v krabičce méně jak 6 bloků, tak je zpravidla vyčtu pokaždé, problém je když jich je třeba víc jak 10...

Variantou jak toto řešit by mohl být import .raw či .csv souboru z SI config+, kde to stažení dat proběhne na první pokus
![Image 767](https://user-images.githubusercontent.com/18715961/64601084-91816700-d3bc-11e9-8551-6e5a32fda7e0.png)

**Comment by fvacek** [comment]
Ano to je pravda, SportIndent prestal poskytovat informace o protokolu, takze je vycitani krabicek drobna hackerska prace, jestli se to ma zmenit, je treba tlacit na SportIdent. Navic je treba pouzivat coupling stick, to vycitani krabicek napomaha velmi.

**Comment by frostidllo** [comment]
Tak ten jsem samozřejmě používal :)
Co nějaká možnost importu souboru, který vygeneruje SI config+ ? .raw nebo .csv

**Comment by fvacek** [comment]
to by samozrejme slo, asi to bude jednodussi nez se trestat s SI uzavrenymi protokoly.

**Comment by fvacek** [comment]
https://github.com/fvacek/quickbox/issues/437
