### ISSUE TITLE
Změna čísla čipu

### ISSUE THREAD

**Issue by lukaskett** [fvacek/quickbox#430]
Pokud chci závodníkovi změnit číslo čipu, musím přepsat dvě pole, aby vše fungovalo správně. Dost nepraktické, několikrát jsem na to zapomněl.

![QE_zmena_cisla_cipu](https://user-images.githubusercontent.com/29544822/64628892-83e6d400-d3f2-11e9-9b28-4f9ef90ccd99.png)

Stejné pro přiřazení čipu závodníkovi bez vyplněného pole SI. Má v poli nulu.

Další věci, která s tímto tématem souvisí, je prohození dvou čipů, které by se taky  hodilo. To už tady zaznělo #170. V případě vložení čísla čipu, které už má nějaký závodník přiřazené, by mohlo vyskočit okno s možností čipy prohodit, resp zadat jinéčíslo čipu závodníkovi, který už vkládané číslo má.

Aktuálně je možné přiřadit více závodníkům stejné číslo čipu.

**Comment by frostidllo** [comment]
Když má závodník v poli nulu, tak stačí změnit ten údaj na obrázku vpravo nahoře a pak kliknout na E1 a hned zavřít. Pokud tam je ale už neco vyplněné, tak je to potřeba přepsat...

**Comment by martinkrivda** [comment]
Toto je zřejmě proto, aby závodník mohl běžet každou etapu víceetapovych závodů s  jiným čipem. Což mi i tak připadá nesmyslné a nepraktické, ale chápu, že to někomu může vyhovovat. Osobně, pokud se drží číslo SI takhle redundantně, si myslím, že by bylo dobré přidat warning alert zda změnit číslo čipu jak u závodníka, tak pro příslušnou etapu. V sobotu jsem na toto taky zapomněl, pak jsme měli hodně změn u vyčítání. 🙂

**Comment by fvacek** [comment]
Pokud se jedna o jednoetapovy zavod, je nejjednodussi, menit cisla cipu rocnou v tabulce Runs, nemuze dojit k chybe. Uznavam, ze pokud se jedna o jednoetapovy zavod, melo by byt cislo automaticky prepsano i z tabulky Competitors. Udelam na to issue.

**Comment by fvacek** [comment]
#433
