### ISSUE TITLE
Rozvržení startu kategorií: Chybná detekce kolize

### ISSUE THREAD

**Issue by janpalas** [fvacek/quickbox#436]
Viz obrázek - M60 má IMHO chybně označenou kolizi z W40, protože poslední závodník z M60 vystartoval ještě před první závodnící z W40, kategorie se překrývají pouze kusem posledního "prázdného intervalu" po posledním závodníkovi z M60.

![image](https://user-images.githubusercontent.com/14836471/64820197-2b5d3580-d5b0-11e9-9e73-98162034a1f1.png)

(Nepovažuji to za nějaký zásadní problém, spíš kosmetika...)

**Comment by fvacek** [comment]
no z hlediska QE to kolize je :(
