### ISSUE TITLE
EmmaClient / RaCom type exportovat závodníka i po úpravě vyčtení

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#439]
V případě, že závodník je po vyčtení z nějakého důvodu DISK a následně oddisknut, tak se poté tato změna znovu nevyexportuje. Vzniká tak rozdílnost výsledků. Ocenili bychom, kdyby se po jakékoliv úpravě (hlavně tedy oddisknutí nebo naopak disknutí) změna znovu vyexportovala.

Ještě si myslím osobně, že by nebylo na škodu přidat možnost exportu daného vyčtení do kontextového menu.
![Inkedema_export](https://user-images.githubusercontent.com/30177677/65393135-51879000-dd7d-11e9-948d-7777f20b990f.jpg)
_viz obrázek, tyto závodnice jsem oddiskl z důvodu nefunkční jednotky_

**Comment by arnost00** [comment]
Muzu poprosit o data? Potrebuji zjistit proc tam zustalo.
A taky bych poprosil o postup jakym jste oddisknuli dane zavodniky.
Nejspis tento postup oddisknuti nevymaze  DISK v miste odkud to export pro EmmaClient cte.

**Comment by martinkrivda** [comment]
data jsou v #438 .
Oddiskával jsem odtržením checkboxů **Chyba** a **DISK** v záložce vyčítání. Pokud toto je správný postup. ;-)
Co jsem koukal do exportu, tak záznam o opětovném exportu se stavem /O.K. jsem nenalezl.

> Nejspis tento postup oddisknuti nevymaze DISK v miste odkud to export pro EmmaClient cte.
A po úpravě daného vyčtení export do texťáku znovu proběhne?

**Comment by arnost00** [comment]
Nasel jsem si na webu primo tu chybnou kategorii, je to ona ?
https://liveresultat.orientering.se/followfull.php?comp=16403&lang=cz#D10C

V odkazu jsem ale objevil jen data z kratke, najdu nekdy i zminenou klasiku, nebo kde se nachazi chyba v kratke ?

V service EmmaClient lze zapnout aby se pravidelne delal export startovky (kvuli startu na krabicku) a export vysledku. Pokazde se tento soubor cely vygeneruje znovu.

**Comment by martinkrivda** [comment]
Aha pardon. To jsem si neuvědomil. Ano jedná se o tuto kategorii.
Data z klasiky jsou tady: [zb_chc_long.zip](https://github.com/fvacek/quickbox/files/3640197/zb_chc_long.zip)

**Comment by arnost00** [comment]
Nasel jsem si i vysledky v ORISu a i zde jsou dane divky diskvalifikovany :
https://oris.orientacnisporty.cz/Vysledky?id=4740#112954

Resp. se mi nepodarilo najit jak je vytisknout z daneho QBE souboru tak aby nebyly disk.
Takze prosim nejakou napovedu ... aktualne netusim co vlastne je spatne.

**Comment by martinkrivda** [comment]
@arnost00 moc se omlouvám. Jedná se o kategorii D12C, nevím proč jsem měl za to, že to byly D10C (s tou jsem řešil něco jiného a nějak si to spojil). Tak znovu a lépe.
Jedná se např. o Pipkovou Karolínu. V mezičasech ji chybí kontrola s kódem 201, oddiskl jsem ji odtržením těchto dvou checkboxů.
https://oris.orientacnisporty.cz/Mezicasy?compid=4740&classid=112918
<img width="1141" alt="d12c" src="https://user-images.githubusercontent.com/30177677/65403328-642cb400-ddd3-11e9-804a-1b5502bd4cab.png">
V ORIS je první, v liveresultat MP. Pokud disknu / oddisknu závodníka tímto způsobem, tak v exportu pro emma žádná změna nenastane.

**Comment by arnost00** [comment]
Tak jsem to zkontroloval, a vypadato to ze jste pouziili starsi verzi QE.
Vystup z aktualniho buildu (vlastni build) :
![CHC_d12c](https://user-images.githubusercontent.com/8378685/65405702-554aff00-dddd-11e9-95ee-6c1c3b460ef7.PNG)

**Comment by arnost00** [comment]
Asi bych se primluvil pro vytvoreni noveho release.

**Comment by martinkrivda** [comment]
Díky. Uzavírám toto. Do vlastního buildu se mi moc pouštět nechtělo, použili jsme release 2.2.6. Netušil jsem, že tam je už tolik změn.

**Comment by fvacek** [comment]
v nedeli poradame zavody, pri nich vetsinou najdu a opravim par chyb, pak udelam build a relaease
