### ISSUE TITLE
Možnost řazení reportu startovní listiny dle abecedy

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#440]
Startéři by ocenili možnost řadit startovní listinu pro kategorie s volným startovním časem dle abecedy - příjmení (např. pro kategorie příchozích, HDR, apod.)

Jedná se o funkcionalitu s nízkou prioritou, nicméně myslím šikovnou. Napadají mě 2 možnosti jak toto udělat.

1. Možnost nastavit něco jako Order type při generování reportu. Default by byl čas (tak jako je teď), ale byla by možnost nastavit i řazení dle abecedy, a na startovní časy by se nebral ohled.

2. Žádná konfigurace, jen v případě, že závodníci mají stejný startovní čas, tak tyto seřadit dle abecedy (nikoliv dle ID)

**Comment by paukert** [comment]
Na žádných závodech (s intervalovým startem) jsem asi neviděl seřazené závodníky podle příjmení, pokud neměli stejný startovní čas. I z tohoto důvodu bych se přikláněl k druhé možnosti (která je i snadnější na implementaci).

V případě souhlasu je úprava řazení ve startovní listině po kategoriích a klubech připravená v #444

**Comment by fvacek** [comment]
za me taky, dik
