### ISSUE TITLE
EmmaClient / RaCom type exportovat startovní čas po vyčtení

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#441]
U kategorií s volným časem startu (např. Příchozí, HDR, apod.) je v exportu startovní listiny pro EmmaClient exportován čas 000.00,0000. Pokud daný závodník startuje "na krabičku". Tak mu běží čas od nuly.

Bylo by fajn u vyčtení exportovat jak cílový čas, tak i reálný startovní čas z QE. 
_Pokud startovku vyexportuji i po vyčtení, tak stále je čas v exportu 000.00,0000. Pravděpodobně se tedy bere čas z tabulky runs. V tomto případě, pokud závodník startoval na krabičku by chtělo brát startovní čas z tabulky cards._

data jsou v #438 

![Inkedema_export_start](https://user-images.githubusercontent.com/30177677/65394348-037a8880-dd8d-11e9-8ae4-08d8769cde07.jpg)

**Comment by arnost00** [comment]
Vypada to ze ne
co jsi musel mit spatne nastaveno. Zkusil jsem data a mam tam normalni starty z cipu. 

![ZB_P](https://user-images.githubusercontent.com/8378685/65394674-18f1b180-dd91-11e9-87f9-a28862f167c5.PNG)

**Comment by arnost00** [comment]
Napada me snad jedine jestli jste mel v service EmmaClient zaskrtnut pravidelny export startovky ?

**Comment by martinkrivda** [comment]
@arnost00 to jsem neměl, kde se to nastavuje? Myslel jsem, že to QE ještě neumí. :)
Exportoval jsem ručně jednou z menu TXT.
U služby žádnou takovou možnost nevidím. Jel jsem na QE 2.2.6.

<img width="556" alt="emmaclient" src="https://user-images.githubusercontent.com/30177677/65394770-cf559680-dd91-11e9-9ce5-676eadae041a.png">

**Comment by arnost00** [comment]
Umi, v novejsi verzi nez 2.2.6,
EmmaClient dialog z aktualniho buildu :
![EmmaService](https://user-images.githubusercontent.com/8378685/65394812-7c301380-dd92-11e9-8b75-a88812d652c1.PNG)

**Comment by martinkrivda** [comment]
;-) aha. Tak v tom případě je toto už mimo. Díky.
