### ISSUE TITLE
Import rozvržení startu kategorií

### ISSUE THREAD

**Issue by martinkrivda** [fvacek/quickbox#443]
Pro rozvržení startu kategorií nepoužíváme Class layout. Podklady dostávám od stavitele a hl. rozhodčího v tabulce, která odpovídá konfiguraci QE. Tyto data poté přepisuji ručně do konfigurace. _Tabulkou v excelu vypočítáme ideální intervaly startů a starty kategorií v rámci pravidel, tak aby byl počet závodníků v lese co nejvíce rozložen._

Prosím Tě, nebyla by možnost přidat možnost importu podkladů pro losování startovních časů v CSV ve formátu stejně jako je tabulka v QE?
_Např. : Kategorie;Start;Interval;VakP;VakB;VakPO;Poslední;Map_
![Inkedimport_podkladu_pro_losovani](https://user-images.githubusercontent.com/30177677/65411562-761b5080-dded-11e9-9b0e-15d258fd1f80.jpg)

**Comment by fvacek** [comment]
Urcite jo, to by nemelo dat moc prace. Jak by se to melo jmenovat?

**Comment by fvacek** [comment]
Co funguje uz ted a co pouzivam ja pro vkladani poctu map je seradit si Excelovskou tabulku stejne jako tu v QE, uznacit v Excelu cely sloupec, dat `Ctrl-C` oznacit vrchni bunku v QE a dat `Ctrl-V`, objevi se dialog pomoci ktereho jde vlozit cely rozsah poli.

**Comment by xkenia** [comment]
Za me, pokud je moznost to copy&paste z excelu, tak je to dostatecne reseni.
