### ISSUE TITLE
Vicenasobne orazeni cile

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#447]
Mam ale zavaznejsi poznatek alespon doufam ze to tak je jak popisuji.

Predstav si kategorii ktera ma kontroly 120,121,122,123,124 a sberku 100.  Pobezim zavod  a zapomenu narazit 100. V cili jsem disk. Vratim se do lesa 100 narazim a vratim se do cile a nebudu !!! razit cil a quickEvent normalne sezere a je to bez chyb.
Predpokladam ze to muze byt i tak ze hned po startu pojdu do cile narazim cil a pak se vratim a  narazim vsechny kontroly krome cile  a pak pujdu vycit a jsem prvni :-). Ale to jsem nezkousel.
Muzes to overit jestli to co pisu je opravdu tak nebo se mi to jen zdalo ?

Dik. Zvo.

**Comment by fvacek** [comment]
SportIdent umoznuje razit cil kolikrat chces a v cipu neni zadny zaznam o tom, ze se tak stalo. QE zatim neobsahuje zadny test na vicenasobne razeni. Duvody jsou tyto:
1. to co popisujes se stava v 90% pripadu detem a prichozim, kde je podle me v poradku, kdyz si mohou chybu opravit a nezkazit si zavod, stejne je druhe orazeni cile casove poskodi.
1. casove poskozeni povazuji za dostatecny trest, diskvalifikace mi neprijde adekvatni, protoze to zavodnika casove poskozuje a ne zvyhodnuje.
1. pokud si nekdo orazi nejprve cil a pak teprve kontroly, neni to zavodnik ale podvodnik. Ja verim na fair-play, takze se mi vubec nechce programovat past na podvodniky, stejne se to ukaze v zapornem case ze sberky do cile.

**Comment by xkenia** [comment]
Tohle by mohlo byt na feature request - kontrola zapornych mezicasu. Vetsinou jsou zpusobeny spatnym naprogramovanim kontrol, ze ta predchozi ma vyssi cas nez nasledujici.
Jinak podle pravidel to v poradku neni ani v jednom pripade - pruchod cilem je povazovan za ukonceni zavodu a nasledne vstup na trat/do lesa by melo byt pouze se souhlasem rozhodciho (pokud je to takto v pokynech), ale urcite pravidla nepovoluji opravu. Na to existuje moznost penalizace. A posledni 3. bod by mel byt poresen v pokynech bodem "zavodnik je povinnen si v cili vynulovat a zkontrolovat cip", cimz si cil promaze.
