### ISSUE TITLE
Družstva - nefunguje import z ORISu, dokud nezměním Teams na Relay

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#449]
U závodu družstev je v ORISu nastaven typ závodu "Družstva", nikoliv štafety.
Nevím, proč to má speciální druh závodu, ale je to tak.

Pokud naimportuji takový závod beze změny, nenaplní se záložka Relays a tedy družstva nejsou naimportována.

Naštěstí po vybrání závodu a kliknutí na import se zobrazí dialog, kde lze vybrat typ závodu (už v QuickEventu), a pokud zde vyberu Relay místo Teams, import se podaří.

Docela se mi ulevilo, když jsem zjistil, že se alespoň takto import podaří. :-)

Vojta

**Comment by fvacek** [comment]
To jsem nedomyslel, opravime to. Jeste ze existuje workaround.

**Comment by fvacek** [comment]
fixed in 2.2.8
