### ISSUE TITLE
Štafety - závodníkům na prvním úseku se nenastavuje čas startu

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#450]
Pokud při štafetách (či družstvech) zadám ke kategorii čas startu, bohužel se tento čas startu nenastaví závodníkům na prvním úseku. Čas startu je null a po doběhnutí tento závodník má čas vypočtený od času nula. Přitom startoval třeba 5, 10, 15, 20 nebo 25.

Čas startu by šel teoreticky závodníkům vyplnit ručně, což by ale v případě 620 štafet bylo hodně práce.

Já jsem si nakonec poradil s pomocí následujícího SQL update:

```sql
UPDATE runs r SET starttimems = 60000 * (SELECT cd.starttimemin FROM relays rel
JOIN classes cl ON (cl.id = rel.classid)
JOIN classdefs cd ON (cd.classid = cl.id)
WHERE r.leg = 1 AND (r.relayid = rel.id))
WHERE r.leg = 1
```

Samozřejmě čas startu jednotlivým úsekům by se měl vyplňovat automaticky, při importu závodníka (se soupiskou nebo s přihláškou), případně pak při ručním zadávání nebo změnách soupisek. A asi by se měl také nastavit všem prvním úsekům v okamžiku, kdy uložím čas startu u kategorie.

**Comment by fvacek** [comment]
nevim, jestli je to sikovny, ale aktualne se cas prvnim usekum nastavuje losovanim

<img width="548" alt="image" src="https://user-images.githubusercontent.com/4949019/66273627-c971b200-e875-11e9-8bea-8dc0384bc0b2.png">

**Comment by VoiToi** [comment]
Aha, to mě teď nenapadlo, a posledně jsem to tak možná udělal. :-)
No, tak každopádně kdyby se ten první start nastavil automaticky, tak by to bylo blbuvzdornější.

**Comment by fvacek** [comment]
To urcite, udelam z toho feature-request, ale obavam se, ze uz tam jeden na tohle je :)

**Comment by lukaskett** [comment]
Jo na to už jsem upozorňoval, viz #354

**Comment by fvacek** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4949019/71313024-6e426b00-2433-11ea-9fd4-aa8140ec8cda.png">

na nastaveni casu prvnich useku stafet existuje specialni typ losovani, viz screen-shot. Navic jsem pridal cervene podbarveni startovniho casu prvnich useku  stafet s odlisnym startovnim casem, nez je uvedeno v `classes`
