### ISSUE TITLE
Štafety - závodník mimo soutěž nemá čas

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#453]
Nevím, zda se toto týká jen štafet, nebo i běžných závodů.

Pokud závodníkovi nastavím příznak NC (not cometing), chápu to jako Mimo soutěž, což by se mělo chovat asi ideálně tak, že závodníci jsou uvedeni ve výsledkách bez pořadí, na konci, ale s jejich skutečným časem.

Nyní se u závodníka mimo soutěž nezobrazuje pořadí (to je správně), ale ani čas, takže to spíše vypadá, jako by závodník vůbec nenastoupil.

**Comment by paukert** [comment]
Toto se bude týkat pouze štafet. Pokud na normálních závodech někoho označím jako NC (not competing = mimo soutěž), tak je uveden na konci výsledkové listiny, bez pořadí, se svým skutečným časem a příznakem NC (případně MS v české lokalizaci).

**Comment by paukert** [comment]
Jaký by mělo vlastně smysl označovat jednotlivého závodníka příznakem MS? Myslíš tím, že by celá štafeta jako celek byla MS? (viz #357)

**Comment by VoiToi** [comment]
Označovat závodníka má smysl proto, že už tam ten příznak NC je, zatímco u štafety ne. :-)
Myslím, že to je v pohodě pro označení štafety MS použít příznak u alespoň jednoho jejího závodníka.
Jinak ve výsledcích by měla být celá štafeta MS, u závodníka nic takového nedává smysl.

**Comment by fvacek** [comment]
fixed in 2.3.3
