### ISSUE TITLE
QE 2.2.6 - MČR štafet a družstev

### ISSUE THREAD

**Issue by VoiToi** [fvacek/quickbox#454]
- ORIS - štafety: https://oris.orientacnisporty.cz/Zavod?id=4308
- ORIS - družstva: https://oris.orientacnisporty.cz/Zavod?id=4309

Dumpy databáze závodu štafet (vytvářené po 5 minutách) - komprese ZIP + [7z](https://www.7-zip.org/):
[all_dumps_mcr_staf_2019.zip](https://github.com/fvacek/quickbox/files/3694733/qe_dumps.zip)

Dumpy databáze závodu MČR družstev (vytvářené po 5 minutách)- komprese ZIP + [7z](https://www.7-zip.org/):
[all_dumps_mcr_druz_2019.zip](https://github.com/fvacek/quickbox/files/3694754/all_dumps_mcr_druz_2019.zip)

Závod se celkem vydařil, největší problém se nám vyskytl v sobotu na začátku, a to nedoplněné časy startu prvních úseků, viz issue  #450.

Trochu neoptimální byl tisk výsledků - tiskli jsme periodicky všechny kategorie, protože nefungoval filtr kategorií (issue #451) a u družstev většinou najednou výsledky po 3 různých úsecích (např. 3., 4. i 5. úsek najednou, kdy na 3. úseku dobíhali poslední kousky, na 4. dobíhal střed závodního pole a na 5. dobíhala špička dětí a vetošů).

**Comment by fvacek** [comment]
dekuji za zpetnou vazbu
