### ISSUE TITLE
Nelze importovat závod z ORISu.

### ISSUE THREAD

**Issue by ikanakova** [fvacek/quickbox#456]
QuickEvent verze 2.2.8
Při importu závodu z ORISu, či synchronizaci záznamů aktuálního závodu, hází QuickEvent chybu:
![oris1](https://user-images.githubusercontent.com/38765251/66338101-b8da3e00-e940-11e9-9af9-9cddf69fd9a3.PNG)
při synchronizaci závodu (importovaného ve v. 2.2.6):
![ORIS](https://user-images.githubusercontent.com/38765251/66337925-6436c300-e940-11e9-89d9-38763f3f67e1.PNG)

**Comment by ikanakova** [comment]
@paukert nejsem si ale jistá, že je to obdobný problém - chybějící OpenSSL, protože ve verzi 2.2.6 import i synchronizace funguje bez problému.

**Comment by paukert** [comment]
@ikanakova máte pravdu, po instalaci QE 2.2.8 mi taky přestal fungovat import z ORISu. Přitom ve verzi 2.2.6 normálně funguje.

Nicméně po instalaci OpenSSL to opravdu začne zase fungovat. Návod pro instalaci OpenSSL je třeba zde: https://tecadmin.net/install-openssl-on-windows/

**Comment by ikanakova** [comment]
@paukert Zjistila jsem, že není potřeba instalovat OpenSSL, ale stačí přidat libssl a libcrypto (viz *.zip) do složky s QuickEventem (C:\Program Files\QuickEvent).
[QuickEvent.zip](https://github.com/fvacek/quickbox/files/3708918/QuickEvent.zip)

**Comment by paukert** [comment]
Nevím, co přesně způsobilo, že ve verzi 2.2.8 přestalo spojení s ORISem fungovat (a zda se to vůbec týká všech uživatelů, kteří používají Windows a kteří nemají nainstalované OpenSSL), ale pokud by tomu tak bylo a "chyba" by nešla opravit ve zdrojových kódech QuickEventu, tak by možná stálo za zvážení, jestli tyto knihovny nepřibalovat do instalačního souboru QuickBoxu, aby si je nemusel každý stahovat (nebo instalovat OpenSSL).

**Comment by Pjootr** [comment]
Mohu potvrdit, že import z ORISu mně nefunguje ani na jednom ze 3 PC (2x WIN10Pro a 1x WIN7Pro). Jsem pro přibalit zmíněné knihovny do instalačního souboru.

**Comment by paukert** [comment]
Jinak tohle bude asi taky "problém" QT viz https://wiki.qt.io/Qt_5.13.1_Known_Issues#OpenSSL

**Comment by fvacek** [comment]
tady bych odhadoval, ze problem vtresi, kdyz k instalackam QE pribalim i OpenSSL, ktere je soucasti distribuce QT

**Comment by fvacek** [comment]
zkusim pridat SSL knihovny do instalacky 2.2.9

**Comment by Pjootr** [comment]
import z ORISU ve verzi 2.2.9 nefunguje ...
pomohlo až přepsání knihoven z výše uvedeného archivu od **ikanakova**

**Comment by paukert** [comment]
Mně import z ORISu ve verzi 2.2.9 funguje (na stejném počítači ve verzi 2.2.8 nefungoval).

**Comment by fvacek** [comment]
tak nevim, co s tim dal :(

**Comment by Osin01** [comment]
Chyba se objevila i v poslední verzi 2.3.3
pomohlo až přepsání knihoven z výše uvedeného archivu od ikanakova
Nedaly by se instalačky pro příště přibalit přímo tyto konkrétní verze souborů?

**Comment by fvacek** [comment]
Tohle ja nedokazu rozhodnout. Nemam windows us 10 let a nevim, ktere libssl.dll a libcrypto.dll jsou ty spravne, chci tim rict, ze je tam muzu pribalit napr. ty od @ikanakova , ale je to workaround, ktery asi nebude fungovat dlouho. Za sebe radsi neco nevyresim, nez bych to vyresil spatne. 

Mozna bych mohl do chybove hlasky pripsat neco jako `Make sure that you have OpenSSL 1.1 installed` nebo `libssl.dll and libcrypto.dll should be installed on your system`, ale rozhodne nebudu do QE pridavat instalaci OpenSSL.

**Comment by paukert** [comment]
V současné chvíli je oficiálně podporovaná jediná verze OS windows – Windows 10.

Napadá mě, jestli třeba knihovna od @ikanakova není starší a tím pádem ještě podporuje starší/neaktualizované verze OS Windows, které třeba přibalovaná knihovna již nepodporuje.

Mně osobně funguje import na třech různých zařízeních, všechny běží na Windows 10, verze 1909.

**Comment by Osin01** [comment]
Zkoušel jsem to na dvou počítačích, aktualizovaných na poslední verzi windows 10, verze 1909.
Na jednom import fungoval pouze po nahrání knihoven od @ikanakova, na druhém fungovalo od začátku bez problémů. 
Je možné, že na tom, na kterém to fungovalo mám nainstalovanou i starší verzi open ssl z dřívějška. 
Počítač, kde to nefungovalo je prakticky čistá nová instalace windows.

Na počítači, kde to nešlo jsem testoval i starší verze a poslední fungujícící byla 2.0.4.

**Comment by arnost00** [comment]
@ikanakova nikde jsem nezaznamenal jakou verzi OS Windows pouzivate, lze prosim doplnit ?
Ma nekdo nejake zkusenosti z OS Windows starsimi nez W10 ?

**Comment by ikanakova** [comment]
@arnost00 Windows 10.

**Comment by fvacek** [comment]
@Osin01 je mozne, ze OpenSSL se na positac dostane s instalaci jineho SW a QE pak pouzije jeho knihovny.

**Comment by otahirs** [comment]
Teď dodělávám `github actions` a narazil jsem právě na SSL. Moje zjištění je takové, že je třeba přibalit takové knihovny `libcrypto-1_1-x64.dll` a `libssl-1_1-x64.dll` na které má zrovna Qt náladu. Protože zatímco ty zkopírované z instalace OpenSSL (dostupné na VM od githubu pro build windows) nefugují, tak po přepsání těmi co dodala _ikanakova _ je vše vpořádku.

**Comment by fvacek** [comment]
ukazalo se, ze take verze `vcredis` hraje velkou ulohu, v tom, jestli probalena `libssl-1_1-x64.dll` najde dependence nebo ne. Ruzne verze vcredist instalatoru jsou soucasti instalace Qt

**Comment by fvacek** [comment]
https://github.com/Quick-Event/quickbox/issues/405
