### ISSUE TITLE
Importovat kluby a registrace spolu se zavodem

### ISSUE THREAD

**Issue by otahirs** [fvacek/quickbox#457]
Ahoj,
posílám pár poznámek k uživatelskému prostředí.

 ---

1. 
Je opravdu nutné aby byl dvakrát zobrazován výběr etapy? Nešla by vybraná etapa do Runs a Classes přebírat z globálního nastavení?
![er1](https://user-images.githubusercontent.com/24588500/66581417-57081700-eb80-11e9-9194-660a29b82889.png)

---
2. 
Ocenil bych pouze jedno menu pro import závodu, obecně bych se snažil vyhnout všem duplicitám
![er2](https://user-images.githubusercontent.com/24588500/66581218-0690b980-eb80-11e9-927a-e9bc71d0bb10.png)
![er3](https://user-images.githubusercontent.com/24588500/66581223-07c1e680-eb80-11e9-831b-5acfd09df2cc.png)

---
3. přesunul bych výběr zobrazených oken ze schovaného pravého kliknutí do horní lišty 
![er4](https://user-images.githubusercontent.com/24588500/66581225-08f31380-eb80-11e9-850c-a19dc80270b9.png)

---
4.
K zaškrtávacím políčkům, např. `show off-race`, `edit on punch`,.. bych doplnil blbuvzdorné onhover vysvětlivky

**Comment by paukert** [comment]
3. výběr zobrazených oken je v horní liště pod položkou "View"
4. a) u show off-race by šlo změnit "Show off race competitors" na třeba "Show competitors who are not running in this stage."
b) u edit on punch je nyní "Edit or insert competitor on card insert into station.", to by šlo asi trošku pozměnit na "Edit or insert competitor by inserting card into the station." – jen si nejsem jistý, jestli musí být nastavená vyčítací jednotka do módu "Entries", pokud ano, tak bych to změnil na "Edit or insert competitor by inserting card into the station (reader mode "Entries" requested)."

**Comment by otahirs** [comment]
>   show off-race 

_Include competitors who are not running in this stage._

>  edit on punch

_Show Edit or Insert competitor dialog box when card is inserted into the reader station. (reader mode "Entries" required)_

**Comment by Pjootr** [comment]
1. **Current stage E1** - je ta se kterou právě pracuji (výčítám, tisknu výsledky apod.)
Stage 1,2,3 .... v Runs a Classes jsou všechny etapy vícedenních závodů a mohu se tam během kterékoliv **Current stage** podívat např. na tratě, jména závodníků nebo třeba změnit startovní čas na další etapu/y.

2. Event -> Import event = slouží k nahrání závodu ze souboru QBE
např. když potřebuji otevřít závod se starší verzí dat = tojest, když se objeví tato hláška:
![db_old](https://user-images.githubusercontent.com/49484751/66601284-d826d480-eba7-11e9-9aba-d3e21abba46b.png)
Nebo když pořádám závod v lokální DB (samostatný QBE soubor) a pak ho chci natáhnout do DB PosgtreSQL na server.

Nejedná se tedy o duplicitu.

**Comment by otahirs** [comment]
1. přišlo by my logické přepínat etapu na jednom místě, abych nemusel tápat který select zrovna použít

2. vím , že se nejedná o duplicitní funkci. Stejná logika jako v bodě 1. Když chci importovat event neměly by existovat v systému dvě potenciální místa, kde tuto fci mohu najít.

Pro webdesing a obecně GUI uživatelských aplikací platí zásada "Nenuťte uživatele přemýšlet", čemuž přímo odporuje "duplicita" položek.

**Comment by paukert** [comment]
1. myslím si, že současný stav je OK, důvody už popsal @Pjootr 
2. tady bych byl naopak pro přesunutí pod položku import, několikrát jsem tuto funkcionalitu už tady hledal

![Bez názvu](https://user-images.githubusercontent.com/15065907/66604354-49698600-ebae-11e9-9e72-2956c3df365d.png)

**Comment by otahirs** [comment]
#### Návrh na menu _Import -> Oris ->_
![clubreg](https://user-images.githubusercontent.com/24588500/66636184-f117a000-ec10-11e9-93d3-f18df1dd5863.png)

_Event_ změnit na _New event_
_Sync current event entries_ -> _Sync current entries_
sloučít import klubů a registraček -> _Clubs & Registrations_

**Comment by paukert** [comment]
Na sloučení importu klubů a registrací už tu dokonce issue je #292

**Comment by fvacek** [comment]
Rad bych z toho udelal nejaky zaver:
* bod 1 povazuji za vysvetleny a nemyslim si, ze by bylo potreba s tm neco delat
* bod 2, tady bych byl asi pro presunuti QBE importu to menu import, jak navrhuje Lukas
* import klubu a registraci bych asi dal primo k importu zavodu z Orisu a z menu ho vyndal uplne

**Comment by paukert** [comment]
>    import klubu a registraci bych asi dal primo k importu zavodu z Orisu a z menu ho vyndal uplne

To mi přijde jako hodně dobrý nápad :)

**Comment by otahirs** [comment]
> import klubu a registraci bych asi dal primo k importu zavodu z Orisu a z menu ho vyndal uplne

souhlasím, jen přemýšlím, že se může vyskytnout situace, kdy by uživatel chtěl stáhnout databázi závodníků a klubů, ale přitom neimportovat závod z orisu (závod mimo Oris, i když, kdo by to dělal)
> edit on punch

zůstává otázka: _musí být nastavená vyčítací jednotka do módu "Entries", aby toto nastavení fungovalo?_

**Comment by fvacek** [comment]
> zůstává otázka: musí být nastavená vyčítací jednotka do módu "Entries", aby toto nastavení fungovalo?

Ano

**Comment by otahirs** [comment]
Pak by bylo vhodné checkbox znepřístupnit (`disabled`, pokud něco takového Qt jednoduše podporuje), pokud je vybrán mód `race`.

**Comment by fvacek** [comment]
Ano, to by bylo fajn, jenom to pri soucasne architekture QE da necekane hodne prace. Prepokladal jsem na zacatku, ze nebudu QE psat sam, ale ze to bude system QML/C++ pluginu, o ktery se nejak podeli komunita. Ted uz bych to delal jinak, protoze jsem to odhadl spatne a monoliticka aplikace C++ aplikace by vysla lepe a jednoduseji, ale je to ted uz otazka masivniho refactoringu.

Strucne receno, jedna se o komunikaci mezi pluginy, ktere tam teoreticky ani nemusi byt soucasne nahrany (coz se asi nikdy nestane, ale je to tak bohuzel navrzeno)

**Comment by arnost00** [comment]
@otahirs Ja uz se ze závody mimo ORIS kterým se hodila registrace a oddily z ORISu setkal. Jako příklad bych uvedl každoroční oddílový přebor. 
A není BZL podobný typ závodu ? Nebo už je v ORISu ?

**Comment by fvacek** [comment]
oka, tak to tam nechame jako `registrace + kluby` a pri importu zavodu se to provede implicitne take

**Comment by otahirs** [comment]
@arnost00 
Vzhledem k tomu, že ORIS podporuje závody mimo CSOS, tak je v plánu většina akcí již tahat přes ORIS. I tak jsem ale předpokládal, že tato situace nastává a je tedy třeba zachovat možnost stažení databáze.

@fvacek 
> oka, tak to tam nechame jako registrace + kluby a pri importu zavodu se to provede implicitne take
doporučil bych pak popisek něco ve stylu `clubs & registrations only` aby bylo poznat, že u závodu se to děje implicitně

**Comment by paukert** [comment]
> oka, tak to tam nechame jako `registrace + kluby` a pri importu zavodu se to provede implicitne take

Automatický import registrací a klubů spolu se závodem ještě teda kdyžtak není hotový
