### ISSUE TITLE
Error v logu pri neotevreni zavodu - program spadne

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#459]
Mam otevreny zavod, dam Soubor -> Zavod -> Otevrit zavod, nic nevyberu, zavru formular pro vyber zavodu. Nasledne mi v logu co cca 2 vteriny vyskakuji Errory:

`Error	default	"SELECT classes.id AS classes__id, classes.name AS classes__name, classdefs.id AS classdefs__id, classdefs.classId AS classdefs__classId, classdefs.stageId AS classdefs__stageId, classdefs.courseId AS classdefs__courseId, classdefs.startSlotIndex AS classdefs__startSlotIndex, classdefs.startTimeMin AS classdefs__startTimeMin, classdefs.startIntervalMin AS classdefs__startIntervalMin, classdefs.vacantsBefore AS classdefs__vacantsBefore, classdefs.vacantEvery AS classdefs__vacantEvery, classdefs.vacantsAfter AS classdefs__vacantsAfter, classdefs.mapCount AS classdefs__mapCount, classdefs.resultsCount AS classdefs__resultsCount, classdefs.resultsPrintTS AS classdefs__resultsPrintTS, classdefs.lastStartTimeMin AS classdefs__lastStartTimeMin, classdefs.drawLock AS classdefs__drawLock, classdefs.relayStartNumber AS classdefs__relayStartNumber, classdefs.relayLegCount AS classdefs__relayLegCount, (SELECT COUNT(runs.id) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id)) AS runnersCount, (SELECT COUNT(runs.id) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.finishTimeMs > 0 OR runs.disqualified)) AS runnersFinished, (SELECT MIN(runs.startTimeMs) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.startTimeMs IS NOT NULL)) AS startFirstMs, (SELECT MAX(runs.startTimeMs) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.startTimeMs IS NOT NULL)) AS startLastMs, (SELECT MAX(timeMs) FROM (SELECT runs.timeMs FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id AND runs.timeMs>0 AND NOT runs.disqualified) ORDER BY runs.timeMs  LIMIT 1) AS results1) AS time1Ms, (SELECT MAX(timeMs) FROM (SELECT runs.timeMs FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id AND runs.timeMs>0 AND NOT runs.disqualified) ORDER BY runs.timeMs  LIMIT 3) AS results3) AS time3Ms, 0 AS timeToCloseMs, 0 AS freeMapCount, 0 AS runnersNotFinished, 0 AS resultsNotPrinted, 0 AS resultsNotPrintedSec FROM classes LEFT JOIN classdefs ON classdefs.classId=classes.id AND (classdefs.stageId=1) ORDER BY classes.name" \n "no such table: classes Unable to execute statement"	2019-10-11T09:18:39	query.cpp	43	bool qf::core::sql::Query::exec(const QString&, bool)	`

`Error	default	"SQL Error: no such table: classes Unable to execute statement\nSELECT classes.id AS classes__id, classes.name AS classes__name, classdefs.id AS classdefs__id, classdefs.classId AS classdefs__classId, classdefs.stageId AS classdefs__stageId, classdefs.courseId AS classdefs__courseId, classdefs.startSlotIndex AS classdefs__startSlotIndex, classdefs.startTimeMin AS classdefs__startTimeMin, classdefs.startIntervalMin AS classdefs__startIntervalMin, classdefs.vacantsBefore AS classdefs__vacantsBefore, classdefs.vacantEvery AS classdefs__vacantEvery, classdefs.vacantsAfter AS classdefs__vacantsAfter, classdefs.mapCount AS classdefs__mapCount, classdefs.resultsCount AS classdefs__resultsCount, classdefs.resultsPrintTS AS classdefs__resultsPrintTS, classdefs.lastStartTimeMin AS classdefs__lastStartTimeMin, classdefs.drawLock AS classdefs__drawLock, classdefs.relayStartNumber AS classdefs__relayStartNumber, classdefs.relayLegCount AS classdefs__relayLegCount, (SELECT COUNT(runs.id) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id)) AS runnersCount, (SELECT COUNT(runs.id) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.finishTimeMs > 0 OR runs.disqualified)) AS runnersFinished, (SELECT MIN(runs.startTimeMs) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.startTimeMs IS NOT NULL)) AS startFirstMs, (SELECT MAX(runs.startTimeMs) FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id) WHERE (runs.startTimeMs IS NOT NULL)) AS startLastMs, (SELECT MAX(timeMs) FROM (SELECT runs.timeMs FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id AND runs.timeMs>0 AND NOT runs.disqualified) ORDER BY runs.timeMs  LIMIT 1) AS results1) AS time1Ms, (SELECT MAX(timeMs) FROM (SELECT runs.timeMs FROM runs INNER JOIN competitors ON competitors.id=runs.competitorId AND (runs.stageId=1 AND runs.isRunning AND competitors.classId=classes.id AND runs.timeMs>0 AND NOT runs.disqualified) ORDER BY runs.timeMs  LIMIT 3) AS results3) AS time3Ms, 0 AS timeToCloseMs, 0 AS freeMapCount, 0 AS runnersNotFinished, 0 AS resultsNotPrinted, 0 AS resultsNotPrintedSec FROM classes LEFT JOIN classdefs ON classdefs.classId=classes.id AND (classdefs.stageId=1) ORDER BY classes.name"	2019-10-11T09:18:39	sqltablemodel.cpp	644	virtual bool qf::core::model::SqlTableModel::reloadTable(const QString&)	`

Pokud program zavru a znovu spustim, tak je vse v poradku.

Pokud v praci pokracuju dal, tak program spadne.

**Comment by fvacek** [comment]
fixed
