### ISSUE TITLE
Zrušení dialogu "Connect to database" znepřístupní nastavení

### ISSUE THREAD

**Issue by otahirs** [fvacek/quickbox#463]
Po kliknutí na křížek nebo Cancel v dialogu "Connect to database" se znepřístupní nastavení. ![disabled](https://user-images.githubusercontent.com/24588500/66635114-c62c4c80-ec0e-11e9-8d4f-e568279e77f5.png)

ps: připojení ke stavající databázi vypdadá býti zachováno.

**Comment by fvacek** [comment]
to je v poradku, pokud neni kam ukladat data, nelze prirozene vytvorit zavod

**Comment by otahirs** [comment]
Jedná se o situaci, kdy **již jsem připojen k databázi** a otevřu nastavení `Connect to database` a následně (křížkem nebo Cancel) dialog zruším. Pak nastává:
1. znepřístupní se mi nastavení
2. jsem stále připojen k databázi a operace se závodem dále fungují

**Comment by fvacek** [comment]
fixed in 2.2.9
