### ISSUE TITLE
Chybné "Time to close" a "Not printed time" 

### ISSUE THREAD

**Issue by otahirs** [fvacek/quickbox#466]
#### z oblže 12.10.2019, verze 2.2.8, v event statistics
"Time to close" zobrazoval pouze `0`  
"Not printed time", pokud se pamatuji dobře, byl `0.00` nebo pouze velmi blízké hodnoty

**Comment by paukert** [comment]
Related to #418

**Comment by otahirs** [comment]
duplicate of #418
