### ISSUE TITLE
Card reader -> Open COM | musí být potvrzeno současné nastavení a je třeba použít doubleclick

### ISSUE THREAD

**Issue by otahirs** [fvacek/quickbox#467]
Není možné po spuštění aplikace dát pouze `Open COM`  
Je nutné nejdříve potvrdit současné nastavení _Tools -> Card readout settings -> OK_ , pak je již `Open COM` úspěšné.

edit: linux,  2.2.8

---

PS:
Opět se zde vyskytuje duplicitní nastavení => samotné _tlačítko s ikonou  Open COM_ a nastavení v horní liště _Station->Open COM_
Doporučil bych oddělat položku z nastavení a zvýraznit samotné tlačítko

**Comment by pese76** [comment]
Můžu se zeptat, kde je to potzvrzení "Tools -> Card readout settings -> OK". Nemůžu ho v aplikaci nikde najít Verze pro WIN 2.2.8. Přesně s tímto jsme bojovali o víkendu a vyřešili až downgradem aplikace.

**Comment by paukert** [comment]
![1](https://user-images.githubusercontent.com/15065907/66721193-2e438400-ee03-11e9-96cf-a5bcdb3201e2.png)

Zde se většinou nastavuje pouze COM, potom stačí potvrdit tlačítkem OK.
![2](https://user-images.githubusercontent.com/15065907/66721194-2edc1a80-ee03-11e9-8b4c-8a3d43193a31.png)

**Comment by pese76** [comment]
Díky, ale tak to jsem nastavil asi 20x a stejně se vyčítání nerozběhnulo. (kontroloval jsem si nastavení v SI readru i nastavení com ve správci zařízení).

**Comment by pese76** [comment]
Teď už to bohužel nevyzkouším, protože u sebe nemám vyčítací jednotku. :-(

**Comment by paukert** [comment]
Jediná věc, která mě s nastavením vyčítání napadá, je ta, že QE myslím umí jen COM1-COM9, ale to by potom nevyřešil downgrade aplikace (ale např. zapojení vyčítací krabičky do jiného USB portu nebo ruční změna COMu). Jinak by @fvacek asi potřeboval trošku bližší popis problému (jestli se podařilo připojit/otevřít COM atd.)

**Comment by pese76** [comment]
Zde celý náš příběh. Bohužel o logy jsem s vymazáním adresáře QUICKEVENT asi přišel nebo nevím, kde jsou.

Připravovali jsme závod na Hradešíně 12.10.. Týden před závodem jsem dostal krabičky pražské sady a začal si  připravovat závod v QE 2.2.0 (použitý naposledy v červnu na PPŹ). Vše jsem připravil otestoval vyčítání a vše se blížilo ke zdárnému uspořádání.  Ještě jsem ve vystaveném návodu našel pár nástrojů, co jsem neviděl v aplikaci, tak jsem kouknul po aktualizacích a našel 2.2.8. Přeinstaloval verzi a dost mě překvapila změna datového modelu v PSQL (co vím o verzování, tak změna v posledním čísle by toto neměla obsahovat) nicméně povýšení databáze se podařilo přes import závodu, ale hned po tom se objevila druhá chyba – QE přestal komunikovat s ORIS pro aktualizaci závodníku. O tom jsem našel zmínku ve WIKI a po reinstalaci Win64OpenSSL-1_1_0L.exe se komunikace s ORIS opět rozběhla. Ale proč to SSL poškodilo (instalaci nové verze QE nechápu - v původní verzi to fungovalo a jediné, co jsem provedl, bylo povýšení QE). Spokojeně jsem odjel na závod, prezentace proběhla rychle a bez potíží, (zde je  QE opravdu silný a rychlý) Vše v pohodě krom detailu, že se u závodníků objevily dvě čísla SI a při dohlašování jsem nejspíše plnili to špatné . Problém ale přišel při zapojení vyčítací jednotky a nastavení správného COM, tak se po aktivaci COM objevila hláška „Chyba při nastavování SI jednotky do přímého modu“. N-krát jsem kontroloval COM a vše co dokážu nastavit, zda je vše nastaveno správně. Aplikace SI reader fungovala bez problémů a četla jeden čip za druhým, ale uvnitř QE ani tuk a vždy jen tato hláška. Pak jsem zkusil downgradeovat na původní používanou verzi 2.2.0, ale chyba se objevila opět (tentokrát v angličtině) Začali přicházet první závodníci, tak jsem zkusil poslední pokus. Odinstaloval jsem QE a odstranil všechny adresáře k němu v users a nainstaloval opět původní verzi 2.2.0 a ejhle rozběhlo se vyčítání. Naimportoval jsem z exportu závod a 15 min po příchodu prvního nadšence s žádostí o vyčtení rozjel vyčítání. Bohužel všechny dohlášky a změny čipu jsem musel při vyčtení opravit, protože číslo SI bylo v jiném parametru SI než je používán pro výpočet. Závod zachráněn, ale že jsme se zapotili a potvrzení toho, co tak nesnáším: používej staré ověřené verze. Nebo když povýšíš verzi, byť jen vyšší verzi v posledním čísle, otestuj pečlivě úplně všechno. I tak považuji za QE za dobrá SW, ale tentokrát jsem byl málem v koncích.

**Comment by pese76** [comment]
Kolega "vývojář", co se mnou seděl u compu při problémech možná ještě doplní nějaké své postřehy.

**Comment by pese76** [comment]
> Jediná věc, která mě s nastavením vyčítání napadá, je ta, že QE myslím umí jen COM1-COM9, ale to by potom nevyřešil downgrade aplikace (ale např. zapojení vyčítací krabičky do jiného USB portu nebo ruční změna COMu). Jinak by @fvacek asi potřeboval trošku bližší popis problému (jestli se podařilo připojit/otevřít COM atd.)

COM jsem si hlídal, aby byl v rozsahu a nastaven správně. O jeho správnosti mne ujišťoval SI confog a SI reader, které oba běžely. CO mne napadá, jestli tam reinstalací z 2.2.0 nezůstal nějaký starý config, který se načítal místo aktuálního.

**Comment by otahirs** [comment]
Obecně bych doporučil (sám dělám) si den před závodem vyzkoušet, jestli vše funguje (připojení s tiskárnou na kterou budu tisknout, vyčítání, tisk lístečků,..).

Jedná se stále pouze o aplikaci v aktivním vývoji ve volném čase. Vývoj probíhá zároveň pro Windows i Linux a nikdy nelze odhadnout jaká verze knihoven je zrovna na uživatelově stanici dostupná a jaké problémy se mohou objevit.

**Comment by pese76** [comment]
Jasně nestěžuji si, jen sděluji problém co nastal.

**Comment by paukert** [comment]
Při aktualizaci QE vždy raději nejdříve odinstaluju starou verzi (případně ještě odstraním automaticky nesmazené složky) a potom teprve nainstaluju novou verzi. Tím (snad z velké části) eliminuju možnost, že by tam mohlo něco zůstat ze staré verze, co by mohlo dělat nějaké problémy.

**Comment by pese76** [comment]
Už to budu dělat taky tak :-) Ale kolega zkusil na počítač kde QE nainstalován nikdy nebyl rozběhnout QE a skončil na stejné hlášce, ale možná neprovedl ono OK, kterým takto diskuze začala, zítra ověřím.

**Comment by arnost00** [comment]
Jste schopni zkusit ziskat tu SI krabicku co nespolupracovala a vyzkouset po s kolegou znovu a zkusit popsat co to kdy napsalo ?

**Comment by pese76** [comment]
Zkoušel jsem asi 3 krabičky (měli jsem velkou [pražskou SI ](https://sites.google.com/obkotlarka.cz/sportident/velk%C3%A1-souprava)sadu) v různých USB portech a vždy stejný výsledek. Pokusím se někde sehnat nějakou vyčítací krabičku a nasimulovat to znovu.

**Comment by arnost00** [comment]
Diky. 
@VoiToi - neporadali jste MCR stafet na jmenovane sade ? A pripadne fungovalo to bez problemu v tom QE ktere jste meli? (myslim ze to bylo 2.2.6).

**Comment by VoiToi** [comment]
Ahoj, ano, pořádali jsme na 2.2.6 a na tento problém jsme nenarazili. Program jsem vypínal párkrát někdy i během závodu (a za 5 sekund znovu vyčítal, takže to nikdo nepostřehl), určitě jsem před otevřením COM nelezl do dialogu s nastavením COM.

Vojta

**Comment by tsieger** [comment]
Ještě doplním pozorování, že
i) COM port šel otevřít v SI config-u i SI reader-u, jal už bylo zmíněno výše, a šlo přes něj vyčítat,
ii) QE nicméně při pokusu o vyčítání hlásil "Chyba při nastavování SI jednotky do přímého modu" a přitom jsme v app logu viděli něco ve smyslu "connected to COM" a vzápětí "COM error: 5s timeout". Nevím, zda se ten timeout počítal od otevření portu, nebo zasunutí čipu, ale od zasunutí čipu do hlášky "Chyba při nastavování SI jednotky do přímého modu" určitě uplynulo vždy méně než 5s.

Možná by bylo užitečné mít u té chybové hlášky možnost zjistit detaily, podle nichž by se dal ten problém vystopovat? Kolega koukal do zdrojáků a říkal, že ta hláška je dost nespecifická - fallback pro případ, že se prostě něco nepovede.

Díky za QE!

**Comment by pese76** [comment]
Ten error "COM error: 5s timeout" byl po aktivaci COM.  K načtení SI čipu vůbec nedocházelo. 
Jen ještě jeden postřeh, když jsem se pokušel aktivovat COM a byl aktivní SI reader objevila se jiná hláška, jako že je COM používaný,

**Comment by pese76** [comment]
Tak se mi podařilo nasimulovat chybné chování. Zde otisk logu:
![image](https://user-images.githubusercontent.com/38085837/66773292-fd288980-eebe-11e9-876e-529e489fe5c5.png)

**Comment by fvacek** [comment]
@pese76 To, co se vam pri poradani stalo je mi lito, ale musim rict, ze nejsem schopen kazdou verzi testovat, takze se to asi bude stavat znova. Napriklad tato chyba je Windows specific. Ja Windows jiz 10 let nevlastnim a nepouzivam, takze ji ani nejsem schopen odhalit pri testovani. Usporadal jsem na verzi 2.2.8 bez problemu nase zavody, takze jsem verzi 2.2.8 povazoval za otestovanou dostatecne.

Nove vlastnosti si vyzaduji nove verze, proto jich ke stazeni nechavam vic, protoze vzdy existuje riziko, ze neco pribyde a neco, co driv fungovalo, fungovat prestane. Beta jsem k nim prestal psat, protoze to bylo u vesech. Sehnal jsem si windows a chybu se mi podarilo zreprodukovat, bohuzel ji budu muset opravovat v prostredi, ktere povazuji jiz nekolik let za nepratelske vuci aplikacim vseho druhu a developerum zvlaste :)

Vzhledem k tomu, ze v Linuxu QE 2.2.8 funguje naprosto bez problemu, jedna se nejspis zase o nejakou zalezitost mimo muj kod, jako prvni zkusim ponizit verzi QT.

Fanda

**Comment by pese76** [comment]
Díky za reakci už jsem si  připadal jako blázen. I tak QE fandím.

**Comment by fvacek** [comment]
`Chyba při nastavování SI jednotky do přímého modu` znamena, ze se podarilo otevrit COM, ale nedari se komunikovat s jednotkou, QE se po pripojeni krabicky pokusi ji hned prepnout do `direct` modu, protoze se obcas stavalo, ze vycitani nefungovalo, protoze ji nekdo nastavil spravne, ale zapomnel vypnout `remote` mod. Alespon se tim vyzkousi, ze komunikace je OK, coz se ukazalo, ze ve verzi 2.2.8 na Windows neni.

**Comment by arnost00** [comment]
V sobotu 12.10. jsme delali 2 zavody (MTBO) na verzi 2.2.8 ve Windows (bud 7 nebo 8.1, ted si nejsem jist) - bez jakehokoliv problemu s vycitackou.
Pouzit vlastni build QE : 64bit, source QE 2.2.8, QT 5.13.0

**Comment by fvacek** [comment]
v instalacce je QT 5.13.1

**Comment by fvacek** [comment]
tak to vypada, ze problem je v Qt 5.13.1 pro windows, vzal jsem example serialport a nechodi taky, ten samy v Linuxu chodi, stahuju ted nejake starsi Qt.

**Comment by fvacek** [comment]
tak je to jasny, nasel jsem issue https://bugreports.qt.io/browse/QTBUG-78086 , jedna se o chybu v Qt, za coz opravdu nemuzu. Bohuzel nemam qt 5.13.0, ktere timto netrpi, takze budeme muset asi pockat do vydani 5.13.2, win instalacku radeji smazu

**Comment by paukert** [comment]
Verze 5.13.2 by měla být vydána podle release plánu za 3 dny (17. 10.)

**Comment by fvacek** [comment]
tak ja to zavru, az bude nova instalacka :)

**Comment by otahirs** [comment]
1. může někdo prosím ověřit, jestli na Linuxu je opravdu nejprve potřeba potvrdit nastavení
2. jaké nevýhody má stavět na současné LTS verzi QT?

**Comment by janzhanal** [comment]
BTW: aktualni LTS je 5.12, coz v tuto chvili neni velky skok, ale asi se postupne zvetsi

**Comment by paukert** [comment]
V tomto konkrétním případě by sestavení s poslední TLS verzí QT 5.12 (5.12.5) ale bohužel nepomohlo, chyba se vyskytuje i v této verzi. Měla by být opravená v 5.12.6 (vydání je plánováno na 31. 10.)

**Comment by fvacek** [comment]
sestavime to pozitri s 5.13.2, jestli vyjde

**Comment by fvacek** [comment]
@otahirs 

>    může někdo prosím ověřit, jestli na Linuxu je opravdu nejprve potřeba potvrdit nastavení

neni

>    jaké nevýhody má stavět na současné LTS verzi QT?

zadne

**Comment by jmacura** [comment]
> 
> @pese76 To, co se vam pri poradani stalo je mi lito, ale musim rict, ze nejsem schopen kazdou verzi testovat, takze se to asi bude stavat znova. Napriklad tato chyba je Windows specific. Ja Windows jiz 10 let nevlastnim a nepouzivam, takze ji ani nejsem schopen odhalit pri testovani. Usporadal jsem na verzi 2.2.8 bez problemu nase zavody, takze jsem verzi 2.2.8 povazoval za otestovanou dostatecne.
> 

Jen myšlenka, možná zcela mylná: nešlo by toto částečně řešit CI/CD nástroji? Nevím, jak tady na GitHubu a jak s C++/QML, ale zrovna nedávno jsem zkoušel malý projektík na GitLabu v Javě a do CI buildu lze nastavit i testy pro různá prostředí.
@OpenOrienteering již nějakou dobu také využívá Azure Pipelines pro vytváření buildů na všechny možné OS.
Nebyla by to tedy cesta, jak a) trochu více testovat QE před vypuštění do světa a b) ušetřit si práci s manulálním buildem QE?

**Comment by VoiToi** [comment]
Taky jsem zvyklý na Javu, GitLab a Github a CD a tady mi ten luxus trochu chybí. Bylo by super, kdyby takový základ, jako vyčtení čipu nebo odeslání mezičasu na tiskárnu bylo nějak automaticky testováno, ale zrovna tohle je dost integrační a platformě závislé a tak by to šlo testovat asi dost blbě. Umí někdo udělat snadno mock krabičky? V ideálním světě by něco takového poskytoval SportIdent, ale myslím, že neposkytuje.

Osobně bych vůbec neprogramoval logiku komunikace s SI a použil SPORTident Reader a jen se napojil na jeho API, čímž by se odstínily technikálie a zůstala jen logika, ale to Fanda nechtěl, protože to je jen pro Windows, které on nemá rád.

**Comment by fvacek** [comment]
> Osobně bych vůbec neprogramoval logiku komunikace s SI a použil SPORTident Reader a jen se napojil na jeho API, čímž by se odstínily technikálie a zůstala jen logika, ale to Fanda nechtěl, protože to je jen pro Windows, které on nemá rád.

a hlavne je to v .Netu, cimz bychom si natahli dalsi zavislosti. Kdyby to uvolnili v C, uz by to tam bylo.

**Comment by fvacek** [comment]
> Jen myšlenka, možná zcela mylná: nešlo by toto částečně řešit CI/CD nástroji? Nevím, jak tady na  GitHubu a jak s C++/QML, ale zrovna nedávno jsem zkoušel malý projektík na GitLabu v Javě a do CI buildu lze nastavit i testy pro různá prostředí.

Zrovna tuhle chybu dost blbe, jinak je to zamozrejme vyborny napad. Je potreba ale vzit v podtaz ze:
* Vytvareni buildu na vsechna mozna prostredi objevi jen chyby pri kompilaci. 
* Spusteni QE v ramci testovani nam taky mnoho chyb neobjevi.
* Museli bychom vytvorit funkcionalni testy, coz neni uplne snadna vec protoze
  * potrebujeme virtual + seriovy port + mockup krabicky
  * toto samo o sobe je celkem pekny projekt (hlavne mockup krabicky by mel skutecne dodavat Sportident) a my mame zoufle malo vyvojaru (cca 2)

Integracni linux build jiz mame, takze jedinou veci, kterou bychom mozna mohli udelat hned z vyse uvedeneho, je integracni Windows, Mac build.

**Comment by otahirs** [comment]
rád bych se vrátil k původní issue

> Není možné po spuštění aplikace dát pouze Open COM
Je nutné nejdříve potvrdit současné nastavení Tools -> Card readout settings -> OK , pak je již Open COM úspěšné.

V současné verzi není potřeba otvírat nastavení, je však potřeba několik pokusů než se podaří navázat spojení.
**edit: připojení je úspěšné, pokud se na tlačítko použije doubleclick**

**Comment by fvacek** [comment]
hláška "Device or resource busy" souvisi s tim, co si mysli operacni system. Ja si vubec nemyslim, ze je potreba otevirat nastveni, spis se mi zda, ze otevrenim nastaveni ziska OS cas, aby v nem neco vytimeoutovalo. Na kterem OS se to deje?

**Comment by otahirs** [comment]
Fedora
po otevření nastavení je úspěšnost tak 70%
bez něj možná 1%
...
přiznávám že netuším co se děje

**Comment by fvacek** [comment]
jeste jednou jsem se dival do kodu, settings dialog pouze nastavuje parametry pripojeni v QSettings, COMu se ani nedotkne, takze si nedovedu predstavit, jak by jeho otevreni/zavreni mohlo pomoci odstranit problem "Device or resource busy"

Mne se toto obcas stane, kdyz prepichavam vycitaci kontrolu casto, obvykle staci chvilku pockat.

**Comment by otahirs** [comment]
Máš pravdu, když spustím Quickevent, přepnu do Card reader .. počkám .., tak pak se připojím bez problémů. :+1: 

Možná bych řekl, že když kliknu na OpenCom moc brzo po zapnutí QE/připojení krabičky, tak "zahltím" COM a následně mám problém se na něj dál připojit. :thinking: Je to nějak řešitelné?

**Comment by fvacek** [comment]
to neni zahlceni COMu, Linux si mysli, ze ten COM nekdo pouziva a proto ho nechce zavrit, aby COM stih odeslat/prijmout data a jeho uzivatel o ne neprisel. Je mozny, ze ten vlastnik je QE, nevim, to se pozna utilitou `lsof`. Co se s tim da delat? Nejdriv je potreba zjistit, kvuli cemu je "device busy".

**Comment by otahirs** [comment]
`ttyUSB0` mám ve výpisu `lsof` jen když je krabička řádně připojená. Vypadá to že problém nastává pokud se snažím připojit na COM moc brzy po zapojení krabičky, dalšímy stisky tlačítka jen prodlužuji problém. Pokud vyčkám dostatečně dlouho dobu, tak se připojím.

**Comment by otahirs** [comment]
Vzhledem k tomu, že krabička se nakonec vždy připojí a řešením je počkat do 10s, asi nemá cenu vymýšlet další řešení. Jediné rozumné by mohlo být doplnit přislušnou chybovou hlášku něčím jako 
> possible solution:
Wait at least 10 seconds and then try again.

To by zabránilo horlivým jedincům zkoušet to stále dokola a jen tím oddalovat úspěšné připojení.

**Comment by otahirs** [comment]
mám připravené i následující chybové hlášky:
![Screenshot from 2020-01-10 16-26-38](https://user-images.githubusercontent.com/24588500/72164476-0a71e900-33c6-11ea-8822-bbb5a4ddc961.png)
![Screenshot from 2020-01-10 16-26-18](https://user-images.githubusercontent.com/24588500/72164478-0a71e900-33c6-11ea-9833-4108889b663c.png)

**Comment by otahirs** [comment]
hotovo #495

**Comment by otahirs** [comment]
Potvrzení nastavení se ukázalo jako nesouvisející, přičinou se ukázala přílišná horlivost a opakované dotazy na COM. Předcházet by tomu měly nové chybové hlášky.
