### ISSUE TITLE
Speaker: dopsat propis do tabulky punches pri prirazeni cipu

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#473]
Pokud priradim nenalezeny cip zavodnikovi, aktualne se nepropise do tabulky punches, kterou pouziva speaker.

**Comment by fvacek** [comment]
v tabulce `punches` jsou cisla cipu (`siId`), takze tam problem byt nemuze, bude to necim jinym.

**Comment by fvacek** [comment]
ted koukam ,ze je tam jeste `runId` takze to tim byt muze

**Comment by fvacek** [comment]
Pokud by to znamenalo, ze po prirazeni cipu zavodnikovi je treba projit punches a u tech, ktere maji `runId == 0` vyplnit runId tohoto zavodnika, melo by to jit.

**Comment by xkenia** [comment]
jo, tohle dava smysl a melo by to snad i stacit

**Comment by fvacek** [comment]
fixed in 2.3.3
