### ISSUE TITLE
Binarky v repo ?

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#476]
Je nejaky sofistikovany duvod proc jsou v repu binarky ?
Konkretne 12MB soubor - debian\quickbox\usr\bin\qsqlmon
Dle meho tam nepatri.

**Comment by fvacek** [comment]
nepatri, to jsem se musel ukliknout pri commitovani

**Comment by fvacek** [comment]
btw, muzes mi poslat link na ten soubor, zadny takovy jsem v gitu nenasel, ale treba spatne hledam

**Comment by xkenia** [comment]
https://github.com/fvacek/quickbox/blob/master/debian/quickbox/usr/bin/qsqlmon

**Comment by arnost00** [comment]
Za me to vypada ze to zpusobil commit https://github.com/fvacek/quickbox/commit/78c759bd744eeb4a45d93f4ed36d388166a63810

**Comment by ppisa** [comment]
Excuse me, I have run dpkg-buildpackage -T clean , but it seems to not clean everything. What should we do with the problem? Correct history or simple remove?

**Comment by fvacek** [comment]
simply remove is enough :)

**Comment by fvacek** [comment]
010ebf52b8c89cb3ab1a6d52768885937e4a59f3
