### ISSUE TITLE
Useky/Etapy - pri opusteni editace pole Cas se edituje i Cilovy cas

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#479]
Dam editovat pole Cas (F2 nebo dvojklik do pole) a nic nevyplnim, pri opusteni editace pole Cas se spocte Cilovy cas - v tu chvili je Cas = 0.00, takze Cilovy cas se spocte jako Startovni cas + 0.00.

**Comment by fvacek** [comment]
fixed in 2.3
