### ISSUE TITLE
Překlady - automatizace

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#48]
Při změně jakehokoliv ts souboru se bud bude muset rucne vygenerovat novy qm, nebo zautatizovat toto. Protoze i kdyz je ted pridany preklad nekterych veci do cestiny diky nevytovreni qm souboru se toto neprojevilo.

**Comment by fvacek** [comment]
Zatim to automatizovat nebudeme, nepatrne to prodlužuje preklad a dela se to jednou za cas, takze nema cenu prodluzovat kvuli tomu vyvojovy round trip

**Comment by fvacek** [comment]
there is a need to update translation files, any volunteer?

**Comment by fvacek** [comment]
Pokud bude mit QB nekdy build server, ktery bude generovat nightly builds, urcite to tam dame. Je to je pridat jeden radek do build skriptu
