### ISSUE TITLE
Problém s databází ve verzi 2.3.0

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#480]
- [x] v nové verzi QE je nějaký problém s databází – nejde importovat závod z ORISu (viz screenshot 1), nefunguje ani import staršího qbe souboru, případně export do qbe souboru (screenshot 2 respektive 3)
===========================
Kromě této chyby jsem ještě narazil na:
- [x] hlavní menu --> File je zde 2x položka "Export" (jedna neobsahuje žádnou sub-položku)
- [x] také hlavní menu --> File --> Event --> Event (\*.qbe) je zde pravděpodobně navíc, protože pro export bylo přidáno nové umístění – File --> Export --> Event (\*.qbe)

1) ![1](https://user-images.githubusercontent.com/15065907/71448206-54f23500-2739-11ea-967b-834893cd8ae8.PNG)
2) ![2](https://user-images.githubusercontent.com/15065907/71448207-56bbf880-2739-11ea-90a5-071e3313d646.PNG)
3) ![3](https://user-images.githubusercontent.com/15065907/71448210-57ed2580-2739-11ea-90bd-1b7652809483.PNG)

**Comment by fvacek** [comment]
asi jsem zase zapomnel neco pribalit do instalatoru, diky za testovani

**Comment by fvacek** [comment]
> v nové verzi QE je nějaký problém s databází – nejde importovat závod z ORISu (viz screenshot 1), nefunguje ani import staršího qbe souboru, případně export do qbe souboru (screenshot 2 respektive 3)

zapomnel jsem vytvoreni DB refaktorovat

**Comment by fvacek** [comment]
fixed in 2.3.1
