### ISSUE TITLE
Chyby ve verzi 2.3.0

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#481]
Při testování jsem ještě narazil na několik chybiček:
- [x] File --> Import --> Oris --> Sync relays entries je viditelné i pokud se nejedná o závod štafet/družstev (v dřívějších verzích to viditelné nebylo; po kliknutí na tuto možnost dostanu výjimku)
- [x] Při tisku startovních listin pro startéry je nově viditelná možnost (ale asi by být vidět neměla) tisknout vakanty, kteří ale následně ve vygenerovaném reportu nejsou
- [x] Report pro startovní listinu "Clubs n stages" je nějaký rozbitý (chybí startovní časy, zvláštní nadpis)
- [x] Při tisku výsledků po n etapách mám před tiskem možnost vybrat i typ zalomení, avšak ten ve vygenerovaném reportu není zohledněn (opravením se řeší i issue #204)
- [x] Export výsledků do IOF XML 3.0 nefunguje správně – i u závodníků, kteří mají ražení v pořádku je u mezičasů mnohokrát \<SplitTime status="Missing"\> a čas na mezičase nastaven na 0

**Comment by fvacek** [comment]
Diky za testovani :)

> Export výsledků do IOF XML 3.0 nefunguje správně – i u závodníků, kteří mají ražení v pořádku je u mezičasů mnohokrát <SplitTime status="Missing"> a čas na mezičase nastaven na 0

Zrovna tohle jsem docela testoval, moh bys prosim poslat qbe soubor, kde se to deje.

**Comment by paukert** [comment]
Tady je qbe soubor: [kuo_vcp2019_2_3_1.zip](https://github.com/fvacek/quickbox/files/4011647/kuo_vcp2019_2_3_1.zip)

Hned u první závodnice mám například v exportu tohle, ale ražení má i po přepočtu času v pořádku.

![1](https://user-images.githubusercontent.com/15065907/71606620-b1f34e00-2b72-11ea-87e2-00aafa149b2b.PNG)

**Comment by fvacek** [comment]
fixed in 2.3.2
