### ISSUE TITLE
Lokalizace (Weblate)

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#483]
Pro zachování možnosti překládat projekt QuickBox na Weblate je potřeba nastavit na Weblate nové cesty k překladovým souborům (pluginy jsou nyní v jiné složce). Dále se mohou asi odebrat komponenty, které již nejsou součástí QE (ExampleCppQml, ExamplePureQml) a naopak by se tam mohly přidat nové součásti QE, které tam nyní nejsou (libquickeventcore, libquickeventgui, libsiut).

**Comment by fvacek** [comment]
melo by to byt
