### ISSUE TITLE
Speaker plugin

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#50]
Prepare export for comment, actually ideal is to use OB2000 koment.

**Comment by fvacek** [comment]
I think that we should better create own 'koment' like plugin.

**Comment by VoiToi** [comment]
Ahoj, na kdy vypadá implementace Speaker pluginu?
Je šance, že by to fungovalo do 3 týdnů - alespoň týden před MČR KT)?
Bude se to moci využít pro zobrazování výsledků na větší obrazovce (pro tento účel by to chtělo mít asi i možnost nastavovat velikost fontu, aby se dala snadno zvolit optimální čitelnost)?

**Comment by VoiToi** [comment]
Případně, nebylo by možné udělat prioritně alespoň jednu z následujících možností:
- okno, do kterého se budou zobrazovat všechny výsledky, automaticky se budou aktualizovat a přeskakovat z kategorie na kategorii (to ale může být pracné). 
- command-line API pro export výsledků do souboru (PDF nebo HTML, klidně bez filtru kategorií). V tom případě bych si udělal externí nástroj, který bude výsledky sosat a pak v nich scrollovat, po dokončení skrolování sosne soubor znovu)...
- případně kombinaci předchozích možností (okno, kde bude scrollovat PDF s výsledkama), zkrátka co bude nejsnazší nebo bude mít šanci na nějaké budoucí využití.

Díky moc,
Vojta

**Comment by fvacek** [comment]
Existuje program QuickShow ktery dela presne moznost 1.

**Comment by fvacek** [comment]
Speaker plugin bych rad dodelal nejpozdeji do HSH, radsi drive, ale znate to jak to je s SW vyvojem :)

**Comment by VoiToi** [comment]
Tak to je super! Podařilo se mi to spustit, napoprvé to spadlo (bohužel jsem neodchytil chybovou hlášku) napodruhé běží, v logu nějaké warningy (viz níže), ale snad to i tak bude OK a poběží spolehlivě.
Díky!
```
  11<WARN>(default) QQmlVMEMetaObject: Internal error - attempted to evaluate a function in an invalid context
  12<WARN>[Cell.qml:107](default) file:///C:/Programs/OB/QuickEvent/quickshow-data/qml/Cell.qml:107: TypeError: Property 'loadData' of object QQuickRectangle_QML_1(0x41d51c0) is not a function
  13<WARN>(default) QQmlVMEMetaObject: Internal error - attempted to evaluate a function in an invalid context
  14<WARN>[Cell.qml:109](default) file:///C:/Programs/OB/QuickEvent/quickshow-data/qml/Cell.qml:109: TypeError: Property 'loadData' of object Detail_QMLTYPE_5(0x41d58e0) is not a function
  15<WARN>(default) QQmlVMEMetaObject: Internal error - attempted to evaluate a function in an invalid context
  16<WARN>[Cell.qml:109](default) file:///C:/Programs/OB/QuickEvent/quickshow-data/qml/Cell.qml:109: TypeError: Property 'loadData' of object Detail_QMLTYPE_5(0x41d1c80) is not a function
  17<WARN>(default) QQmlVMEMetaObject: Internal error - attempted to evaluate a function in an invalid context
  18<WARN>[Cell.qml:109](default) file:///C:/Programs/OB/QuickEvent/quickshow-data/qml/Cell.qml:109: TypeError: Property 'loadData' of object Detail_QMLTYPE_5(0x41d1d40) is not a function
```

**Comment by fvacek** [comment]
Nekdy to pada pri resize okna aplikace

**Comment by fvacek** [comment]
Je to takovy udelatko spichnuty horkou jehlou, ale zase je to v QML, takze se to da na miste snadno priohnout.
