### ISSUE TITLE
Nefunkční checkbox "Exclude DISQ", neviditelné tlačítko

### ISSUE THREAD

**Issue by paukert** [fvacek/quickbox#511]
Při tisku výsledků aktuální etapy a výsledků aktuální etapy pro komentátora mám možnost netisknout DISK závodníky, ve vygenerovaných reportech ale vždy jsou.

V oknu se statistikami závodu není vidět ikonka pro tisk výsledků kategorií s novými závodníky.
![icon](https://user-images.githubusercontent.com/15065907/73093297-7c762200-3ede-11ea-83d6-2f985def5959.png)

**Comment by fvacek** [comment]
fixed in 2.3.4

**Comment by paukert** [comment]
Checkbox "Exclude DISQ" u výsledků pro aktuální etapu a aktuální etapu pro komentátora pořád nefunguje (v commitu nic, co by s tím souviselo, taky nevidím).
