### ISSUE TITLE
Chyba při vytváření databáze

### ISSUE THREAD

**Issue by VojtaBlazek** [fvacek/quickbox#518]
Ahoj,
udělal jsem si instalaci na novej komp a QE mi pořád háže error:
Chyba při vytváření databáze: Parameter count mismatch
Narazil jsem na to poprvý a nevím co s tim?

Tohle se objevuje v logu:
Info	default	opening file: "C:/Users/user/Desktop/cst.qbe" driver: "QSQLITE"	2020-02-25T23:36:14	eventplugin.cpp	768	bool Event::EventPlugin::createEvent(const QString&, const QVariantMap&)	

Error	default	Load QML component error: "file:///C:/QuickEvent/qml/quickevent/Event/qmldir:-1 plugin cannot be loaded for module \"Event\": Cannot load library C:\\QuickEvent\\qml\\quickevent\\Eventplugin.dll: Uvedená procedura nebyla nalezena.\n"	2020-02-25T23:36:14	dbschema.cpp	47	QObject* DbSchema::dbSchemaRoot()	

Error	default	DbSchema QML object not created	2020-02-25T23:36:14	dbschema.cpp	58	QStringList DbSchema::createDbSqlScript(const DbSchema::CreateDbSqlScriptOptions&)	
Info	default	;	2020-02-25T23:36:14	eventplugin.cpp	785	bool Event::EventPlugin::createEvent(const QString&, const QVariantMap&)	

Warning	default	"no such table: stages Unable to execute statement"	2020-02-25T23:36:14	query.cpp	30	bool qf::core::sql::Query::prepare(const QString&, bool)

**Comment by VojtaBlazek** [comment]
Je nutný mít nainstalovaný nějaký SQL? Dřív normálně fungovalo, že jsem zvolil adresář.
Díky 
Ještě připojuji kompletní log. 
[QE_error_log.txt](https://github.com/fvacek/quickbox/files/4252533/QE_error_log.txt)

**Comment by VojtaBlazek** [comment]
Ve verzi 2.2.6 tato chyba nevzniká

**Comment by fvacek** [comment]
podle logu to vubec nenacte pluginy

**Comment by fvacek** [comment]
Tak to bude asi nejaka pracicka pro Windows specialisty, ja jsem si ted nainstaloval 2.3.2 a bezi. Muze nekdo s Windows jeste prosim vyzkouset, ze 2.3.2 a hlavne 2.3.3 nefunguje na Windows?

**Comment by Pjootr** [comment]
verzi 2.3.2 jsem testoval na halovem OB, pracoval jsem s lokalnim souborem na WIN10PRO a fungovalo to ...
problém byl jen s importem tratí z OCAD IOF XML 3.0 viz [#488](https://github.com/fvacek/quickbox/issues/488)

**Comment by paukert** [comment]
Verze 2.3.3 vyzkoušena na třech různých strojích (Windows 10 Home, verze 1909), nikde jsem na zmíněný problém nenarazil.

**Comment by VojtaBlazek** [comment]
Hmm to je divný, zkusím se na to ještě podívat.

Každopádně díky

**Comment by OndrejSpanel** [comment]
Stalo se mi teď totéž poté, co jsem instaloval QE přes nějakou hodně starou verzi. Po kompletní odinstalaci a nové instalaci už to neudělalo.

**Comment by fvacek** [comment]
Toto se muze stat, struktura instalovanych souboru se dost zmenila, takze tam nejake pozustatky starych pluginu muzou dost zlobit, obecne je lepsi starou instalaci nejprve vymazat nebo alespon prejmenovat adresar

**Comment by VojtaBlazek** [comment]
Díky moc!
Odinstaloval jsem, smazal vše co bylo v registrech a raději nainstaloval do jiné složky.
Vše funguje perfektně!
