### ISSUE TITLE
Špatná verze v popisku

### ISSUE THREAD

**Issue by jakub-h** [fvacek/quickbox#519]
Verze 2.3.3 o sobě píše, že je 2.3.2. Např. ve vygenerovaných pdf startovkách nebo v About Quick Event. Viz
![screen](https://user-images.githubusercontent.com/23062908/75494854-754ea200-59bd-11ea-9e39-c67182c8a328.png)

**Comment by paukert** [comment]
Před buildem verze 2.3.3 se pravděpodobně zapomněla upravit konstanta v souboru `quickevent/app/quickevent/src/appversion.h`, a proto je všude místo 2.3.3 napsáno 2.3.2

**Comment by jakub-h** [comment]
Už to vidím. A teď už to je připraveno na další release. Tím pádem tato issue postrádá smysl.
