### ISSUE TITLE
Test receipts printing on cash printer in windows

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#55]
Can anybody tell us, how to send character + control codes directly to USB connected cash printer on Windows?

We can easily do it on Linux writing to /dev/usb/lpx

**Comment by arnost00** [comment]
Yes there are to ways.
1) \\.\LPT1
2) \\computer_name\printer_share_name

When we want USB connected printer be accessible from LPT1 we need to : 
 - Create given printer shared
 - by "net use LPT1 \\computer_name\printer_share_name"

By now, we only need to create some "nice" solution for "normal skilled" user

Btw: My test was on TM-T70 (maybe we need rename TM-T88V to not be so specific)

**Comment by fvacek** [comment]
Great, seems to be almost as simple as on Linux. Thanks.   Viky, can you test it on your box and printer, please?

**Comment by viktorm2015** [comment]
I tried it but works only  2):
1) \\.\LPT1
 2) \\computer_name\printer_share_name
(For USB connected printer be accessible from LPT1 we need to before: 
•Create given printer shared
•by "net use LPT1 \\computer_name\printer_share_name") as Arnost wrote.
