### ISSUE TITLE
Impossible to insert new Class or CourseCode with SQLite db

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#57]
This will raise error:
<ERR>[sqltablemodel.cpp:166] Cannot prepare query: INSERT INTO codes (id) VALUES (DEFAULT)
or
<ERR>[sqltablemodel.cpp:166] Cannot prepare query: INSERT INTO classes (id) VALUES (DEFAULT)

Problem is in row 
qs = "INSERT INTO %1 (%2) VALUES (DEFAULT)";
in sqltablemodel.cpp.

For SQLite is necessary to use "INSERT INTO table DEFAULT VALUES".

**Comment by fvacek** [comment]
closing as #81 duplicate
