### ISSUE TITLE
Heavy card read/ reciepts printing traffic blocks GUI

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#61]
Printing/ card read should reside in separate threads so GUI stays responsible

**Comment by fvacek** [comment]
Qt FW is event driven, so any UI unresponsiveness is caused only by bussy-loop in code. In other words, the root cause of UI freeze is caused by bug in code, not in low number of threads used.

**Comment by arnost00** [comment]
In real time systems UI and "core" is normally separated. Why not in QE ?
We no longer live in single-thread world.

**Comment by fvacek** [comment]
Even with single threaded QE, you can launch as many QE as needed for heavy load. If you don't like a single thread world you can discover the multi-process one.

**Comment by fvacek** [comment]
What does it mean heavy load?
I think that we should find bottle neck first. Maybe we don't need more threads, maybe the implementation is just wrong.
Can you collect some profiler traces?
What is the most CPU consuming? Card readout? Receipt printing? Something else?

Why I like to avoid more threads if possible?
1. Qt is event driven system with all the advantages and disadvantages comparing to thread based concurrency approach.
2. QObject itself is not thread safe, this forces developers to write additional code to come over this fact.
3. When we'll find out that it is necessary to split QE to GUI and APP thread, than we will do it, not earlier.

**Comment by mezkov** [comment]
I did little research and tried to read card with ~20 punches on my 8 years old ntb. 

Most of time was spent on receipt printing. When using graphics printer the method ReceiptsPrinter::printReceipt took 430 ms of which rp.process() alone took 300 ms. Character printer was faster but the printReceipt still took 230 ms of which 140 ms was wasted on rp.process_html().

**Comment by fvacek** [comment]
Great, thanks for observations. Unfortunately, I'm afraid that receipts printing, which is done in QML, cannot be moved to separate thread. Even process_html cannot be moved. Anyway process_html is kind of straightforward method, so I'm quite sure that it can be optimized.

**Comment by fvacek** [comment]
can anybody check that problem persist after commit 4eecd5edc25511393f074ba656cf4fdfc2d89cc3 ?
it seems that QE was waiting for SQLite. Saving in transaction probably did a trick.

**Comment by mezkov** [comment]
Well, as I said before the main problem is printing the receipt which can take 500 ms or even more. Card readout and punches validation is not that time consuming - it takes around 80 ms.

**Comment by fvacek** [comment]
Card report is generated in ~400-500 ms. I cannot do a much about this. However, I've organized short course event with cca 600 competitors last week without any GUI lags.

**Comment by fvacek** [comment]
Too dificult to implement with current architecture, QML is not multithreaded for now.
