### ISSUE TITLE
Reciepe prints on graphical printers are unreadable sometimes

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#63]
Parts of the printing are was blacked out by black rectangles printed over reciepe text. On some reciepts were surrounded by thick black line (obiutary style)

**Comment by fvacek** [comment]
can you attach receipt scan? Anyway, I guess that it is a printer driver issue.

**Comment by fvacek** [comment]
I can randomly reproduce this on windows with thermal cash printer. But I have no idea what can I do about it. I seem that this bug is specific to printer driver + OS + ???.

**Comment by viktorm2015** [comment]
It was the same thing on  Results. The square of contens was black Especially if I printed one category. After two or three attempts I got the the correct result.

**Comment by OndrejSpanel** [comment]
We have seen this on saturday, when printing 170 receipts this has happened about 5 times. On a second print (initiated by a new readout, or by using Print receipt from the QE) it usually worked fine, but for one unlucky runner we had to repeat it four times.

I think it is not limited to a printer drivers. I was also often checking receipts manually (just to check everything is working OK), as I have seen it once in the "Show receipt" result window - the inner rectangle containing the controls and times was black.

**Comment by fvacek** [comment]
May be some kind of race condition in print code. Unfortunately is very hard to find such a kind of bug which is hard to reproduce.
