### ISSUE TITLE
Problem finding racer to associate with readout

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#64]
I was searching for Žižková, searching by name. None was found. When I searched by club name (eg. TBM if I recall correctly), Žižková was included in results. So I left the club part and start typing the name again. After inserting 'Ž', three racers whose name contained  'Ž' remained in selection. When I typed 'i', no result was displayed.
I think I expirienced similar behavior multiple times, but in this case I had time to examine. Possibly even in other searches in registrations.

**Comment by fvacek** [comment]
fixed, competitor find refactored
