### ISSUE TITLE
It's difficult to determine reason of disqualification

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#65]
If a racer is DISQ, its hard to determine why (I can look at the receipe prewiew, but it's time consuming)

**Comment by fvacek** [comment]
How many minutes during an event organization have you spent by inspecting DISQ reason looking to receipts preview? Is it really so time consuming?

**Comment by Amaroun** [comment]
Well, it's certainly not a disaster, perhaps it's more abut switching between runs/readouts/receipts lists. I give it some more thought, something feels not right here to me.

**Comment by fvacek** [comment]
following bool values are stored in database for each run currently
```
				Field { name: 'notCompeting'; type: Boolean { }
					defaultValue: false;
					notNull: true
					comment: "Competitor does run in this stage but not competing"
				},
				Field { name: 'disqualified'; type: Boolean { }
					defaultValue: false;
					notNull: true
				},
				Field { name: 'misPunch'; type: Boolean { }
					defaultValue: false;
					notNull: true
				},
```
if we find easy way how to show them in such a not obtrusive way, we can go on.

Changing to feature request with low riority.

**Comment by mezkov** [comment]
what about adding new string column to store the reason?

**Comment by Amaroun** [comment]
Is time limit considered?

**Comment by fvacek** [comment]
Time limit is not implemented yet, please create feature request for it.

**Comment by fvacek** [comment]
What about to show the disq reason directly instead of DISQ?

**Comment by Amaroun** [comment]
Yes, that would do.

**Comment by fvacek** [comment]
related to #69 and #79
