### ISSUE TITLE
Stages list is empty when entering a new competitor

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#67]
If I add a new competior, the stages list is empty. To adjust start time, I have to add the competitor, close the add dialog, find newly entered competior in the list, open it again and then adjust the time.

**Comment by fvacek** [comment]
Yes, I'm aware of it. My plan is to fix it till KUO event 10.10. 2015

**Comment by fvacek** [comment]
fixed in 4ba7d10fdc599515b68472f2d72aa978d7724e77
