### ISSUE TITLE
Adding a new competitor from registration is too complicated

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#68]
Feature request I think
Worflow for adding new competitor should go like this:
- Call the new competitor dialog (shortcut would be nice)
- Single editbox and a result table appears. The editbox has the focus. Whatever is written to it is used to search registrations (names, registration numbers, registered si card numbers together, oris style). Up/down keys selects active line in search result table, enter or space confirms selection.
- Button/ keyboard shortcut opens dialog for entering unregistered/ not found competitor (current dialog would do, without the search registrations button)
- When copetior is chosen, class and si modifications for first expected stage should be foccused.

On oblž, where many on site registrations occur, this is time critical operation, I think it deserves extra attention.

**Comment by fvacek** [comment]
looks great

**Comment by fvacek** [comment]
implemented in 4ba7d10fdc599515b68472f2d72aa978d7724e77
