### ISSUE TITLE
Find the way how to show vakants in start list

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#74]
one possible solution is to underscore lines after vakants like Runs table does with green color

**Comment by viktorm2015** [comment]
or insert empty line with eg. "*"

**Comment by xkenia** [comment]
Uderscore (or color) line after is impossible, if vacant will be last or there will be more vacants at end of start list.

**Comment by arnost00** [comment]
Some czech information about vakants handling in other O-SW : http://qe.eob.cz/vakanti.html

**Comment by arnost00** [comment]
I vote for have vacants as "empty" competitors in start list. I think this is the easiest variant for working it well and be quick for morning registration.
Now I can't see any vacants in the end of race list. I must count it from Event statistics - and this is slow for quick competitor registration.
Or we need some more complex workaround.

**Comment by fvacek** [comment]
I prefer to insert empty lines during start-list report generation. This way organizers can fill in start-list printed sheets and redundant information will not be stored in SQL. Any objections?

**Comment by fvacek** [comment]
Please, can some one check it?

**Comment by arnost00** [comment]
Small problem ... P and HDR. They start with unch start si station and all of them have start time 0.00
So startlist show any vakants.

**Comment by arnost00** [comment]
How you determine vakants on end and on begin of startlist when VB = 0, VE = n, VA = 0 and I remove same competitor from start list.
What hapend when I have vakant on 2nd time, and I remove 1st competitor ? Than I have VB = 2, VE = n-1, VA = 0 but values VB, VE and VA are still the same as before 1st competitor removal.
Or the same situation on end of startlist ?

**Comment by arnost00** [comment]
Bug - When I remove last runner in startlist, no vakant is printed in startlist.
On begin of start list vakant shown when remove first runner.

But another problem - second runner doesn't have green time (so first vakant is hidden in runs).

**Comment by fvacek** [comment]
Vacants on the end of start list are not displayed. If we want to support this, we have to add one more column to classdefs table (startFinish) and set its value after drawing.

**Comment by OndrejSpanel** [comment]
I somehow fail to understand how this is supposed to work. I have performed a drawing with vacants each 5 in all categories, but I do not see any vacants in any of the start list outputs (there are empty times in each category). Is this present in 1.0.0 beta I am using? If not, can a new release be made with this feature?

**Comment by fvacek** [comment]
This feature is not present in current beta build yet. Will be in 1.0.1. I'll try to do it tomorrow.
