### ISSUE TITLE
Check the card check-time when card read

### ISSUE THREAD

**Issue by viktorm2015** [fvacek/quickbox#79]
Doplnit časovou kontrolu Check čipu na startu, při dřívějším Check než xx min (nastavitelný parametr) před startem automaticky DISQ. Pokud parametr nastavím na 0 nebo null, neDISKkávat.

**Comment by martinkrivda** [comment]
Ahoj, jak moc náročné by pro tebe bylo dokončit tuto funkcionalitu? Považuji tuto funkci za celkem důležitou. Myslíš, že bys našel čas v dohledné době toto udělat? V opačném případě si napíši jednoduchý skript, který mi check-time zkontroluje. ;-) díky za odpověď.

**Comment by fvacek** [comment]
zas tolik ne, podivam se na to o vikendu

**Comment by fvacek** [comment]
implemented in 2.0.2

**Comment by fvacek** [comment]
aby to fungovalo, je treba prepnout typ card checkeru v CardReader pluginu na `C++ CardChecker (testing)`
