### ISSUE TITLE
Implement Receipts printer options

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#84]
Options to implement on graphics printer:
- [ ] numbers of strips per page

Options to implement on cash printer:
- [X] bind card reader to printer (each printer will serve for it's own card reader station)

**Comment by VoiToi** [comment]
+1 for this request: numbers of strips per page, so it will be possible to use laser printer for split-times (receipts).
Alternative solution would be sufficient for me: modify text printer support - when pointed to a directory, it would generate text files with random filenames, which I could take and print on my own.

**Comment by fvacek** [comment]
Alternative solution implemented in 766ae4c

**Comment by fvacek** [comment]
everybody is using cash printer, not needed IMO anymore
