### ISSUE TITLE
Import/Export read card CSV from/to SI Manager 

### ISSUE THREAD

**Issue by fvacek** [fvacek/quickbox#86]
[readcard_133441.txt](https://github.com/fvacek/quickbox/files/25690/readcard_133441.txt)

**Comment by Osin01** [comment]
Tato funkce by byla moc užitečná a dala by se použít pro dodatečné zpracování z backupu vyčítací, nebo PrintOut SI krabičky z tréninku, nebo malého závodu.
V lese si každý vytiskne lísteček z termotiskárny a závod se následně zpracuje z backupu PrintOut krabičky. Je to rychlé a jednoduché a není třeba mít v lese počítač a brát lidem čipy.
Já takto zpracovávám skoro automatizovaně oddílové i jiné malé závody z vyčtených CSV v tabulkovém procesoru, ale v QuickEventu by to bylo lepší :-).
Stejně tak se dá zachránit závod, např. když přestane fungovat počítač během závodu, vyčtené čipy jsou uloženy v backupu vyčítací krabičky.
Je tam ale myslím nějaké omezení počtu, BS7-P a BSM8 má paměť na max 1022 čipů, v závislosti na typu.
Backup má nyní jiný formát:
[readcard_136599_middle.txt](https://github.com/fvacek/quickbox/files/1447897/readcard_136599_middle.txt)

**Comment by fvacek** [comment]
from version 2.2.6 CardReader/Tools/Import
