### ISSUE TITLE
Receipts text format improvement

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#91]
When I tested character type of receipts, I found some small issues : 
1. SI card number is printed twice 
2. When runner is DISQ, it is still priinted standings

And some small improvement, for better understanding will be nice : 
1. If time loss on control is 0.00 we don't need to print it.
2. Print '+' before time loss on control
3. Print code control in brackets will be easy nice too. (OE2010 & OB2000 used it)

What do you think about it ?

**Comment by Paukert** [comment]
Pokud si to dobře pomatuju, tak to jedno SI je to, se kterým závodník běžel a to druhé, se kterým byl přihlášený. Ostatní návrhy by měly být už hotové.

**Comment by fvacek** [comment]
je to tak, jak rika Lukas
