### ISSUE TITLE
Zapamatovat nastavení tisku výsledků

### ISSUE THREAD

**Issue by viktorm2015** [fvacek/quickbox#97]
V rámci závodu zapamatovat poslední nastavení tisku výsledků. Tj. zatržítko "Class filter", WildCard x RegExp a Page layout. Během závodu se to zpravidla nemění. Pamatovat jednotně pro všechny připojené klienty.

**Comment by Paukert** [comment]
Program si pamatuje nastavení filtru při tisku startovek (výsledků), ale nepomatuje si, jestli byl filtr zapnutý nebo vypnutý (zatržítko "Class filter" // "Filtr kategorií" je vždy defaultně zatrženo).

Ještě by bylo dobré, kdyby si program pamatoval tato nastavení i při tisku z okna statistik závodu.

**Comment by fvacek** [comment]
> Ještě by bylo dobré, kdyby si program pamatoval tato nastavení i při tisku z okna statistik závodu.

tam to nema smysl, protoze class filter se pouziva na to, aby se tiskly vysledky v oznacenych radcich

**Comment by fvacek** [comment]
fixed

**Comment by Paukert** [comment]
Myslel jsem nastavení zalomení stránky, to se většinou v průběhu závodu nemění.

**Comment by fvacek** [comment]
tak to jo :)

**Comment by fvacek** [comment]
fixed

**Comment by Paukert** [comment]
Tlačítko "Save as default" funguje pouze u nastavení, které se otevře přes statistiky závodu. Pokud si nějaký filtr nastavím při tisku startovek nebo výsledků a kliknu na tlačítko "Save as default", tak se to neuloží.

**Comment by fvacek** [comment]
fixed in 1.1.7
